### ISSUE TITLE
你们可以用文档中心？

### ISSUE THREAD

**Issue by doomzhou** [aliyun/aliyun-cli#1]
http://docs.aliyun.com/ 都404了呀

**Comment by xiangxixids** [comment]
不好意思, 用这个链接呢?
https://docs.aliyun.com/?spm=5176.383338.201.97.nlXsxq#/pub/aliyun-command-line-interface

稍后我更新一下.

**Comment by doomzhou** [comment]
可以了，后来我也在下载 包里看到pdf了

**Comment by xiangxixids** [comment]
好的, 文档中心的文档有更新. 而且会比较频繁, 您可以多在文档中心查看一下. 感谢支持.
