### ISSUE TITLE
ALIBABACLOUD_PROFILE环境变量不生效

### ISSUE THREAD

**Issue by huww98** [aliyun/aliyun-cli#1039]
* **命令格式**:

* **执行命令**:

ALIBABACLOUD_PROFILE=aaa aliyun cs GET /clusters/cmyackclusterid

* **输出**:

Cluster not found, 因为指定的profile没有生效。
已验证使用--profile=aaa可以生效。
通过dlv调试
```
(dlv) b GetCurrentProfile
Breakpoint 1 set at 0x10047f6e0 for github.com/aliyun/aliyun-cli/config.(*Configuration).GetCurrentProfile() github.com/aliyun/aliyun-cli/config/configuration.go:70
```
该断点未命中。

**Comment by JacksonTian** [comment]
收到 我们确认下

**Comment by JacksonTian** [comment]
ALIBABACLOUD_PROFILE 这个之前只覆盖了配置场景，没有覆盖到 API 调用场景，下个版本的发布中会修复该问题。

**Comment by JacksonTian** [comment]
fixed in c5f35e8af0d24074fb21f0f735c33f7003077417
