### ISSUE TITLE
关于r-kvstore　sdk 无法使用

### ISSUE THREAD

**Issue by doomzhou** [aliyun/aliyun-cli#11]
通过aliyuncli r-kvstore 操作kv一直报一个错

```
{
    "Message": "Can not find endpoint to access.", 
    "Code": "SDK.InvalidRegionId"
}
```

其它jdk 都是ok的。  是否有独立的配置需要完成。

**Comment by JacksonTian** [comment]
The issue is not updated long time, I will close it now.

If any question, feel free to reopen it.
