### ISSUE TITLE
SLB DescribeCertificateRelations 接口缺失

### ISSUE THREAD

**Issue by luomoxu** [aliyun/aliyun-cli#1111]
在aliyun-cli SLB 相关api缺失 DescribeCertificateRelations
https://github.com/aliyun/aliyun-openapi-nodejs-sdk/blob/b6ea5e8baee774ffc705bc81e7392fbeab81d253/Slb-2014-05-15/lib/client.js#L1297

**Comment by CodeSpaceiiii** [comment]
> 在aliyun-cli SLB 相关api缺失 DescribeCertificateRelations https://github.com/aliyun/aliyun-openapi-nodejs-sdk/blob/b6ea5e8baee774ffc705bc81e7392fbeab81d253/Slb-2014-05-15/lib/client.js#L1297

我们看一下。

**Comment by CodeSpaceiiii** [comment]
> 在aliyun-cli SLB 相关api缺失 DescribeCertificateRelations https://github.com/aliyun/aliyun-openapi-nodejs-sdk/blob/b6ea5e8baee774ffc705bc81e7392fbeab81d253/Slb-2014-05-15/lib/client.js#L1297

这个 API 已经不是一个公开的 API，CLI 暂时无法支持，请确认是否有其他的 API 可以替代。
