### ISSUE TITLE
Add disable output color feature

### ISSUE THREAD

**Issue by xuyuji9000** [aliyun/aliyun-cli#115]
When running command `aliyun cdn --help|less`, the output is like this:

![image](https://user-images.githubusercontent.com/4877346/51433221-d5610980-1c3d-11e9-9972-3b771963da7f.png)

Maybe add disable color feature could make the output more clear.

**Comment by night556** [comment]
The problem is due to the ```less``` command can not display output with color as default, You can use command ```aliyun cnd --help | less -r``` to display output with color.

**Comment by night556** [comment]
> When running command `aliyun cdn --help|less`, the output is like this:
> 
> ![image](https://user-images.githubusercontent.com/4877346/51433221-d5610980-1c3d-11e9-9972-3b771963da7f.png)
> 
> Maybe add disable color feature could make the output more clear.

The problem is due to ```less``` command does not display color as default, you can use command ```aliyun cdn --help | less -r``` to display output with color.
