### ISSUE TITLE
3.0.235 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [aliyun/aliyun-cli#1152]
👋 there was some issue with the release build, https://github.com/aliyun/aliyun-cli/actions/runs/12047321425/job/33589621883, and the release flow was not completed. Raise this issue for awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/199215

**Comment by CodeSpaceiiii** [comment]
Thank you for your feedback. There are some minor problems with our Apple environment build, which have been fixed and version 3.0.235 has been re-released.
