### ISSUE TITLE
aliyuncli根本看不到help信息

### ISSUE THREAD

**Issue by keontang** [aliyun/aliyun-cli#12]
```
# aliyuncli ecs help
usage: aliyuncli <command> <operation> [options and parameters]
<aliyuncli> the valid command as follows:

```

都是空的

<img width="711" alt="screen shot 2016-07-13 at 13 56 06" src="https://cloud.githubusercontent.com/assets/17756696/16793975/7a19a69c-4907-11e6-8777-209a21baed8e.png">

<img width="699" alt="screen shot 2016-07-13 at 13 56 59" src="https://cloud.githubusercontent.com/assets/17756696/16793978/808f6836-4907-11e6-8a4c-cb296e79e48d.png">

**Comment by keontang** [comment]
问题已解决，通过 [https://help.aliyun.com/document_detail/30017.html](https://help.aliyun.com/document_detail/30017.html) 中的常见问题7解决。

**Comment by scaret** [comment]
同样的问题。链接已失效

**Comment by keontang** [comment]
解决方法我知道的，先问一下 @scaret 你用的是 ubuntu 的系统，是吗？

**Comment by scaret** [comment]
@keontang OSX 10.11.6

**Comment by keontang** [comment]
@scaret 苹果电脑上我没试过，你可以参考：[https://github.com/aliyun/aliyun-cli/issues/14](https://github.com/aliyun/aliyun-cli/issues/14)

**Comment by scaret** [comment]
@keontang 好的，谢谢，对OSX并不管用。好在有Google……
