### ISSUE TITLE
Feature request: mirror command for oss

### ISSUE THREAD

**Issue by zerthimon** [aliyun/aliyun-cli#13]
Would be nice to have a mirror command or a --mirror option to existing `UploadObjectFromLocalDir` command.
Mirror - make destination exactly as source.

**Comment by night556** [comment]
> xactly as source.

The oss command is compatible with the ossutil program. cli does not currently develop the actual process in the oss command.
ossutil：https://www.alibabacloud.com/help/doc-detail/50452.htm?spm=a2c65.11461447.0.0.5ef5433csE4JHz
