### ISSUE TITLE
去掉 jq 相关的调用

### ISSUE THREAD

**Issue by JacksonTian** [aliyun/aliyun-cli#148]
* **产品和接口**:
* **平台**:
* **最小代码**:

目前内置了 JSON pretty print。

**Comment by night556** [comment]
> * **产品和接口**:
> * **平台**:
> * **最小代码**:
> 
> 目前内置了 JSON pretty print。

目前jq在代码中并没有进行使用，主要在二进制文件中作为辅助命令调用，用于过滤结果，并非进行json美化过程。
