### ISSUE TITLE
Message: The specified parameter "InstanceIds" is not valid

### ISSUE THREAD

**Issue by zot11** [aliyun/aliyun-cli#154]
* **Product and API**: 2.0.12
* **Platform**: every
* **How to Reproduce** run
aliyun ecs DescribeInstances --InstanceIds ["i-***","i-***"] --profile default
and get:
Message: The specified parameter "InstanceIds" is not valid.

I see this parameter in help, And wish to see it in real

**Comment by night556** [comment]
Hi, if the value of flag is a json string, please keep it with double quotes. So the value of `--InstanceIds` should be `"['i-***','i-***']"`. Please try again like this.
If you have any other questions, please contact us.
Thank you for your attention to AliCloud CLI Project!

**Comment by night556** [comment]
> * **Product and API**: 2.0.12
> * **Platform**: every
> * **How to Reproduce** run
>   aliyun ecs DescribeInstances --InstanceIds ["i-***","i-***"] --profile default
>   and get:
>   Message: The specified parameter "InstanceIds" is not valid.
> 
> I see this parameter in help, And wish to see it in real

Hi, if the value of flag is a json string, please keep it with double quotes. So the value of --InstanceIds should be "['i-***','i-***']". Please try again like this.
If you have any other questions, please contact us.
Thank you for your attention to AliCloud CLI Project!
