### ISSUE TITLE
优化`--output`输出

### ISSUE THREAD

**Issue by night556** [aliyun/aliyun-cli#160]
* **需求分类**: 用户体验
* **描述**: 在 `--output` 的现有表格输出上增加行序号。

**Comment by domino-jiang** [comment]
# aliyun r-kvstore DescribeInstances --output cols="InstanceId"                                                                                                                                             
InstanceId
----------
<nil>

什么不输出了.哪里用错了?

**Comment by night556** [comment]
> ```
> #aliyun r-kvstore DescribeInstances --output cols=InstanceId                                                                                                                                            
> InstanceId
> ----------
> <nil>
> ```
> 什么不输出了.哪里用错了?

你好，你所过滤字段 `InstanceId` 不是包含在根元素下面的，所以你需要指定 `rows`字段，或许是这样的`rows=RootFilter[0].Instances.KVStoreInstance`

**Comment by night556** [comment]
> ```
> #aliyun r-kvstore DescribeInstances --output cols=InstanceId                                                                                                                                            
> InstanceId
> ----------
> <nil>
> ```
> 什么不输出了.哪里用错了?

**Comment by domino-jiang** [comment]
> > ```
> > #aliyun r-kvstore DescribeInstances --output cols=InstanceId                                                                                                                                            
> > InstanceId
> > ----------
> > <nil>
> > ```
> > 什么不输出了.哪里用错了?
> 
> 你好，你所过滤字段 `InstanceId` 不是包含在根元素下面的，所以你需要指定 `rows`字段，或许是这样的`rows=RootFilter[0].Instances.KVStoreInstance`

谢谢回复!

但是用起来不方便.还要去改原来写好的命令.
我先换回3.0.12了.

**Comment by night556** [comment]
> > > ```
> > > #aliyun r-kvstore DescribeInstances --output cols=InstanceId                                                                                                                                            
> > > InstanceId
> > > ----------
> > > <nil>
> > > ```
> > > 什么不输出了.哪里用错了?
> > 
> > 
> > 你好，你所过滤字段 `InstanceId` 不是包含在根元素下面的，所以你需要指定 `rows`字段，或许是这样的`rows=RootFilter[0].Instances.KVStoreInstance`
> 
> 谢谢回复!
> 
> 但是用起来不方便.还要去改原来写好的命令.
> 我先换回3.0.12了.

嗯嗯 好的呢，因为以前的output有不足，新版本的增加了根元素支持，如果需要的这个特性你可以切换到新版本，不需要则无需切换。
现有cli的内部机制将不会有大量改动，一般如果不需要最新的特性可以无需提升版本。如果还有其他问题，请联系我们。
感谢您对 Alibaba Cloud  CLI 项目的关注！
