### ISSUE TITLE
InvalidAction when using DescribePrice

### ISSUE THREAD

**Issue by roura356a** [aliyun/aliyun-cli#171]
* **Execution Command**:
`aliyun ecs DescribePrice --RegionId ap-southeast-2 --ResourceType instance --InstanceType ecs.t5-c1m1.large --PriceUnit Month --SystemDisk.Size 80 --SystemDisk.Category cloud_ssd`

* **Output**:
```bash
ERROR: SDK.ServerError
ErrorCode: InvalidAction
Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidAction&source=PopGw
RequestId: D2A0D82C-C3D2-49B9-A773-25DDB0B19AAA
Message: Specified action is not valid.
```

I'm using the latest version of the CLI tool on mac (v3.0.14). The credentials in use are root.

**Comment by night556** [comment]
> * **Execution Command**:
>   `aliyun ecs DescribePrice --RegionId ap-southeast-2 --ResourceType instance --InstanceType ecs.t5-c1m1.large --PriceUnit Month --SystemDisk.Size 80 --SystemDisk.Category cloud_ssd`
> * **Output**:
> 
> ```shell
> ERROR: SDK.ServerError
> ErrorCode: InvalidAction
> Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidAction&source=PopGw
> RequestId: D2A0D82C-C3D2-49B9-A773-25DDB0B19AAA
> Message: Specified action is not valid.
> ```
> 
> I'm using the latest version of the CLI tool on mac (v3.0.14). The credentials in use are root.

Hi, there are some restrictions on the use of this api, and if you want to know if you have permission to use this interface, please consult the product. Can you tell us where you know the existence of this interface, if it is a URL, please give us.

**Comment by roura356a** [comment]
Hi @night556. In this very tool, if you run `aliyun ecs`, the CLI tool lists as available the `DescribePrice`.

Also, I'm following https://www.alibabacloud.com/help/doc-detail/61466.htm.

**Comment by roura356a** [comment]
I opened a ticket and support engineer told me that "The ECS API does not have DescribePrice action". I should use the BSS instead. But I can see people using this Action in ECS, like https://medium.com/solution-stories/alibaba-cloud-instance-prices-8dd1176ff037

**Comment by night556** [comment]
> I opened a ticket and support engineer told me that "The ECS API does not have DescribePrice action". I should use the BSS instead. But I can see people using this Action in ECS, like https://medium.com/solution-stories/alibaba-cloud-instance-prices-8dd1176ff037

Hi, as far as we know this action is existing, and maybe you are not satisfied with the conditions of use of the action. You can try the solution that the support engineer gave you, using another action instead of the DescribePrice action.
If you have any other questions, please contact us.
Thank you for your attention to Alibaba Cloud CLI Project!

**Comment by roura356a** [comment]
Thanks @night556 👍

**Comment by endless-learner** [comment]
https://help.aliyun.com/document_detail/107829.html  This API is available but required to apply first.
