### ISSUE TITLE
OSS对象重命名

### ISSUE THREAD

**Issue by yftang** [aliyun/aliyun-cli#172]
* **需求类型**: 增加特性

* **需求描述**: 对一个对象进行重命名是我经常使用的命令，在AWS上有例如`aws s3 mv`的命令，但是阿里云CLI却一直没有。目前的解决方案大致只能是`aliyun oss cp oss://some-bucket/some/path/file.txt oss://some-bucket/some/path/filename.txt && aliyun oss rm oss://some-bucket/some/path/file.txt`，这样稍显麻烦。

* **设计方案**: `aliyun oss mv oss://some-bucket/some/path/file.txt oss://some-bucket/some/path/filename.txt`。

**Comment by night556** [comment]
> * **需求类型**: 增加特性
> * **需求描述**: 对一个对象进行重命名是我经常使用的命令，在AWS上有例如`aws s3 mv`的命令，但是阿里云CLI却一直没有。目前的解决方案大致只能是`aliyun oss cp oss://some-bucket/some/path/file.txt oss://some-bucket/some/path/filename.txt && aliyun oss rm oss://some-bucket/some/path/file.txt`，这样稍显麻烦。
> * **设计方案**: `aliyun oss mv oss://some-bucket/some/path/file.txt oss://some-bucket/some/path/filename.txt`。

您好，您的建议我们已经收到，由于各方面的原因，暂时未有排期，一旦有结果我们会回复您。
再次感谢您的建议。如果有其他问题，请与我们联系。
感谢您对阿里云 CLI 工具的关注！

**Comment by night556** [comment]
> * **需求类型**: 增加特性
> * **需求描述**: 对一个对象进行重命名是我经常使用的命令，在AWS上有例如`aws s3 mv`的命令，但是阿里云CLI却一直没有。目前的解决方案大致只能是`aliyun oss cp oss://some-bucket/some/path/file.txt oss://some-bucket/some/path/filename.txt && aliyun oss rm oss://some-bucket/some/path/file.txt`，这样稍显麻烦。
> * **设计方案**: `aliyun oss mv oss://some-bucket/some/path/file.txt oss://some-bucket/some/path/filename.txt`。

目前CLI中的oss命令是由ossutil程序兼容而来，CLI暂时不对oss命令中的实际流程进行开发。这边暂时建议您可以向ossutil项目提出需求。
