### ISSUE TITLE
建议修改默认超时时间与重试逻辑

### ISSUE THREAD

**Issue by ailan-gl** [aliyun/aliyun-cli#175]
* **需求类型**:
体验改进

* **需求描述**:
建议将默认的`retry-count`改为0，可用`--retry-count`参数来设置
默认超时时间改为10秒，增加`--timeout <seconds>`参数来指定超时时间

* **设计方案**:

**Comment by night556** [comment]
> * **需求类型**:
>   体验改进
> * **需求描述**:
>   建议将默认的`retry-count`改为0，可用`--retry-count`参数来设置
>   默认超时时间改为10秒，增加`--timeout <seconds>`参数来指定超时时间
> * **设计方案**:

请详细描述一下将默认重试次数改为0，超时时间改为 10s 所带来的体验改进之处。另这两个默认超时设置在 gosdk 里面已经有默认值了，如果用户不设置，就使用 gosdk 的值，当然用户也可以自定义用以取代 gosdk 的值。
