### ISSUE TITLE
aliyun Ecs DescribeRegions should not require region

### ISSUE THREAD

**Issue by atodorov** [aliyun/aliyun-cli#177]
```
$ aliyun Ecs DescribeRegions
ERROR: region can't be empty

Configuration failed, use `aliyun configure` to configure it
```

I need to pass a region value if I want to list all regions but if I don't know any of the exact values I need to search fro them which kind of defeats the purpose of trying to list them via the cli tool.

**Comment by night556** [comment]
> ```
> $ aliyun Ecs DescribeRegions
> ERROR: region can't be empty
> 
> Configuration failed, use `aliyun configure` to configure it
> ```
> 
> I need to pass a region value if I want to list all regions but if I don't know any of the exact values I need to search fro them which kind of defeats the purpose of trying to list them via the cli tool.

Hi, what you said does exist, but you must ensure that your region is correct before using the CLI. The initial region can be obtained from the official website: https://www.alibabacloud.com/help/doc-detail/40654.htm?spm=a2c63.l28256.a3.4.74c879acxygWcK .
