### ISSUE TITLE
win10 上 UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 2016: illegal multibyte sequence

### ISSUE THREAD

**Issue by chenshuchuan** [aliyun/aliyun-cli#183]
win10 上安装时候出现编码问题

执行命令:
```
pip install aliyuncli
```
```
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting aliyuncli
  Downloading https://mirrors.aliyun.com/pypi/packages/f2/38/a44b5a5d7a33e258113eb88de865c36f14c4d034d17b57ade7dffadab919/aliyuncli-2.1.5.tar.gz (60kB)
     |████████████████████████████████| 61kB 3.8MB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m90ti_ox\aliyuncli\setup.py", line 54, in <module>
        main()
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m90ti_ox\aliyuncli\setup.py", line 34, in main
        long_description = open("README.rst").read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 2016: illegal multibyte sequence
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m90ti_ox\aliyuncli\
```

**Comment by night556** [comment]
> win10 上安装时候出现编码问题
> 
> 执行命令:
> 
> ```
> pip install aliyuncli
> ```
> 
> ```
> Looking in indexes: https://mirrors.aliyun.com/pypi/simple
> Collecting aliyuncli
>   Downloading https://mirrors.aliyun.com/pypi/packages/f2/38/a44b5a5d7a33e258113eb88de865c36f14c4d034d17b57ade7dffadab919/aliyuncli-2.1.5.tar.gz (60kB)
>      |████████████████████████████████| 61kB 3.8MB/s
>     ERROR: Complete output from command python setup.py egg_info:
>     ERROR: Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m90ti_ox\aliyuncli\setup.py", line 54, in <module>
>         main()
>       File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m90ti_ox\aliyuncli\setup.py", line 34, in main
>         long_description = open("README.rst").read(),
>     UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 2016: illegal multibyte sequence
>     ----------------------------------------
> ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m90ti_ox\aliyuncli\
> ```

The python version is no longer maintained, please use the golang version.

**Comment by night556** [comment]
> > win10 上安装时候出现编码问题
> > 执行命令:
> > ```
> > pip install aliyuncli
> > ```
> > 
> > 
> > ```
> > Looking in indexes: https://mirrors.aliyun.com/pypi/simple
> > Collecting aliyuncli
> >   Downloading https://mirrors.aliyun.com/pypi/packages/f2/38/a44b5a5d7a33e258113eb88de865c36f14c4d034d17b57ade7dffadab919/aliyuncli-2.1.5.tar.gz (60kB)
> >      |████████████████████████████████| 61kB 3.8MB/s
> >     ERROR: Complete output from command python setup.py egg_info:
> >     ERROR: Traceback (most recent call last):
> >       File "<string>", line 1, in <module>
> >       File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m90ti_ox\aliyuncli\setup.py", line 54, in <module>
> >         main()
> >       File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m90ti_ox\aliyuncli\setup.py", line 34, in main
> >         long_description = open("README.rst").read(),
> >     UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 2016: illegal multibyte sequence
> >     ----------------------------------------
> > ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-m90ti_ox\aliyuncli\
> > ```
> 
> The python version is no longer maintained, please use the golang version.

It is recommended to use the new version of CLI, and if you have any other questions, please contact us.
Thank you for your attention to Alibaba Cloud CLI Project!
