### ISSUE TITLE
DescribeAvailableResource does not support DestinationResource==InstanceType

### ISSUE THREAD

**Issue by eyalzo** [aliyun/aliyun-cli#187]
* **Command Format**:

* **Execution Command**:
aliyun ecs DescribeAvailableResource --DestinationResource InstanceType --RegionId eu-west-1

* **Output**:

ERROR: SDK.ServerError
ErrorCode: Invalid.Param
Recommend: 
RequestId: 0ED43CB0-10FA-415E-A114-260952189D3C
Message: The input parameter DestinationResource that is mandatory for processing this request is not supplied.

 Version 3.0.16 on Mac, installed with brew

**Comment by night556** [comment]
> * **Command Format**:
> * **Execution Command**:
>   aliyun ecs DescribeAvailableResource --DestinationResource InstanceType --RegionId eu-west-1
> * **Output**:
> 
> ERROR: SDK.ServerError
> ErrorCode: Invalid.Param
> Recommend:
> RequestId: 0ED43CB0-10FA-415E-A114-260952189D3C
> Message: The input parameter DestinationResource that is mandatory for processing this request is not supplied.
> 
> Version 3.0.16 on Mac, installed with brew

Hi, when specifying DestinationResource as InstanceType, you must specify IoOptimized.
![image](https://user-images.githubusercontent.com/41110785/59648636-5a7f2900-91b2-11e9-8981-6294dbf5ccf5.png)
Below is the document URL:
https://www.alibabacloud.com/help/doc-detail/66186.html?spm=a2c5t.10695662.1996646101.searchclickresult.32eaf39dJsUxul

**Comment by night556** [comment]
Please contact us if you have any other questions.
Thank you for your attention to Alibaba Cloud CLI Project!
