### ISSUE TITLE
Suggestion: switch from "dep" to go modules

### ISSUE THREAD

**Issue by drnic** [aliyun/aliyun-cli#197]
Currently the repo uses `dep` + `Gopkg.toml`. Golang now includes a native packaging system "go modules".

One benefit amongst any is that projects using go modules do not need to be installed + developed within `$GOPATH` maze.

References for go modules + how to switch:

* https://blog.golang.org/using-go-modules
* https://blog.golang.org/modules2019
* https://starkandwayne.com/blog/switching-to-go-modules/

**Comment by night556** [comment]
> Currently the repo uses `dep` + `Gopkg.toml`. Golang now includes a native packaging system "go modules".
> 
> One benefit amongst any is that projects using go modules do not need to be installed + developed within `$GOPATH` maze.
> 
> References for go modules + how to switch:
> 
> * https://blog.golang.org/using-go-modules
> * https://blog.golang.org/modules2019
> * https://starkandwayne.com/blog/switching-to-go-modules/

Thank you for your suggestion and the link you provided, we are planning to support go modules.
Thank you for your attention to Alibaba Cloud CLI Project!

**Comment by night556** [comment]
> Currently the repo uses `dep` + `Gopkg.toml`. Golang now includes a native packaging system "go modules".
> 
> One benefit amongst any is that projects using go modules do not need to be installed + developed within `$GOPATH` maze.
> 
> References for go modules + how to switch:
> 
> * https://blog.golang.org/using-go-modules
> * https://blog.golang.org/modules2019
> * https://starkandwayne.com/blog/switching-to-go-modules/

The package manager has been changed to Go Modules in version 3.0.26.
