### ISSUE TITLE
增加最新版本下载别名

### ISSUE THREAD

**Issue by byan** [aliyun/aliyun-cli#204]
* **需求类型**:
增加最新版本下载别名

* **需求描述**:
这样每次下载就不用到主页去看最新版本是什么，然后指定版本下载

* **设计方案**:
建立一个下载地址的符号链接指向最新版本。
比如 `https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz` => 
`https://aliyuncli.alicdn.com/aliyun-cli-linux-3.0.20-amd64.tgz`

**Comment by night556** [comment]
> * **需求类型**:
>   增加最新版本下载别名
> * **需求描述**:
>   这样每次下载就不用到主页去看最新版本是什么，然后指定版本下载
> * **设计方案**:
>   建立一个下载地址的符号链接指向最新版本。
>   比如 `https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz` =>
>   `https://aliyuncli.alicdn.com/aliyun-cli-linux-3.0.20-amd64.tgz`

谢谢你的建议，我们正在增加此种链接。

**Comment by night556** [comment]
> * **需求类型**:
>   增加最新版本下载别名
> * **需求描述**:
>   这样每次下载就不用到主页去看最新版本是什么，然后指定版本下载
> * **设计方案**:
>   建立一个下载地址的符号链接指向最新版本。
>   比如 `https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz` =>
>   `https://aliyuncli.alicdn.com/aliyun-cli-linux-3.0.20-amd64.tgz`

我们已经有了链接指向最新版本：https://aliyuncli.alicdn.com/aliyun-cli-windows-latest-amd64.zip
