### ISSUE TITLE
auto-completion reports error

### ISSUE THREAD

**Issue by casparant** [aliyun/aliyun-cli#206]
* **Command Format**:
./aliyun (Tab)(Tab)

* **Execution Command**:
./aliyun (Tab)(Tab) 

* **Output**:
./aliyun -bash: /tmp/go-build260648301/b001/cli.test: No such file or directory
-bash: /tmp/go-build260648301/b001/cli.test: No such file or directory

I'm using this binary: https://github.com/aliyun/aliyun-cli/releases/download/v3.0.20/aliyun-cli-linux-3.0.20-amd64.tgz

**Comment by night556** [comment]
> * **Command Format**:
>   ./aliyun (Tab)(Tab)
> * **Execution Command**:
>   ./aliyun (Tab)(Tab)
> * **Output**:
>   ./aliyun -bash: /tmp/go-build260648301/b001/cli.test: No such file or directory
>   -bash: /tmp/go-build260648301/b001/cli.test: No such file or directory
> 
> I'm using this binary: https://github.com/aliyun/aliyun-cli/releases/download/v3.0.20/aliyun-cli-linux-3.0.20-amd64.tgz

Hi, we did not reproduce this issue. Please put aliyun file in `/usr/local/bin`, and then run command `aliyun auto-completion`, and try again.

**Comment by casparant** [comment]
re-run `aliyun auto-completion` works, not reproducible from my side, thanks for confirmation. Closing.
