### ISSUE TITLE
ErrorMessage with Chinese Characters

### ISSUE THREAD

**Issue by yagrxu** [aliyun/aliyun-cli#208]
* **Command Format**:

* **Execution Command**:
aliyun iot QueryDevice --ProductKey a1dXZXPCPJy
* **Output**:
{
	"ErrorMessage": "产品不存在。",
	"RequestId": "C1342253-5A58-437D-A77C-A26FE22B8BE6",
	"Success": false,
	"Code": "iot.prod.NotExistedProduct"
}
similar below:
        "ErrorMessage": "入参产品ID没有赋值。",
	"RequestId": "A6FF4B79-CFF5-4555-B988-B148A0BF6263",
	"Success": false,
	"Code": "iot.prod.NullProductKey"

![image](https://user-images.githubusercontent.com/11458143/62324303-7ceeac80-b4a9-11e9-9904-3c2af2680c4f.png)

**Comment by night556** [comment]
> * **Command Format**:
> * **Execution Command**:
>   aliyun iot QueryDevice --ProductKey a1dXZXPCPJy
> * **Output**:
>   {
>   "ErrorMessage": "产品不存在。",
>   "RequestId": "C1342253-5A58-437D-A77C-A26FE22B8BE6",
>   "Success": false,
>   "Code": "iot.prod.NotExistedProduct"
>   }
>   similar below:
>   "ErrorMessage": "入参产品ID没有赋值。",
>   "RequestId": "A6FF4B79-CFF5-4555-B988-B148A0BF6263",
>   "Success": false,
>   "Code": "iot.prod.NullProductKey"
> 
> ![image](https://user-images.githubusercontent.com/11458143/62324303-7ceeac80-b4a9-11e9-9904-3c2af2680c4f.png)

Hi, the CLI just calls the interface, your error is returned by the server, please contact the product staff
