### ISSUE TITLE
Links for API are not correct

### ISSUE THREAD

**Issue by yagrxu** [aliyun/aliyun-cli#209]
* **Command Format**:
* **Execution Command**:
aliyun iot QueryDeviceProp help
aliyun iot QueryProduct help
* **Output**:
Alibaba Cloud Command Line Interface Version 3.0.22

Product: Iot (Alibaba Cloud IoT)
Link:    https://help.aliyun.com/api/iot/QueryDeviceProp.html
also this 
Alibaba Cloud Command Line Interface Version 3.0.22

Product: Iot (Alibaba Cloud IoT)
Link:    https://help.aliyun.com/api/iot/QueryProduct.html

Links are not valid

**Comment by night556** [comment]
> * **Command Format**:
> * **Execution Command**:
>   aliyun iot QueryDeviceProp help
>   aliyun iot QueryProduct help
> * **Output**:
>   Alibaba Cloud Command Line Interface Version 3.0.22
> 
> Product: Iot (Alibaba Cloud IoT)
> Link: https://help.aliyun.com/api/iot/QueryDeviceProp.html
> also this
> Alibaba Cloud Command Line Interface Version 3.0.22
> 
> Product: Iot (Alibaba Cloud IoT)
> Link: https://help.aliyun.com/api/iot/QueryProduct.html
> 
> Links are not valid

This link is automatically generated by the CLI. If an error occurs, please contact the product staff.

**Comment by night556** [comment]
> * **Command Format**:
> * **Execution Command**:
>   aliyun iot QueryDeviceProp help
>   aliyun iot QueryProduct help
> * **Output**:
>   Alibaba Cloud Command Line Interface Version 3.0.22
> 
> Product: Iot (Alibaba Cloud IoT)
> Link: https://help.aliyun.com/api/iot/QueryDeviceProp.html
> also this
> Alibaba Cloud Command Line Interface Version 3.0.22
> 
> Product: Iot (Alibaba Cloud IoT)
> Link: https://help.aliyun.com/api/iot/QueryProduct.html
> 
> Links are not valid

Thank you for your question, if there is no further feedback on the issue, the issue will be closed on September 16.
