### ISSUE TITLE
No need to always require AccessKey/AccessSecret/RegionID

### ISSUE THREAD

**Issue by xning** [aliyun/aliyun-cli#21]
For example, anybody could browse ECS regions' info by a browser, hence it is unnecessary to require  AccessKey/AccessSecret/RegionID when running 'aliyuncli ecs DescribeRegions'.

**Comment by xning** [comment]
If we always require these parameters, the command line cannot work before configuring it. But to collect AccessKey/AccessSecret/RegionID infs and to the configure the command line is not easy for these newbies and bore for these impatient users who just want to get some simple infos.

**Comment by JacksonTian** [comment]
You can use `aliyun configure` to set the default AK/Region.
