### ISSUE TITLE
执行命令崩溃

### ISSUE THREAD

**Issue by pc10201** [aliyun/aliyun-cli#210]
执行命令崩溃

* **Command Format**:

最新版cli

* **Execution Command**:

./aliyun aegis DescribeGroupedVul --pager

* **Output**:

panic: interface conversion: interface {} is nil, not float64

goroutine 1 [running]:
github.com/aliyun/aliyun-cli/openapi.(*Pager).FeedResponse(0xc4202d02d0, 0xc42009b500, 0x13fa, 0x0, 0x0)
	/home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/pager.go:158 +0x77b
github.com/aliyun/aliyun-cli/openapi.(*Pager).CallWith(0xc4202d02d0, 0xf47d20, 0xc4205ba250, 0x2, 0x2, 0xc420598590, 0x8)
	/home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/pager.go:90 +0x94
github.com/aliyun/aliyun-cli/openapi.(*Commando).invokeWithHelper(0xc42032a480, 0xf47d20, 0xc4205ba250, 0xe33760, 0x6, 0xc420598590, 0x8, 0x0)
	/home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:185 +0xcc
github.com/aliyun/aliyun-cli/openapi.(*Commando).processInvoke(0xc42032a480, 0xc420267380, 0x7ffefc745824, 0x5, 0x7ffefc74582a, 0x12, 0x0, 0x0, 0xc420262c30, 0xc420262c60)
	/home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:135 +0x1ca
github.com/aliyun/aliyun-cli/openapi.(*Commando).main(0xc42032a480, 0xc420267380, 0xc42049e9a0, 0x2, 0x2, 0x55, 0xc4200321f0)
	/home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:103 +0x39f
github.com/aliyun/aliyun-cli/openapi.(*Commando).(github.com/aliyun/aliyun-cli/openapi.main)-fm(0xc420267380, 0xc42049e9a0, 0x2, 0x2, 0x2, 0xc42049e9a0)
	/home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:49 +0x52
github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc420322000, 0xc420267380, 0xc42001e0d0, 0x3, 0x3, 0x18, 0x19)
	/home/mrx/go/src/github.com/aliyun/aliyun-cli/cli/command.go:237 +0x690
github.com/aliyun/aliyun-cli/cli.(*Command).Execute(0xc420322000, 0xc420267380, 0xc42001e0d0, 0x3, 0x3)
	/home/mrx/go/src/github.com/aliyun/aliyun-cli/cli/command.go:85 +0x5d
main.main()
	/home/mrx/go/src/github.com/aliyun/aliyun-cli/main/main.go:89 +0x7e4

**Comment by night556** [comment]
> 执行命令崩溃
> 
> * **Command Format**:
> 
> 最新版cli
> 
> * **Execution Command**:
> 
> ./aliyun aegis DescribeGroupedVul --pager
> 
> * **Output**:
> 
> panic: interface conversion: interface {} is nil, not float64
> 
> goroutine 1 [running]:
> github.com/aliyun/aliyun-cli/openapi.(*Pager).FeedResponse(0xc4202d02d0, 0xc42009b500, 0x13fa, 0x0, 0x0)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/pager.go:158 +0x77b
> github.com/aliyun/aliyun-cli/openapi.(*Pager).CallWith(0xc4202d02d0, 0xf47d20, 0xc4205ba250, 0x2, 0x2, 0xc420598590, 0x8)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/pager.go:90 +0x94
> github.com/aliyun/aliyun-cli/openapi.(*Commando).invokeWithHelper(0xc42032a480, 0xf47d20, 0xc4205ba250, 0xe33760, 0x6, 0xc420598590, 0x8, 0x0)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:185 +0xcc
> github.com/aliyun/aliyun-cli/openapi.(*Commando).processInvoke(0xc42032a480, 0xc420267380, 0x7ffefc745824, 0x5, 0x7ffefc74582a, 0x12, 0x0, 0x0, 0xc420262c30, 0xc420262c60)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:135 +0x1ca
> github.com/aliyun/aliyun-cli/openapi.(*Commando).main(0xc42032a480, 0xc420267380, 0xc42049e9a0, 0x2, 0x2, 0x55, 0xc4200321f0)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:103 +0x39f
> github.com/aliyun/aliyun-cli/openapi.(*Commando).(github.com/aliyun/aliyun-cli/openapi.main)-fm(0xc420267380, 0xc42049e9a0, 0x2, 0x2, 0x2, 0xc42049e9a0)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:49 +0x52
> github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc420322000, 0xc420267380, 0xc42001e0d0, 0x3, 0x3, 0x18, 0x19)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/cli/command.go:237 +0x690
> github.com/aliyun/aliyun-cli/cli.(*Command).Execute(0xc420322000, 0xc420267380, 0xc42001e0d0, 0x3, 0x3)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/cli/command.go:85 +0x5d
> main.main()
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/main/main.
该错误是由于未指定`PageNumber`子字段造成的，请使用3.0.23以上版本执行以下命令
```shell
aliyun aegis DescribeGroupedVul --pager path=GroupedVulItems PageNumber=CurrentPage
```
关于`--pager`选项使用方法，请参考官网文档：https://help.aliyun.com/document_detail/122112.html?spm=a2c4g.11186623.6.560.20181b18vZvwhk

**Comment by night556** [comment]
> 执行命令崩溃
> 
> * **Command Format**:
> 
> 最新版cli
> 
> * **Execution Command**:
> 
> ./aliyun aegis DescribeGroupedVul --pager
> 
> * **Output**:
> 
> panic: interface conversion: interface {} is nil, not float64
> 
> goroutine 1 [running]:
> github.com/aliyun/aliyun-cli/openapi.(*Pager).FeedResponse(0xc4202d02d0, 0xc42009b500, 0x13fa, 0x0, 0x0)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/pager.go:158 +0x77b
> github.com/aliyun/aliyun-cli/openapi.(*Pager).CallWith(0xc4202d02d0, 0xf47d20, 0xc4205ba250, 0x2, 0x2, 0xc420598590, 0x8)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/pager.go:90 +0x94
> github.com/aliyun/aliyun-cli/openapi.(*Commando).invokeWithHelper(0xc42032a480, 0xf47d20, 0xc4205ba250, 0xe33760, 0x6, 0xc420598590, 0x8, 0x0)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:185 +0xcc
> github.com/aliyun/aliyun-cli/openapi.(*Commando).processInvoke(0xc42032a480, 0xc420267380, 0x7ffefc745824, 0x5, 0x7ffefc74582a, 0x12, 0x0, 0x0, 0xc420262c30, 0xc420262c60)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:135 +0x1ca
> github.com/aliyun/aliyun-cli/openapi.(*Commando).main(0xc42032a480, 0xc420267380, 0xc42049e9a0, 0x2, 0x2, 0x55, 0xc4200321f0)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:103 +0x39f
> github.com/aliyun/aliyun-cli/openapi.(*Commando).(github.com/aliyun/aliyun-cli/openapi.main)-fm(0xc420267380, 0xc42049e9a0, 0x2, 0x2, 0x2, 0xc42049e9a0)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/openapi/commando.go:49 +0x52
> github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc420322000, 0xc420267380, 0xc42001e0d0, 0x3, 0x3, 0x18, 0x19)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/cli/command.go:237 +0x690
> github.com/aliyun/aliyun-cli/cli.(*Command).Execute(0xc420322000, 0xc420267380, 0xc42001e0d0, 0x3, 0x3)
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/cli/command.go:85 +0x5d
> main.main()
> /home/mrx/go/src/github.com/aliyun/aliyun-cli/main/main.go:89 +0x7e4

如果没有后续消息，我们将在9月16日前关闭此issue
