### ISSUE TITLE
aliyun eci CreateContainerGroup 参数存在重复

### ISSUE THREAD

**Issue by edensky01** [aliyun/aliyun-cli#216]
* **命令格式**:

* **执行命令**:
  `aliyun eci CreateContainerGroup --help`

* **输出**:

  ```shell
  阿里云CLI命令行工具 3.0.25
  
  Product: Eci (Elastic Container Instances)
  Link:    https://help.aliyun.com/api/eci/CreateContainerGroup.html
  
  Parameters:
    --Container.n.Image                                      String     Required
    --Container.n.Name                                       String     Required 
    --Container.n.Arg.n                                      RepeatList Optional
    --Container.n.Command.n                                  RepeatList Optional
    --Container.n.Cpu                                        Float      Optional
    --EnvironmentVar.n.FieldRef.FieldPath                    String     Optional
    --EnvironmentVar.n.Key                                   String     Optional
    --EnvironmentVar.n.Value                                 String     Optional
    --Container.n.Gpu                                        Integer    Optional
    --Container.n.ImagePullPolicy                            String     Optional
    --Container.n.LivenessProbe.Exec.Command.n               RepeatList Optional
    --Container.n.LivenessProbe.FailureThreshold             Integer    Optional
    --Container.n.LivenessProbe.HttpGet.Path                 String     Optional
    --Container.n.LivenessProbe.HttpGet.Port                 Integer    Optional
    --Container.n.LivenessProbe.HttpGet.Scheme               String     Optional
    --Container.n.LivenessProbe.InitialDelaySeconds          Integer    Optional
    --Container.n.LivenessProbe.PeriodSeconds                Integer    Optional
    --Container.n.LivenessProbe.SuccessThreshold             Integer    Optional 
    --Container.n.LivenessProbe.TcpSocket.Port               Integer    Optional
    --Container.n.LivenessProbe.TimeoutSeconds               Integer    Optional
    --Container.n.Memory                                     Float      Optional
    --Port.n.Port                                            Integer    Optional
    --Port.n.Protocol                                        String     Optional
    --Container.n.ReadinessProbe.Exec.Command.n              RepeatList Optional
    --Container.n.ReadinessProbe.FailureThreshold            Integer    Optional 
    --Container.n.ReadinessProbe.HttpGet.Path                String     Optional
    --Container.n.ReadinessProbe.HttpGet.Port                Integer    Optional
    --Container.n.ReadinessProbe.HttpGet.Scheme              String     Optional
    --Container.n.ReadinessProbe.InitialDelaySeconds         Integer    Optional
    --Container.n.ReadinessProbe.PeriodSeconds               Integer    Optional
    --Container.n.ReadinessProbe.SuccessThreshold            Integer    Optional
    --Container.n.ReadinessProbe.TcpSocket.Port              Integer    Optional
    --Container.n.ReadinessProbe.TimeoutSeconds              Integer    Optional
    --Container.n.SecurityContext.Capability.Add.n           RepeatList Optional
    --Container.n.SecurityContext.ReadOnlyRootFilesystem     Boolean    Optional
    --Container.n.SecurityContext.RunAsUser                  Long       Optional
    --Container.n.Stdin                                      Boolean    Optional 
    --Container.n.StdinOnce                                  Boolean    Optional
    --Container.n.Tty                                        Boolean    Optional
    --VolumeMount.n.MountPath                                String     Optional 
    --VolumeMount.n.Name                                     String     Optional
    --VolumeMount.n.ReadOnly                                 Boolean    Optional
    --VolumeMount.n.SubPath                                  String     Optional
    --Container.n.WorkingDir                                 String     Optional
    --ContainerGroupName                                     String     Required
    --RegionId                                               String     Required
    --SecurityGroupId                                        String     Required
    --VSwitchId                                              String     Required
    --Arn.n.AssumeRoleFor                                    String     Optional
    --Arn.n.RoleArn                                          String     Optional
    --Arn.n.RoleType                                         String     Optional
    --ClientToken                                            String     Optional 
    --Cpu                                                    Float      Optional
    --DnsConfig.NameServer.n                                 RepeatList Optional
    --DnsConfig.Option.n.Name                                String     Optional
    --DnsConfig.Option.n.Value                               String     Optional
    --DnsConfig.Search.n                                     RepeatList Optional
    --DnsPolicy                                              String     Optional
    --EipInstanceId                                          String     Optional
    --HostAliase.n.Hostname.n                                RepeatList Optional
    --HostAliase.n.Ip                                        String     Optional
    --ImageRegistryCredential.n.Password                     String     Optional
    --ImageRegistryCredential.n.Server                       String     Optional
    --ImageRegistryCredential.n.UserName                     String     Optional
    --ImageSnapshotId                                        String     Optional
    --InitContainer.n.Arg.n                                  RepeatList Optional 
    --InitContainer.n.Command.n                              RepeatList Optional 
    --InitContainer.n.Cpu                                    Float      Optional 
    (重复)--EnvironmentVar.n.FieldRef.FieldPath                    String     Optional
    (重复)--EnvironmentVar.n.Key                                   String     Optional
    (重复)--EnvironmentVar.n.Value                                 String     Optional 
    --InitContainer.n.Gpu                                    Integer    Optional
    --InitContainer.n.Image                                  String     Optional
    --InitContainer.n.ImagePullPolicy                        String     Optional
    --InitContainer.n.Memory                                 Float      Optional
    --InitContainer.n.Name                                   String     Optional
    (重复)--Port.n.Port                                            Integer    Optional
    (重复)--Port.n.Protocol                                        String     Optional
    --InitContainer.n.SecurityContext.Capability.Add.n       RepeatList Optional
    --InitContainer.n.SecurityContext.ReadOnlyRootFilesystem Boolean    Optional
    --InitContainer.n.Command.n                              RepeatList Optional
    --InitContainer.n.SecurityContext.RunAsUser              Long       Optional
    (重复)--VolumeMount.n.MountPath                                String     Optional
    (重复)--VolumeMount.n.Name                                     String     Optional
    (重复)--VolumeMount.n.ReadOnly                                 Boolean    Optional
    (重复)--VolumeMount.n.SubPath                                  String     Optional
    --InitContainer.n.WorkingDir                             String     Optional
    --InstanceType                                           String     Optional
    --Memory                                                 Float      Optional
    --RamRoleName                                            String     Optional
    --ResourceGroupId                                        String     Optional
    --RestartPolicy                                          String     Optional
    --SecurityContext.Sysctl.n.Name                          String     Optional
    --SecurityContext.Sysctl.n.Value                         String     Optional
    --SlsEnable                                              Boolean    Optional
    --Tag.n.Key                                              String     Optional
    --Tag.n.Value                                            String     Optional
    --ConfigFileVolume.ConfigFileToPath.n.Content            String     Optional
    --ConfigFileVolume.ConfigFileToPath.n.Mode               Integer    Optional
    --ConfigFileVolume.ConfigFileToPath.n.Path               String     Optional
    --Volume.n.ConfigFileVolume.DefaultModel                 Integer    Optional
    --Volume.n.DiskVolume.DiskId                             String     Optional
    --Volume.n.DiskVolume.FsType                             String     Optional
    --Volume.n.EmptyDirVolume.Medium                         String     Optional
    --Volume.n.NFSVolume.Path                                String     Optional
    --Volume.n.NFSVolume.ReadOnly                            Boolean    Optional
    --Volume.n.NFSVolume.Server                              String     Optional
    --Volume.n.Name                                          String     Optional
    --Volume.n.Type                                          String     Optional
    --ZoneId                                                 String     Optional
  ```

**Comment by night556** [comment]
> * **命令格式**:
> * **执行命令**:
>   `aliyun eci CreateContainerGroup --help`
> * **输出**:
>   ```shell
>   阿里云CLI命令行工具 3.0.25
>   
>   Product: Eci (Elastic Container Instances)
>   Link:    https://help.aliyun.com/api/eci/CreateContainerGroup.html
>   
>   Parameters:
>     --Container.n.Image                                      String     Required
>     --Container.n.Name                                       String     Required 
>     --Container.n.Arg.n                                      RepeatList Optional
>     --Container.n.Command.n                                  RepeatList Optional
>     --Container.n.Cpu                                        Float      Optional
>     --EnvironmentVar.n.FieldRef.FieldPath                    String     Optional
>     --EnvironmentVar.n.Key                                   String     Optional
>     --EnvironmentVar.n.Value                                 String     Optional
>     --Container.n.Gpu                                        Integer    Optional
>     --Container.n.ImagePullPolicy                            String     Optional
>     --Container.n.LivenessProbe.Exec.Command.n               RepeatList Optional
>     --Container.n.LivenessProbe.FailureThreshold             Integer    Optional
>     --Container.n.LivenessProbe.HttpGet.Path                 String     Optional
>     --Container.n.LivenessProbe.HttpGet.Port                 Integer    Optional
>     --Container.n.LivenessProbe.HttpGet.Scheme               String     Optional
>     --Container.n.LivenessProbe.InitialDelaySeconds          Integer    Optional
>     --Container.n.LivenessProbe.PeriodSeconds                Integer    Optional
>     --Container.n.LivenessProbe.SuccessThreshold             Integer    Optional 
>     --Container.n.LivenessProbe.TcpSocket.Port               Integer    Optional
>     --Container.n.LivenessProbe.TimeoutSeconds               Integer    Optional
>     --Container.n.Memory                                     Float      Optional
>     --Port.n.Port                                            Integer    Optional
>     --Port.n.Protocol                                        String     Optional
>     --Container.n.ReadinessProbe.Exec.Command.n              RepeatList Optional
>     --Container.n.ReadinessProbe.FailureThreshold            Integer    Optional 
>     --Container.n.ReadinessProbe.HttpGet.Path                String     Optional
>     --Container.n.ReadinessProbe.HttpGet.Port                Integer    Optional
>     --Container.n.ReadinessProbe.HttpGet.Scheme              String     Optional
>     --Container.n.ReadinessProbe.InitialDelaySeconds         Integer    Optional
>     --Container.n.ReadinessProbe.PeriodSeconds               Integer    Optional
>     --Container.n.ReadinessProbe.SuccessThreshold            Integer    Optional
>     --Container.n.ReadinessProbe.TcpSocket.Port              Integer    Optional
>     --Container.n.ReadinessProbe.TimeoutSeconds              Integer    Optional
>     --Container.n.SecurityContext.Capability.Add.n           RepeatList Optional
>     --Container.n.SecurityContext.ReadOnlyRootFilesystem     Boolean    Optional
>     --Container.n.SecurityContext.RunAsUser                  Long       Optional
>     --Container.n.Stdin                                      Boolean    Optional 
>     --Container.n.StdinOnce                                  Boolean    Optional
>     --Container.n.Tty                                        Boolean    Optional
>     --VolumeMount.n.MountPath                                String     Optional 
>     --VolumeMount.n.Name                                     String     Optional
>     --VolumeMount.n.ReadOnly                                 Boolean    Optional
>     --VolumeMount.n.SubPath                                  String     Optional
>     --Container.n.WorkingDir                                 String     Optional
>     --ContainerGroupName                                     String     Required
>     --RegionId                                               String     Required
>     --SecurityGroupId                                        String     Required
>     --VSwitchId                                              String     Required
>     --Arn.n.AssumeRoleFor                                    String     Optional
>     --Arn.n.RoleArn                                          String     Optional
>     --Arn.n.RoleType                                         String     Optional
>     --ClientToken                                            String     Optional 
>     --Cpu                                                    Float      Optional
>     --DnsConfig.NameServer.n                                 RepeatList Optional
>     --DnsConfig.Option.n.Name                                String     Optional
>     --DnsConfig.Option.n.Value                               String     Optional
>     --DnsConfig.Search.n                                     RepeatList Optional
>     --DnsPolicy                                              String     Optional
>     --EipInstanceId                                          String     Optional
>     --HostAliase.n.Hostname.n                                RepeatList Optional
>     --HostAliase.n.Ip                                        String     Optional
>     --ImageRegistryCredential.n.Password                     String     Optional
>     --ImageRegistryCredential.n.Server                       String     Optional
>     --ImageRegistryCredential.n.UserName                     String     Optional
>     --ImageSnapshotId                                        String     Optional
>     --InitContainer.n.Arg.n                                  RepeatList Optional 
>     --InitContainer.n.Command.n                              RepeatList Optional 
>     --InitContainer.n.Cpu                                    Float      Optional 
>     (重复)--EnvironmentVar.n.FieldRef.FieldPath                    String     Optional
>     (重复)--EnvironmentVar.n.Key                                   String     Optional
>     (重复)--EnvironmentVar.n.Value                                 String     Optional 
>     --InitContainer.n.Gpu                                    Integer    Optional
>     --InitContainer.n.Image                                  String     Optional
>     --InitContainer.n.ImagePullPolicy                        String     Optional
>     --InitContainer.n.Memory                                 Float      Optional
>     --InitContainer.n.Name                                   String     Optional
>     (重复)--Port.n.Port                                            Integer    Optional
>     (重复)--Port.n.Protocol                                        String     Optional
>     --InitContainer.n.SecurityContext.Capability.Add.n       RepeatList Optional
>     --InitContainer.n.SecurityContext.ReadOnlyRootFilesystem Boolean    Optional
>     --InitContainer.n.Command.n                              RepeatList Optional
>     --InitContainer.n.SecurityContext.RunAsUser              Long       Optional
>     (重复)--VolumeMount.n.MountPath                                String     Optional
>     (重复)--VolumeMount.n.Name                                     String     Optional
>     (重复)--VolumeMount.n.ReadOnly                                 Boolean    Optional
>     (重复)--VolumeMount.n.SubPath                                  String     Optional
>     --InitContainer.n.WorkingDir                             String     Optional
>     --InstanceType                                           String     Optional
>     --Memory                                                 Float      Optional
>     --RamRoleName                                            String     Optional
>     --ResourceGroupId                                        String     Optional
>     --RestartPolicy                                          String     Optional
>     --SecurityContext.Sysctl.n.Name                          String     Optional
>     --SecurityContext.Sysctl.n.Value                         String     Optional
>     --SlsEnable                                              Boolean    Optional
>     --Tag.n.Key                                              String     Optional
>     --Tag.n.Value                                            String     Optional
>     --ConfigFileVolume.ConfigFileToPath.n.Content            String     Optional
>     --ConfigFileVolume.ConfigFileToPath.n.Mode               Integer    Optional
>     --ConfigFileVolume.ConfigFileToPath.n.Path               String     Optional
>     --Volume.n.ConfigFileVolume.DefaultModel                 Integer    Optional
>     --Volume.n.DiskVolume.DiskId                             String     Optional
>     --Volume.n.DiskVolume.FsType                             String     Optional
>     --Volume.n.EmptyDirVolume.Medium                         String     Optional
>     --Volume.n.NFSVolume.Path                                String     Optional
>     --Volume.n.NFSVolume.ReadOnly                            Boolean    Optional
>     --Volume.n.NFSVolume.Server                              String     Optional
>     --Volume.n.Name                                          String     Optional
>     --Volume.n.Type                                          String     Optional
>     --ZoneId                                                 String     Optional
>   ```

感谢提交关于该问题的issue，该问题已经在3.0.26版本中解决：https://github.com/aliyun/aliyun-cli/releases/tag/v3.0.26
