### ISSUE TITLE
aliyuncli doesn't work without default profile

### ISSUE THREAD

**Issue by t-moriyama** [aliyun/aliyun-cli#22]
if ~/.aliyuncli/configure is empty, aliyuncli was failed.
I'd like you to aliyuncli work well without default profile.

- On failure:
```
echo "" > ~/.aliyuncli/configure

aliyuncli rds DescribeRegions \
 --AccessKeyId *** \
 --AccessKeySecret *** \
 --RegionId "cn-hangzhou"

accesskeyid/accesskeysecret/regionId is absence
```

- On success:
```
vi ~/.aliyuncli/configure
--
[default]
aliyun_access_key_secret =
aliyun_access_key_id =
--

aliyuncli rds DescribeRegions \
 --AccessKeyId *** \
 --AccessKeySecret *** \
 --RegionId "cn-hangzhou"

{
    "Regions": {
        "RDSRegion": [
            {
                "RegionId": "cn-qingdao", 
                "ZoneId": "cn-qingdao-b"
            }, 
...
```

- Environment:
```
cat /etc/redhat-release 
CentOS release 6.5 (Final)

python --version
Python 2.6.6

pip list | grep aliyun
aliyun-python-sdk-core (2.1.2)
aliyun-python-sdk-ecs (2.1.1)
aliyun-python-sdk-rds (2.0.5)
aliyuncli (2.1.3)
```

**Comment by night556** [comment]
> if ~/.aliyuncli/configure is empty, aliyuncli was failed.
> I'd like you to aliyuncli work well without default profile.
> 
> * On failure:
> 
> ```
> echo "" > ~/.aliyuncli/configure
> 
> aliyuncli rds DescribeRegions \
>  --AccessKeyId *** \
>  --AccessKeySecret *** \
>  --RegionId "cn-hangzhou"
> 
> accesskeyid/accesskeysecret/regionId is absence
> ```
> * On success:
> 
> ```
> vi ~/.aliyuncli/configure
> --
> [default]
> aliyun_access_key_secret =
> aliyun_access_key_id =
> --
> 
> aliyuncli rds DescribeRegions \
>  --AccessKeyId *** \
>  --AccessKeySecret *** \
>  --RegionId "cn-hangzhou"
> 
> {
>     "Regions": {
>         "RDSRegion": [
>             {
>                 "RegionId": "cn-qingdao", 
>                 "ZoneId": "cn-qingdao-b"
>             }, 
> ...
> ```
> * Environment:
> 
> ```
> cat /etc/redhat-release 
> CentOS release 6.5 (Final)
> 
> python --version
> Python 2.6.6
> 
> pip list | grep aliyun
> aliyun-python-sdk-core (2.1.2)
> aliyun-python-sdk-ecs (2.1.1)
> aliyun-python-sdk-rds (2.0.5)
> aliyuncli (2.1.3)
> ```

The Python version of the CLI has stopped maintenance，you can got the new release version of CLI which reconfiguration by Golang and try it again. 
Thank you for your attention to AliCloud CLI Project！
