### ISSUE TITLE
aliyuncli 有时从 /root/.aliyun/config.json 读取配置 有时候从 /.aliyun/config.json 读取配置

### ISSUE THREAD

**Issue by hellowillwan** [aliyun/aliyun-cli#222]
aliyuncli 有时从 /root/.aliyun/config.json 读取配置 有时候从 /.aliyun/config.json 读取配置，不能从一个固定的路径读取配置？

登录后，在bash 交互式执行，/usr/local/sbin/aliyun 会从 /root/.aliyun/config.json 读取配置；
不登录，脚本方式执行，/usr/local/sbin/aliyun 会从 /.aliyun/config.json 读取配置；

下面是 strace 信息：

* **执行命令**:
/usr/bin/strace /usr/local/sbin/aliyun cdn RefreshObjectCaches --ObjectPath mydomain.com/ --ObjectType Directory
* **输出**:
read(3, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 4096
close(3)                                = 0
munmap(0x7f6cbb0f2000, 4096)            = 0
newfstatat(AT_FDCWD, "/root/.aliyun", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0 
newfstatat(AT_FDCWD, "/root/.aliyun/config.json", {st_mode=S_IFREG|0600, st_size=529, ...}, 0) = 0 
openat(AT_FDCWD, "/root/.aliyun/config.json", O_RDONLY|O_CLOEXEC) = 3 
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3095781288, u64=140104928976808}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 3, {0, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
fstat(3, {st_mode=S_IFREG|0600, st_size=529, ...}) = 0 
read(3, "{\n\t\"current\": \"default\",\n\t\"profi"..., 1041) = 529 
read(3, "", 512)                        = 0
close(3)                                = 0

* **执行命令**:
/usr/bin/strace /usr/local/sbin/aliyun cdn RefreshObjectCaches --ObjectPath mydomain.com/ --ObjectType Directory
* **输出**:
...
read(3, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 4096
close(3)                                = 0
munmap(0x7f2660883000, 4096)            = 0
newfstatat(AT_FDCWD, "/.aliyun", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/.aliyun/config.json", {st_mode=S_IFREG|0600, st_size=529, ...}, 0) = 0
openat(AT_FDCWD, "/.aliyun/config.json", O_RDONLY|O_CLOEXEC) = 3
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1566498728, u64=139802751983528}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 3, {0, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
fstat(3, {st_mode=S_IFREG|0600, st_size=529, ...}) = 0
read(3, "{\n\t\"current\": \"default\",\n\t\"profi"..., 1041) = 529
read(3, "", 512)                        = 0
close(3)                                = 0
mmap(0xc420300000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc420300000
mmap(0xc41ffe0000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc41ffe0000
clock_gettime(CLOCK_MONOTONIC, {780965, 190749557}) = 0
mmap(0xc420400000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc420400000
mmap(0xc41ffd8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc41ffd8000
mmap(0xc000001000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000001000
clock_gettime(CLOCK_MONOTONIC, {780965, 197989046}) = 0
newfstatat(AT_FDCWD, "/.aliyun", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/.aliyun/config.json", {st_mode=S_IFREG|0600, st_size=529, ...}, 0) = 0
openat(AT_FDCWD, "/.aliyun/config.json", O_RDONLY|O_CLOEXEC) = 3
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1566498728, u64=139802751983528}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 3, {0, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
fstat(3, {st_mode=S_IFREG|0600, st_size=529, ...}) = 0
read(3, "{\n\t\"current\": \"default\",\n\t\"profi"..., 1041) = 529
read(3, "", 512)                        = 0
close(3)
...

**Comment by night556** [comment]
> aliyuncli 有时从 /root/.aliyun/config.json 读取配置 有时候从 /.aliyun/config.json 读取配置，不能从一个固定的路径读取配置？
> 
> 登录后，在bash 交互式执行，/usr/local/sbin/aliyun 会从 /root/.aliyun/config.json 读取配置；
> 不登录，脚本方式执行，/usr/local/sbin/aliyun 会从 /.aliyun/config.json 读取配置；
> 
> 下面是 strace 信息：
> 
> * **执行命令**:
>   /usr/bin/strace /usr/local/sbin/aliyun cdn RefreshObjectCaches --ObjectPath mydomain.com/ --ObjectType Directory
> * **输出**:
>   read(3, "root❌0:0:root:/root:/bin/bash\n"..., 4096) = 4096
>   close(3)                                = 0
>   munmap(0x7f6cbb0f2000, 4096)            = 0
>   newfstatat(AT_FDCWD, "/root/.aliyun", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
>   newfstatat(AT_FDCWD, "/root/.aliyun/config.json", {st_mode=S_IFREG|0600, st_size=529, ...}, 0) = 0
>   openat(AT_FDCWD, "/root/.aliyun/config.json", O_RDONLY|O_CLOEXEC) = 3
>   epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3095781288, u64=140104928976808}}) = -1 EPERM (Operation not permitted)
>   epoll_ctl(4, EPOLL_CTL_DEL, 3, {0, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
>   fstat(3, {st_mode=S_IFREG|0600, st_size=529, ...}) = 0
>   read(3, "{\n\t"current": "default",\n\t"profi"..., 1041) = 529
>   read(3, "", 512)                        = 0
>   close(3)                                = 0
> * **执行命令**:
>   /usr/bin/strace /usr/local/sbin/aliyun cdn RefreshObjectCaches --ObjectPath mydomain.com/ --ObjectType Directory
> * **输出**:
>   ...
>   read(3, "root❌0:0:root:/root:/bin/bash\n"..., 4096) = 4096
>   close(3)                                = 0
>   munmap(0x7f2660883000, 4096)            = 0
>   newfstatat(AT_FDCWD, "/.aliyun", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
>   newfstatat(AT_FDCWD, "/.aliyun/config.json", {st_mode=S_IFREG|0600, st_size=529, ...}, 0) = 0
>   openat(AT_FDCWD, "/.aliyun/config.json", O_RDONLY|O_CLOEXEC) = 3
>   epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1566498728, u64=139802751983528}}) = -1 EPERM (Operation not permitted)
>   epoll_ctl(4, EPOLL_CTL_DEL, 3, {0, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
>   fstat(3, {st_mode=S_IFREG|0600, st_size=529, ...}) = 0
>   read(3, "{\n\t"current": "default",\n\t"profi"..., 1041) = 529
>   read(3, "", 512)                        = 0
>   close(3)                                = 0
>   mmap(0xc420300000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc420300000
>   mmap(0xc41ffe0000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc41ffe0000
>   clock_gettime(CLOCK_MONOTONIC, {780965, 190749557}) = 0
>   mmap(0xc420400000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc420400000
>   mmap(0xc41ffd8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc41ffd8000
>   mmap(0xc000001000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000001000
>   clock_gettime(CLOCK_MONOTONIC, {780965, 197989046}) = 0
>   newfstatat(AT_FDCWD, "/.aliyun", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
>   newfstatat(AT_FDCWD, "/.aliyun/config.json", {st_mode=S_IFREG|0600, st_size=529, ...}, 0) = 0
>   openat(AT_FDCWD, "/.aliyun/config.json", O_RDONLY|O_CLOEXEC) = 3
>   epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1566498728, u64=139802751983528}}) = -1 EPERM (Operation not permitted)
>   epoll_ctl(4, EPOLL_CTL_DEL, 3, {0, {u32=0, u64=0}}) = -1 EPERM (Operation not permitted)
>   fstat(3, {st_mode=S_IFREG|0600, st_size=529, ...}) = 0
>   read(3, "{\n\t"current": "default",\n\t"profi"..., 1041) = 529
>   read(3, "", 512)                        = 0
>   close(3)
>   ...

对于linux和mac系统，配置文件路径为$HOME/.aliyun/config.json，出现该问题的原因是你的HOME环境变量有时为空，有时为/root。
请保证在执行aliyun命令是HOME环境变量的正确性。
如果还有其他问题，请联系我们。

**Comment by hellowillwan** [comment]
谢谢，的确是 $HOME 为空

**Comment by easybest** [comment]
$HOME 为空是正常的。在很多场景中，kubernetes的容器中就是以一个不存在的用户执行的
