### ISSUE TITLE
aliyun configure set --profile stsTokenProfile  设置时access_key_secret值没有根据参数设置

### ISSUE THREAD

**Issue by dongtaoyu** [aliyun/aliyun-cli#223]
* **命令格式**:
 aliyun --version
Alibaba Cloud Command Line Interface Version 3.0.27

* **执行命令**:
aliyun configure set --profile stsTokenProfile --mode StsToken --region cn-chengdu --access-key-id NHRqGaKU7E2 **--access-key-secret J5XfiEt**k --sts-token wF1q6Ft5B2yfSjIr4vnOv

* **输出**:
aliyun configure get --profile stsTokenProfile
{
        "name": "stsTokenProfile",
        "mode": "StsToken",
        "access_key_id": "NHRqGaKU7E2",
        **"access_key_secret": "NHRqGaKU7E2"**,
        "sts_token": "wF1q6Ft5B2yfSjIr4vnOv",
        "ram_role_name": "",
        "ram_role_arn": "",
        "ram_session_name": "",
        "private_key": "",
        "key_pair_name": "",
        "expired_seconds": 0,
        "verified": "",
        "region_id": "cn-chengdu",
        "output_format": "json",
        "language": "en",
        "site": "china",
        "retry_timeout": 0,
        "retry_count": 0
}

**Comment by night556** [comment]
> * aliyun configure set --profile stsTokenProfile --mode StsToken --region cn-chengdu --access-key-id NHRqGaKU7E2 **--access-key-secret J5XfiEt**k --sts-token wF1q6Ft5B2yfSjIr4vnOv

你好，我们已经收到此issue，正在排查中

**Comment by night556** [comment]
> * **命令格式**:
>   aliyun --version
>   Alibaba Cloud Command Line Interface Version 3.0.27
> * **执行命令**:
>   aliyun configure set --profile stsTokenProfile --mode StsToken --region cn-chengdu --access-key-id NHRqGaKU7E2 **--access-key-secret J5XfiEt**k --sts-token wF1q6Ft5B2yfSjIr4vnOv
> * **输出**:
>   aliyun configure get --profile stsTokenProfile
>   {
>   "name": "stsTokenProfile",
>   "mode": "StsToken",
>   "access_key_id": "NHRqGaKU7E2",
>   **"access_key_secret": "NHRqGaKU7E2"**,
>   "sts_token": "wF1q6Ft5B2yfSjIr4vnOv",
>   "ram_role_name": "",
>   "ram_role_arn": "",
>   "ram_session_name": "",
>   "private_key": "",
>   "key_pair_name": "",
>   "expired_seconds": 0,
>   "verified": "",
>   "region_id": "cn-chengdu",
>   "output_format": "json",
>   "language": "en",
>   "site": "china",
>   "retry_timeout": 0,
>   "retry_count": 0
>   }

您好，我们将尽快发布新版本已解决此问题，在此期间您可以使用 `aliyun configure --profile <Profile Name> --mode StsToken` 以绕过 set 命令的该bug。
我们将在发布新版本后在此issue下通知您。
如果仍有其他问题，请联系我们。

**Comment by night556** [comment]
> * **命令格式**:
>   aliyun --version
>   Alibaba Cloud Command Line Interface Version 3.0.27
> * **执行命令**:
>   aliyun configure set --profile stsTokenProfile --mode StsToken --region cn-chengdu --access-key-id NHRqGaKU7E2 **--access-key-secret J5XfiEt**k --sts-token wF1q6Ft5B2yfSjIr4vnOv
> * **输出**:
>   aliyun configure get --profile stsTokenProfile
>   {
>   "name": "stsTokenProfile",
>   "mode": "StsToken",
>   "access_key_id": "NHRqGaKU7E2",
>   **"access_key_secret": "NHRqGaKU7E2"**,
>   "sts_token": "wF1q6Ft5B2yfSjIr4vnOv",
>   "ram_role_name": "",
>   "ram_role_arn": "",
>   "ram_session_name": "",
>   "private_key": "",
>   "key_pair_name": "",
>   "expired_seconds": 0,
>   "verified": "",
>   "region_id": "cn-chengdu",
>   "output_format": "json",
>   "language": "en",
>   "site": "china",
>   "retry_timeout": 0,
>   "retry_count": 0
>   }

你好，我们已经发布了3.0.28版本以解决此问题。如果仍有其他问题，请联系我们，该issue将被关闭。
感谢您对Alibaba Cloud CLI 项目的关注！
