### ISSUE TITLE
Alibaba Cloud CLI output error for aliyun rds DescribeDBInstances with --pager option

### ISSUE THREAD

**Issue by raj-kumar-1** [aliyun/aliyun-cli#224]
We need pageable API response merged into one, --pager is the option in alibaba cloud CLI.
We have noticed issue with --pager option with rds describe API, however we see the --pager works well with ecs or slb.

command that works : aliyun rds DescribeDBInstances --region=cn-shenzhen
Command that fails : aliyun rds DescribeDBInstances --region=cn-shenzhen --pager

Output Error : 
panic: interface conversion: interface {} is nil, not float64
goroutine 1 [running]:
github.com/aliyun/aliyun-cli/openapi.(*Pager).FeedResponse(0xc00013ed80, 0xc000238c60, 0x86, 0x0, 0x0)
        /root/aliyun-cli/openapi/pager.go:143 +0x957
github.com/aliyun/aliyun-cli/openapi.(*Pager).CallWith(0xc00013ed80, 0x10d26e0, 0xc0005a0120, 0x2, 0x2, 0xc0005801c8, 0x8)
        /root/aliyun-cli/openapi/pager.go:90 +0x95
github.com/aliyun/aliyun-cli/openapi.(*Commando).invokeWithHelper(0xc00029b320, 0x10d26e0, 0xc0005a0120, 0xedc432, 0x6, 0xc0005801c8, 0x8, 0x0)
        /root/aliyun-cli/openapi/commando.go:186 +0xc4
github.com/aliyun/aliyun-cli/openapi.(*Commando).processInvoke(0xc00029b320, 0xc000069c80, 0x7fff3830434c, 0x3, 0x7fff38304350, 0x13, 0x0, 0x0, 0x1e, 0x0)
        /root/aliyun-cli/openapi/commando.go:136 +0x1c4
github.com/aliyun/aliyun-cli/openapi.(*Commando).main(0xc00029b320, 0xc000069c80, 0xc000469c40, 0x2, 0x2, 0x108859c, 0x55)
        /root/aliyun-cli/openapi/commando.go:104 +0x5e6
github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc000092e60, 0xc000069c80, 0xc000020090, 0x7, 0x7, 0x98, 0x99)
        /root/aliyun-cli/cli/command.go:236 +0x5e7
github.com/aliyun/aliyun-cli/cli.(*Command).Execute(0xc000092e60, 0xc000069c80, 0xc000020090, 0x7, 0x7)
        /root/aliyun-cli/cli/command.go:85 +0x5e
main.main()
        /root/aliyun-cli/main/main.go:89 +0x725

* **Command Format**:

* **Execution Command**:

* **Output**:

**Comment by night556** [comment]
> We need pageable API response merged into one, --pager is the option in alibaba cloud CLI.
> We have noticed issue with --pager option with rds describe API, however we see the --pager works well with ecs or slb.
> 
> command that works : aliyun rds DescribeDBInstances --region=cn-shenzhen
> Command that fails : aliyun rds DescribeDBInstances --region=cn-shenzhen --pager
> 
> Output Error :
> panic: interface conversion: interface {} is nil, not float64
> goroutine 1 [running]:
> github.com/aliyun/aliyun-cli/openapi.(*Pager).FeedResponse(0xc00013ed80, 0xc000238c60, 0x86, 0x0, 0x0)
> /root/aliyun-cli/openapi/pager.go:143 +0x957
> github.com/aliyun/aliyun-cli/openapi.(*Pager).CallWith(0xc00013ed80, 0x10d26e0, 0xc0005a0120, 0x2, 0x2, 0xc0005801c8, 0x8)
> /root/aliyun-cli/openapi/pager.go:90 +0x95
> github.com/aliyun/aliyun-cli/openapi.(*Commando).invokeWithHelper(0xc00029b320, 0x10d26e0, 0xc0005a0120, 0xedc432, 0x6, 0xc0005801c8, 0x8, 0x0)
> /root/aliyun-cli/openapi/commando.go:186 +0xc4
> github.com/aliyun/aliyun-cli/openapi.(*Commando).processInvoke(0xc00029b320, 0xc000069c80, 0x7fff3830434c, 0x3, 0x7fff38304350, 0x13, 0x0, 0x0, 0x1e, 0x0)
> /root/aliyun-cli/openapi/commando.go:136 +0x1c4
> github.com/aliyun/aliyun-cli/openapi.(*Commando).main(0xc00029b320, 0xc000069c80, 0xc000469c40, 0x2, 0x2, 0x108859c, 0x55)
> /root/aliyun-cli/openapi/commando.go:104 +0x5e6
> github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc000092e60, 0xc000069c80, 0xc000020090, 0x7, 0x7, 0x98, 0x99)
> /root/aliyun-cli/cli/command.go:236 +0x5e7
> github.com/aliyun/aliyun-cli/cli.(*Command).Execute(0xc000092e60, 0xc000069c80, 0xc000020090, 0x7, 0x7)
> /root/aliyun-cli/cli/command.go:85 +0x5e
> main.main()
> /root/aliyun-cli/main/main.go:89 +0x725
> 
> * **Command Format**:
> * **Execution Command**:
> * **Output**:

Hi, please refer to the documentation for this issue: https://www.alibabacloud.com/help/doc-detail/122112.htm?spm=a2c63.p38356.b99.20.5df95922A2vDW8
Thank you for your attention to Alibaba Cloud CLI Project!
Please contact us if you have any other questions.
