### ISSUE TITLE
Cannot list Table Store instances

### ISSUE THREAD

**Issue by yanc0** [aliyun/aliyun-cli#226]
Hi,

* **Command Format**:

`$ aliyun ots ListInstance`

* **Output**:
```
ERROR: unknown endpoint for ots/cn-beijing! failed unknown endpoint for region cn-beijing
  you need to add --endpoint xxx.aliyuncs.com

Use flag --endpoint xxx.aliyuncs.com to assign endpoint, see 'https://help.aliyun.com/api/ots' or `aliyun help ots` get more information.
```

I cannot find any information about the endpoint needed for this command to run.

Regards,

**Comment by yanc0** [comment]
Hi,

Any update or help? I still cannot find the endpoint needed. :(

Thanks

**Comment by night556** [comment]
> Hi,
> 
> Any update or help? I still cannot find the endpoint needed. :(
> 
> Thanks

Hi, we have received the question, you can use `--endpoint ots. [RegionId] .aliyuncs.com` to specify the endpoint first. 
For example, RegionId is cn-hanghzou, use `--endpoint ots.cn-hangzhou.aliyuncs.com`.

**Comment by nlamirault** [comment]
Thanks. It works : 

```
$ aliyun ots ListInstance --endpoint ots.eu-central-1.aliyuncs.com
{
        "TotalCount": 0,
        "InstanceInfos": {
                "InstanceInfo": []
        },
        "PageSize": 2000,
        "RequestId": "19BBCD19-1D5E-4CDB-BF32-DC8EFCF5D1D6",
        "PageNum": 1
}
```

**Comment by yanc0** [comment]
Thanks !
