### ISSUE TITLE
RROR: [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Read timeout. Please set a valid ReadTimeout.

### ISSUE THREAD

**Issue by ianpowell2017** [aliyun/aliyun-cli#233]
* **Command Format**:
ros CreateStack

* **Execution Command**:
.\aliyun.exe ros CreateStack --RegionId eu-west-1 --StackName "test" --TemplateURL "{path to the url of the template}" --TimeoutInMinutes 60

* **Output**:
ERROR: [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Read timeout. Please set a valid ReadTimeout.
caused by:
Post https://ros.aliyuncs.com/?AccessKeyId=***********&Action=CreateStack&Format=JSON&RegionId=eu-west-1&Signature=************&SignatureMethod=HMAC-SHA1&SignatureNonce=***************
50&SignatureType=&SignatureVersion=1.0&StackName=test&TemplateURL=****************&TimeoutInMinutes=60&Timestamp=2019-11-28T13%3A38%3A58Z&Version=2019-09
-10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Recently started happening.  I have updated to the latest version, problem remains. Can the timeout be adjusted from the command line?

**Comment by night556** [comment]
> * **Command Format**:
>   ros CreateStack
> * **Execution Command**:
>   .\aliyun.exe ros CreateStack --RegionId eu-west-1 --StackName "test" --TemplateURL "{path to the url of the template}" --TimeoutInMinutes 60
> * **Output**:
>   ERROR: [SDK.TimeoutError] The request timed out 4 times(4 for retry), perhaps we should have the threshold raised a little? Read timeout. Please set a valid ReadTimeout.
>   caused by:
>   Post https://ros.aliyuncs.com/?AccessKeyId=***********&Action=CreateStack&Format=JSON&RegionId=eu-west-1&Signature=************&SignatureMethod=HMAC-SHA1&SignatureNonce=***************
>   50&SignatureType=&SignatureVersion=1.0&StackName=test&TemplateURL=****************&TimeoutInMinutes=60&Timestamp=2019-11-28T13%3A38%3A58Z&Version=2019-09
>   -10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> 
> Recently started happening. I have updated to the latest version, problem remains. Can the timeout be adjusted from the command line?

Hi, you can use `--retry-timeout` to set the retry time.
