### ISSUE TITLE
[Feature request] add support for private dns zone

### ISSUE THREAD

**Issue by yongzhang** [aliyun/aliyun-cli#235]
Hi, team

Please add support to operate dns private zone, thanks.

**Comment by night556** [comment]
> Please add support to operate dns private zone, thanks.

Hi, the CLI is for the public network. If you want to use the endpoint of the intranet, use --endpoint to specify the endpoint of the intranet.

**Comment by yongzhang** [comment]
> > Please add support to operate dns private zone, thanks.
> 
> Hi, the CLI is for the public network. If you want to use the endpoint of the intranet, use --endpoint to specify the endpoint of the intranet.

Actually what I'm saying is:
https://api.aliyun.com/#/?product=pvtz

**Comment by night556** [comment]
> > > Please add support to operate dns private zone, thanks.
> > 
> > 
> > Hi, the CLI is for the public network. If you want to use the endpoint of the intranet, use --endpoint to specify the endpoint of the intranet.
> 
> Actually what I'm saying is:
> https://api.aliyun.com/#/?product=pvtz

Sorry I misunderstood, the product is not yet supported on the cli, we will contact the product side to inquire

**Comment by yongzhang** [comment]
> > > > Please add support to operate dns private zone, thanks.
> > > 
> > > 
> > > Hi, the CLI is for the public network. If you want to use the endpoint of the intranet, use --endpoint to specify the endpoint of the intranet.
> > 
> > 
> > Actually what I'm saying is:
> > https://api.aliyun.com/#/?product=pvtz
> 
> Sorry I misunderstood, the product is not yet supported on the cli, we will contact the product side to ask for related information. If there is further news, we will reply under this issue. If you urgently need to use the product, please try to use `--force` to call the relevant interface of the product. https://www.alibabacloud.com/help/doc-detail/122113.htm?spm=a2c63.p38356.b99.21.31c01e0dbiyemc

Really thanks for this, `--force` works for me as a workaround:
$ aliyun pvtz DescribeZones --force --version 2018-01-01 --endpoint pvtz.aliyuncs.com
{
        "PageNumber": 1,
        "PageSize": 20,
        "RequestId": "xxx",
        "TotalItems": 0,
        "TotalPages": 1,
        "Zones": {
                "Zone": []
        }
}

**Comment by night556** [comment]
> > > > > Please add support to operate dns private zone, thanks.
> > > > 
> > > > 
> > > > Hi, the CLI is for the public network. If you want to use the endpoint of the intranet, use --endpoint to specify the endpoint of the intranet.
> > > 
> > > 
> > > Actually what I'm saying is:
> > > https://api.aliyun.com/#/?product=pvtz
> > 
> > 
> > Sorry I misunderstood, the product is not yet supported on the cli, we will contact the product side to ask for related information. If there is further news, we will reply under this issue. If you urgently need to use the product, please try to use `--force` to call the relevant interface of the product. https://www.alibabacloud.com/help/doc-detail/122113.htm?spm=a2c63.p38356.b99.21.31c01e0dbiyemc
> 
> Really thanks for this, `--force` works for me as a workaround:
> 
> ```
> $ aliyun pvtz DescribeZones --force --version 2018-01-01 --endpoint pvtz.aliyuncs.com
> {
>         "PageNumber": 1,
>         "PageSize": 20,
>         "RequestId": "xxx",
>         "TotalItems": 0,
>         "TotalPages": 1,
>         "Zones": {
>                 "Zone": []
>         }
> }
> ```

Glad your issue has been resolved and the issue will be closed.
