### ISSUE TITLE
[Feature Request] auto detect ecs role and use EcsRamRole as default mode

### ISSUE THREAD

**Issue by yongzhang** [aliyun/aliyun-cli#244]
EcsRamRole模式下无法自动识别ECS的role吗？为什么需要手动输入`Ecs Ram Role`？
```
aliyun configure --profile ecsRamRoleProfile --mode EcsRamRole
Configuring profile 'ecsRamRoleProfile' in 'EcsRamRole' authenticate mode...
Ecs Ram Role []: 

```

Edited:
@night556 
我们是否可以像aws cli那样，没有任何default profile的时候，即`.aliyun/config.json`不存在的时候，默认模式为EcsRamRole？并且在执行命令的时候，自动检测其ram role而无需用户手动传入role name？

**Comment by yongzhang** [comment]
另外，aliyun cli安装在ecs里面，可否默认为EcsRamRole模式（不需要aliyun configure），并且自动识别role？

**Comment by night556** [comment]
> 另外，aliyun cli安装在ecs里面，可否默认为EcsRamRole模式（不需要aliyun configure），并且自动识别role？

CLI 现在没有自动识别ecs环境的能力。对于CLI程序，从某些方面来说，ecs只能被识别为一个操作系统，而不能被识别为其他特殊的环境。

**Comment by elsnepal** [comment]
would be good if it simply falls down the order & reads metadata.. should not require configuration at all if there is no ENV to conflict.
