### ISSUE TITLE
是否可以封装成SDK

### ISSUE THREAD

**Issue by pc10201** [aliyun/aliyun-cli#248]
感觉这个工具很好用啊

是否可以封装成SDK，感觉阿里云golang sdk还是有点麻烦的，经常要自己处理分页

**Comment by night556** [comment]
> 感觉这个工具很好用啊
> 
> 是否可以封装成SDK，感觉阿里云golang sdk还是有点麻烦的，经常要自己处理分页

感谢你的使用，关于SDK，CLI也是基于Golang SDK进行编写的代码，且CLI的代码不会保证兼容性，所以不适合继续封装成sdk的。
