### ISSUE TITLE
proxy support does not seem to work

### ISSUE THREAD

**Issue by brianbordini** [aliyun/aliyun-cli#249]
* **Command Format**:

aliyun oss ls

* **Execution Command**:

it does not show anything

* **Output**:

it keeps running without end

I am running aliyun command in a corporate network with proxy servers. I use CNTLM local proxy to authenticate to these proxies

Version: 3.0.32
Environment variables set: http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY

I look at the logs of CNTLM but I do not see any requests logged to aliyun

Can you provide which endpoint the aliyun cli connects ? I wish to confirm if it is an issue at the proxy server or at the CLI.

Is there a debug option for the CLI ?

**Comment by brianbordini** [comment]
After some time, the error appears:

ERROR: Get http://oss-cn-shanghai.aliyuncs.com/?marker=&prefix=: dial tcp 106.14.228.194:80: i/o timeout

**Comment by night556** [comment]
> * **Command Format**:
> 
> aliyun oss ls
> 
> * **Execution Command**:
> 
> it does not show anything
> 
> * **Output**:
> 
> it keeps running without end
> 
> I am running aliyun command in a corporate network with proxy servers. I use CNTLM local proxy to authenticate to these proxies
> 
> Version: 3.0.32
> Environment variables set: http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY
> 
> I look at the logs of CNTLM but I do not see any requests logged to aliyun
> 
> Can you provide which endpoint the aliyun cli connects ? I wish to confirm if it is an issue at the proxy server or at the CLI.
> 
> Is there a debug option for the CLI ?

You can set the environment variable `DEBUG = sdk` to view debug information.

**Comment by brianbordini** [comment]
@night556 

I did 

`export DEBUG=sdk` 

but I do not see anything

**Comment by night556** [comment]
> @night556
> 
> I did
> 
> `export DEBUG=sdk`
> 
> but I do not see anything

I just noticed that you are using the `oss` product, please use the` --proxy-host`, `--proxy-user`,` --proxy-pwd` options to specify the proxy. Examples are:
`aliyun oss ls oss://bucket1 --proxy-host http://47.88.**.**:3128 --proxy-user test --proxy-pwd test`

**Comment by brianbordini** [comment]
> > @night556
> > I did
> > `export DEBUG=sdk`
> > but I do not see anything
> 
> I just noticed that you are using the `oss` product, please use the` --proxy-host`, `--proxy-user`,` --proxy-pwd` options to specify the proxy. Examples are:
> `aliyun oss ls oss://bucket1 --proxy-host http://47.88.**.**:3128 --proxy-user test --proxy-pwd test`

it works with the --proxy-host. The request completes (I think I have not the right permission in the RAM)

[xeno@ws ~ (k8s ctx: eks_customer-qual-aws-eu-central-1)]$ aliyun oss ls --proxy-host http://192.168.56.2:3128 

ERROR: oss: service returned error: StatusCode=403, ErrorCode=AccessDenied, ErrorMessage="You are forbidden to list buckets.", RequestId=5E254E72ED0B59373839AD87

If I try another command like
```
aliyun ecs DescribeRegions

> GET ...
> Host: location-readonly.aliyuncs.com
> x-sdk-core-version: 0.0.1
> Content-Type: application/x-www-form-urlencoded
> x-sdk-client: golang/1.0.0
> x-sdk-invoke-type: common
> Accept-Encoding: identity
> User-Agent: AlibabaCloud (linux; amd64) Golang/1.12.9 Core/0.0.1 Aliyun-CLI/3.0.32

	"RequestId": "0458DEB8-9EE9-45A5-BDD5-18E05BA9E8D7",
	"Regions": {
		"Region": [
			{
				"RegionId": "cn-qingdao",
				"RegionEndpoint": "ecs.aliyuncs.com",
				"LocalName": "华北 1"
			}
```

I have the output with debug information and without specifying the proxy

**Comment by night556** [comment]
@brianbordini The environment variable `DEBUG = sdk` does not display proxy information. In addition, because the` oss` command is different from the logic used by other products, this environment variable has no effect on the `oss` command.
