### ISSUE TITLE
SpotDuration description missing in the docs

### ISSUE THREAD

**Issue by alexeyshishkin01** [aliyun/aliyun-cli#251]
* **Command Format**:

* **Execution Command**:

* **Output**:

root@Alexey-HP:~# aliyun version
3.0.32
root@Alexey-HP:~# aliyun ecs CreateInstance --help | grep -i spot
  --SpotDuration                  Integer Optional
  --SpotInterruptionBehavior      String  Optional
  --SpotPriceLimit                Float   Optional
  --SpotStrategy                  String  Optional
root@Alexey-HP:~#

the docs https://www.alibabacloud.com/help/doc-detail/25499.htm doesn't describe 'SpotDuration' parmeter

**Comment by night556** [comment]
> * **Command Format**:
> * **Execution Command**:
> * **Output**:
> 
> root@Alexey-HP:~# aliyun version 3.0.32 root@Alexey-HP:~# aliyun ecs CreateInstance --help | grep -i spot
> --SpotDuration Integer Optional
> --SpotInterruptionBehavior String Optional
> --SpotPriceLimit Float Optional
> --SpotStrategy String Optional
> root@Alexey-HP:~#
> 
> the docs https://www.alibabacloud.com/help/doc-detail/25499.htm doesn't describe 'SpotDuration' parmeter

Due to frequent data changes, the cli help information and official website documents may have synchronization problems, and will not be intentionally repaired without affecting the use.

**Comment by alexeyshishkin01** [comment]
How are you going to catch up AWS/Azure/GCP/IBM clouds this way?

**Comment by night556** [comment]
> How are you going to catch up AWS/Azure/GCP/IBM clouds this way?



> How are you going to catch up AWS/Azure/GCP/IBM clouds this way?

We have noticed this problem before, and it is being improved. Please rest assured that this problem will be solved in the future.
