### ISSUE TITLE
优化用户体验：JSON格式输出时，字段名是乱序的，建议按照A-Z字母排序。

### ISSUE THREAD

**Issue by endless-learner** [aliyun/aliyun-cli#253]
* **需求类型**:
优化用户体验

* **需求描述**:
JSON格式输出时，字段名是乱序的，建议按照A-Z字母排序。

* **设计方案**:

**Comment by night556** [comment]
> * **需求类型**:
>   优化用户体验
> * **需求描述**:
>   JSON格式输出时，字段名是乱序的，建议按照A-Z字母排序。
> * **设计方案**:

json和map本身是无序设计的，且CLI并没有对返回内容进行更改，直接返回的api服务端数据

**Comment by mutoo** [comment]
@night556 js/json 定义的 map 确实是无序的，但是如果能有序输出的话，确实是一个提升体验的改进。

我在使用 cli 的过程中，需要将 json 输出保存并做版本控制。无序的输出每次都造成大量 diff，不可读，非常恼人。

**Comment by night556** [comment]
> @night556 js/json 定义的 map 确实是无序的，但是如果能有序输出的话，确实是一个提升体验的改进。
> 
> 我在使用 cli 的过程中，需要将 json 输出保存并做版本控制。无序的输出每次都造成大量 diff，不可读，非常恼人。

谢谢您提供的使用场景需求，我们将会考虑该需求是否加入后期开发。如有进展，我们会在该issue下回复您。

**Comment by endless-learner** [comment]
@night556 看看这里 
https://stackoverflow.com/questions/18668652/how-to-produce-json-with-sorted-keys-in-go  

在cli里面稍微处理一下这个排序可以极大地改善可读性。
而如果你要求每个API 本身的output是有序的，则可以说需要几十个乃至上百个云产品去修改API，那兼职是遥遥无期。

**Comment by mutoo** [comment]
@night556 @endless-learner 我现在的解决方案是使用 `aliyun ecs DescribeInstances | jq --sort-keys` 可以试试，效果不错。

**Comment by night556** [comment]
> * **需求类型**:
>   优化用户体验
> * **需求描述**:
>   JSON格式输出时，字段名是乱序的，建议按照A-Z字母排序。
> * **设计方案**:

在最新版本中，该输出优化已实现。
