### ISSUE TITLE
after deleting the default configure, aliyun stops working

### ISSUE THREAD

**Issue by charleszheng44** [aliyun/aliyun-cli#254]
After deleting the default configure (the default configure was the only configure),
I keep getting the error message, `ERROR: load current configuration failed unknown profile default, run configure to check`, regardless of the subcommand I use (I can't even run `aliyun configure`).

**Comment by charleszheng44** [comment]
fix by deleting the `~/.aliyun/config.json`.

**Comment by Jasonlhy** [comment]
I also encounter this issue ... is it a bug ?

**Comment by nweisenauer-sap** [comment]
This bug still exists ... I could not find out how to logout from aliyun cli, so I deleted the default profile. Then I ran into this issue. Please reopen? @charleszheng44 @sdk-team
