### ISSUE TITLE
Update to latest Go SDK to fix STS issues

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#256]
* **Type of Demand**:
Please update Go SDK reference to also include latest change to https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/sts/endpoint.go#L10 which updates STS endpoints accordingly.
* **Detailed Description**:
Release v1.61.1 of Go SDK should be added to vendor.

**Comment by night556** [comment]
CLI does not depend on this file, so this file update will not affect cli. If you have any questions, please let us know
