### ISSUE TITLE
支持NextToken的翻页方式

### ISSUE THREAD

**Issue by ayanamist** [aliyun/aliyun-cli#260]
* **需求类型**:
优化用户体验

* **需求描述**:
部分openapi已经提供了NextToken+MaxResults的翻页方式，能否支持这种，传统的分页方式，在数据频繁增减的情况下，会丢数据。

* **设计方案**:

**Comment by night556** [comment]
> * **需求类型**:
>   优化用户体验
> * **需求描述**:
>   部分openapi已经提供了NextToken+MaxResults的翻页方式，能否支持这种，传统的分页方式，在数据频繁增减的情况下，会丢数据。
> * **设计方案**:

请问能否提供一个该分页形式的简单api接口用于测试。

**Comment by ayanamist** [comment]
https://help.aliyun.com/document_detail/58512.html

例如这个

> 方式一：通过NextToken设置查询凭证（Token），其取值是上一次调用DescribeNetworkInterfaces返回的NextToken参数值，再通过MaxResults设置单页查询的最大条目数。
