### ISSUE TITLE
go get github.com/jteeuwen/go-bindata/...: no matching versions for query "latest"

### ISSUE THREAD

**Issue by ZenBoy999** [aliyun/aliyun-cli#261]
* **命令格式**:

* **执行命令**:
make install
* **输出**:
go get -u github.com/aliyun/aliyun-openapi-meta
go: finding github.com/aliyun/aliyun-openapi-meta latest
go get -u github.com/jteeuwen/go-bindata/...
go: finding github.com/jteeuwen/go-bindata/... latest
go get github.com/jteeuwen/go-bindata/...: no matching versions for query "latest"
make: *** [Makefile:9：deps] 错误 1

**Comment by night556** [comment]
> * **命令格式**:
> * **执行命令**:
>   make install
> * **输出**:
>   go get -u github.com/aliyun/aliyun-openapi-meta
>   go: finding github.com/aliyun/aliyun-openapi-meta latest
>   go get -u github.com/jteeuwen/go-bindata/...
>   go: finding github.com/jteeuwen/go-bindata/... latest
>   go get github.com/jteeuwen/go-bindata/...: no matching versions for query "latest"
>   make: *** [Makefile:9：deps] 错误 1

该情况可能是由于gomod的引入导致，我们会在未来考虑修改或移除该makefile文件，如果你希望自行编译，请参考文档：https://help.aliyun.com/document_detail/121545.html?spm=a2c4g.11186623.6.549.3b0758ebIHywJA

**Comment by ZenBoy999** [comment]
嗯嗯，感谢。 按照 aliyun.com 上的文档，在 x86-64 上编译成功了。 在 Ubuntu 上还是事先安装了 go-bindata 软件包就可以。 文档里面 go build 的取当前版本号，建议用 shell 命令 $(git describe --tags) 就可以。不过要去掉第一个字母 v， 也就是 git describe --tags|sed -e 's/^v//g' 即可
