### ISSUE TITLE
build doesn't work with https://github.com/shuLhan/go-bindata

### ISSUE THREAD

**Issue by aschleifer** [aliyun/aliyun-cli#262]
I'm trying to build the alicloud-cli withe go-bindata from https://github.com/shuLhan/go-bindata which seems to be the current version as the https://github.com/jteeuwen/go-bindata (whish is used in the build documentation) is archived.

However when doing this I get the following error when I execute the binary at the end:

```
panic: read json from products.json failed &{[]}
goroutine 1 [running]:
github.com/aliyun/aliyun-cli/meta.LoadRepository(0xff2a0f20ae0, 0xff2a191b1a0, 0xc0000ad7a0)
        github.com/aliyun/aliyun-cli/meta/repository.go:35 +0x613
github.com/aliyun/aliyun-cli/openapi.NewLibrary(...)
        github.com/aliyun/aliyun-cli/openapi/library.go:38
github.com/aliyun/aliyun-cli/openapi.NewCommando(0xff2a0f21940, 0xc0000a8008, 0xff2a0bf540f, 0x7, 0xff2a0bf30fb, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/aliyun/aliyun-cli/openapi/commando.go:43 +0xa4
main.main()
        command-line-arguments/main.go:77 +0x3ec
```

It would be nice if this could be fixed so that this tool doesn't rely on archived software.

**Comment by yagrxu** [comment]
@night556 能看一下这个问题么？ 似乎bindata 版本比较老，看看是不是有可能更新一下？

**Comment by night556** [comment]
> I'm trying to build the alicloud-cli withe go-bindata from https://github.com/shuLhan/go-bindata which seems to be the current version as the https://github.com/jteeuwen/go-bindata (whish is used in the build documentation) is archived.
> 
> However when doing this I get the following error when I execute the binary at the end:
> 
> ```
> panic: read json from products.json failed &{[]}
> goroutine 1 [running]:
> github.com/aliyun/aliyun-cli/meta.LoadRepository(0xff2a0f20ae0, 0xff2a191b1a0, 0xc0000ad7a0)
>         github.com/aliyun/aliyun-cli/meta/repository.go:35 +0x613
> github.com/aliyun/aliyun-cli/openapi.NewLibrary(...)
>         github.com/aliyun/aliyun-cli/openapi/library.go:38
> github.com/aliyun/aliyun-cli/openapi.NewCommando(0xff2a0f21940, 0xc0000a8008, 0xff2a0bf540f, 0x7, 0xff2a0bf30fb, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
>         github.com/aliyun/aliyun-cli/openapi/commando.go:43 +0xa4
> main.main()
>         command-line-arguments/main.go:77 +0x3ec
> ```
> 
> It would be nice if this could be fixed so that this tool doesn't rely on archived software.

CLI only uses bindata for the packaging process and has not encountered any problems at present, so relatively speaking, the archived project is more stable. If there is no significant impact basis, we will not consider updating this dependency for the time being.

**Comment by night556** [comment]
> I'm trying to build the alicloud-cli withe go-bindata from https://github.com/shuLhan/go-bindata which seems to be the current version as the https://github.com/jteeuwen/go-bindata (whish is used in the build documentation) is archived.
> 
> However when doing this I get the following error when I execute the binary at the end:
> 
> ```
> panic: read json from products.json failed &{[]}
> goroutine 1 [running]:
> github.com/aliyun/aliyun-cli/meta.LoadRepository(0xff2a0f20ae0, 0xff2a191b1a0, 0xc0000ad7a0)
>         github.com/aliyun/aliyun-cli/meta/repository.go:35 +0x613
> github.com/aliyun/aliyun-cli/openapi.NewLibrary(...)
>         github.com/aliyun/aliyun-cli/openapi/library.go:38
> github.com/aliyun/aliyun-cli/openapi.NewCommando(0xff2a0f21940, 0xc0000a8008, 0xff2a0bf540f, 0x7, 0xff2a0bf30fb, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
>         github.com/aliyun/aliyun-cli/openapi/commando.go:43 +0xa4
> main.main()
>         command-line-arguments/main.go:77 +0x3ec
> ```
> 
> It would be nice if this could be fixed so that this tool doesn't rely on archived software.

Regarding this issue, we may update to https://github.com/shuLhan/go-bindata.
But for the two versions of bindata, we also conducted some usage tests, for the following scenarios:
Package the `aliyun-openapi-meta` folder and read the` products.json` in it.
For `https: // github.com / shuLhan / go-bindata`:
Packaging: `go-bindata ../ aliyun-openapi-meta / ...`
Read: `Asset (" ../ aliyun-openapi-meta / product.json ")`
Packaging: `go-bindata --prefix ../aliyun-openapi-meta ../ aliyun-openapi-meta / ...`
Read: `Asset (" ../ aliyun-openapi-meta /../ aliyun-openapi-meta / product.json ")`
For `https: // github.com / jteeuwen / go-bindata`:
Packaging: `go-bindata --prefix ../aliyun-openapi-meta ../ aliyun-openapi-meta / ...`
Read: `Asset (" product.json ")`
The first bindata program will make the path of Asset need to care about the path in the packaging command, that is, our code will depend on the input of the external packaging command (../aliyun-openapi-meta).
The second bindata program does not have this problem. The internal path of the directly packaged folder is mainly used, and there is no need to care about the external path (../aliyun-openapi-meta).
If the test is unreasonable or wrong, or if https://github.com/shuLhan/go-bindata is better, please let us know, thank you very much!

**Comment by anthraxx** [comment]
well I believe its better to look for alternative ways of handling things instead of relying on a tool variant that was literally archived because its no longer maintained. If you want to have a certain feature (like the path handling) that is not currently supported in the maintained variant it would be a better way to open a discussion there or even submit patches to a maintained variant.
Not just because of bug fixes but also because of potential security fixes in the past. It's never a good idea to rely on unsupported and unmaintained tools.

**Comment by anthraxx** [comment]
thanks for implementing
