### ISSUE TITLE
命令行的反馈很难让人明白什么是问题的根源

### ISSUE THREAD

**Issue by yagrxu** [aliyun/aliyun-cli#264]
* **命令格式**:

* **执行命令**:
aliyun cr GetAuthorizationToken --RegionId eu-central-1
* **输出**:
ERROR: region can't be empty
Configuration failed, use `aliyun configure` to configure it

其实问题在于没有配置profile - 这个提示的错误是region 为空

**Comment by night556** [comment]
> * **命令格式**:
> * **执行命令**:
>   aliyun cr GetAuthorizationToken --RegionId eu-central-1
> * **输出**:
>   ERROR: region can't be empty
>   Configuration failed, use `aliyun configure` to configure it
> 
> 其实问题在于没有配置profile - 这个提示的错误是region 为空

没有配置命令也不一定会出错，你可以理解为这类似于错误栈，第一行的错误表明最根本的错误，第二行算是表明的是上述类型错误的一个合集。有可能第一行表明ak没有，而第二行报同样的错误。
