### ISSUE TITLE
OSS does not work with STS Token

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#265]
Hi--, 

I'm using Aliyun CLI `v3.0.23`.

The CLI does not seem to work with STS token when used for OSS:

```
aliyun --access-key-id $ALICLOUD_ACCESS_KEY --access-key-secret $ALICLOUD_SECRET_KEY --sts-token $ALICLOUD_STS_TOKEN oss ls
```

It always fails with
```
ERROR: config failed: invalid access_key_id:
```

It works, however, when used with other service such as ECS:
```
aliyun --access-key-id $ALICLOUD_ACCESS_KEY --access-key-secret $ALICLOUD_SECRET_KEY --sts-token $ALICLOUD_STS_TOKEN ecs DescribeInstances
```

According to https://www.alibabacloud.com/help/doc-detail/135527.htm OSS supports STS. Is this a bug? Thanks!

**Comment by night556** [comment]
Regarding this issue, we also need to look at it.
You can try to configure credentials with `aliyun configure --mode StsToken` before using the `oss` command.
