### ISSUE TITLE
aliyuncli oss 下载时文件夹名称问题

### ISSUE THREAD

**Issue by EVEhehe** [aliyun/aliyun-cli#27]
为什么会出现将oss..../call/2167170/路径下载到本地变成/call/216717/0/这种情况

**Comment by lvscar** [comment]
你好 @EVEhehe 。 因为阿里云OSS 变更了SDK且发布了专门的CLI工具，在近期版本的aliyuncli 中。我们停止了对oss的支持，请你 访问 https://github.com/aliyun/ossutil 获取 ossutil 工具配合阿里云 OSS使用. 谢谢
