### ISSUE TITLE
Variable value not updated in aliyun cli command

### ISSUE THREAD

**Issue by learnawswithus** [aliyun/aliyun-cli#274]
I am getting autoscaling groupid value in the variable name : asgId
When I pass the same in aliyun command, I am getting the below error.

ubuntu@ip-172-31-7-159:~$ echo $asgId
"asg-a2dh6wqg2dawkx6oi4y0"

Error when passed as variable:
===================
ubuntu@ip-172-31-7-159:~$ aliyun ess EnableScalingGroup --ScalingGroupId $asgId
ERROR: SDK.ServerError
ErrorCode: InvalidScalingGroupId.NotFound
Recommend:
RequestId: 37F3EDD4-E2B7-4FF3-A38D-76970E53B478
Message: The specified scaling group does not exist.

ubuntu@ip-172-31-7-159:~$ echo "aliyun ess EnableScalingGroup --ScalingGroupId $asgId"
aliyun ess EnableScalingGroup --ScalingGroupId "asg-a2dh6wqg2dawkx6oi4y0"

Works fine if the same is applied directly:
===========================
ubuntu@ip-172-31-7-159:~$ aliyun ess EnableScalingGroup --ScalingGroupId "asg-a2dh6wqg2dawkx6oi4y0"
{
        "RequestId": "8D843969-BAC5-4F64-A599-526FD72EB52C"
}

**Comment by night556** [comment]
Please set the environment variable `DEBUG = sdk`, and then provide the log to us。

**Comment by learnawswithus** [comment]
Got the issue resolved
