### ISSUE TITLE
ERROR: parse failed not support flag form -1/-1

### ISSUE THREAD

**Issue by oldthreefeng** [aliyun/aliyun-cli#281]
* **Command Format**:

* **Execution Command**:
aliyun ecs AuthorizeSecurityGroup --RegionId cn-hangzhou --SecurityGroupId ******20azsp** --IpProtocol tcp --PortRange '-1/-1' --SourceCidrIp "1.1.1.1"
* **Output**:
ERROR: parse failed not support flag form -1/-1

**Comment by oldthreefeng** [comment]
ERROR: '--RegionId' is not a valid parameter or flag. See `aliyun help ecs AuthorizeSecurityGroup`.

**Comment by oldthreefeng** [comment]
aliyun ecs AuthorizeSecurityGroup --help
Alibaba Cloud Command Line Interface Version 3.0.41

Product: Ecs (Elastic Compute Service)
Link:    https://help.aliyun.com/api/ecs/AuthorizeSecurityGroup.html

Parameters:


这个Parameters为空??

**Comment by night556** [comment]
我们正在排查中，有结果将在这里进行回复

**Comment by night556** [comment]
已经发布了3.0.42版本，请切换至新版本运行。
