### ISSUE TITLE
aliyun cli new version not working in centos 7.7

### ISSUE THREAD

**Issue by learnawswithus** [aliyun/aliyun-cli#282]
[root@varnish aliyun]# ls
aliyun-cli-linux-3.0.42-amd64.tgz
[root@varnish aliyun]# tar xvzf aliyun-cli-linux-3.0.42-amd64.tgz
aliyun
[root@varnish aliyun]# sudo su
[root@varnish aliyun]# mv aliyun /usr/local/bin/
[root@varnish aliyun]# ls
aliyun-cli-linux-3.0.42-amd64.tgz
[root@varnish aliyun]# aliyun
bash: aliyun: command not found
[root@varnish aliyun]#  aliyun configure
bash: aliyun: command not found
[root@varnish aliyun]#

Aliyun CLI installation is failing in CentOS 7.7

**Comment by JacksonTian** [comment]
please use `which aliyun` to check the path.

**Comment by learnawswithus** [comment]
![image](https://user-images.githubusercontent.com/58425545/81478342-5df02880-923a-11ea-9d93-764ebac6e2fd.png)

**Comment by learnawswithus** [comment]
Aliyun was installed on CentOS machine and working fine but suddenly from yesterday afternoon, aliyun stopped working. I terminated the old instance and trying to install aliyun cli in new centos machine, but it is not working.

**Comment by night556** [comment]
The test here is normal. According to your information, we judge that your `/usr/local/bin` directory may not be in the `PATH` environment variable. Please add it to the `PATH` environment variable, or move `aliyun` to another directory, such as `/bin` or `/usr/bin`
