### ISSUE TITLE
aliyun  slb AddAccessControlListEntry --AclEntrys 字段应该怎么填？ 

### ISSUE THREAD

**Issue by oldthreefeng** [aliyun/aliyun-cli#285]
* **Command Format**:
```
aliyun slb DescribeAccessControlListAttribute --RegionId cn-hangzhou --AclId acl-bp1pxxxxxx  --profile default
{
	"AclEntrys": {
		"AclEntry": [
			{
				"AclEntryComment": "公司ip",
				"AclEntryIP": "116.xxx.xx.xxx/32"
			}
		]
	},
	"AclId": "acl-bp1xxxxxxxxxxx",
	"AclName": "mysql访问白名单",
	"AddressIPVersion": "ipv4",
	"RequestId": "D361A621-8022-441D-A643-33662BBD289C",
	"ResourceGroupId": "rg-axxxxxxxxxxy"
}
```
* **Execution Command**:
```
aliyun  slb AddAccessControlListEntry --RegionId cn-hangzhou --AclId acl-bp1xxxxxxxxxxxxxxv  --AclEntrys  '[{"entry":"118.242.35.106","comment":"test"}]'
* **Output**:
ERROR: SDK.ServerError
ErrorCode: InvalidEntry
Recommend: 
RequestId: 26EB1D1F-F0B7-44AE-A71A-A27433B08D83
Message: The specified parameter AclEntrys is not valid
```

官网的说明
```
  [{"entry":"10.0.**.**/24","comment":"privaterule1"},{"entry":"192.168.**.**/16","comment":"privaterule2"}]  
```
依旧报错。
![image](https://user-images.githubusercontent.com/38313565/82297894-e793b900-99e5-11ea-94de-17372ff3eb9f.png)

**Comment by oldthreefeng** [comment]
--AclEntrys "[{\"entry\":\"1.1.1.1/32\",\"comment\":\"privaterule2\"}]"

.....调了半天才找到。。。

**Comment by night556** [comment]
官网只是单纯的值示例，但是对于终端来说，字符串的输入需要符合终端能解析的格式，对于json这种复杂字符串，可以参考：https://help.aliyun.com/document_detail/110340.html?spm=a2c4g.11186623.6.563.3b0716d2SWWioY

**Comment by danielhou09** [comment]
https://help.aliyun.com/document_detail/70023.html  官网api 调试工具试试看
`{\"entry\": \"39.156.69.79\",\"comment\": \"privaterule1\"}`
![image](https://user-images.githubusercontent.com/9412449/124902886-f38d7080-e015-11eb-83b3-5a86b458bd3c.png)
