### ISSUE TITLE
environment variables as credentials can not be read directly

### ISSUE THREAD

**Issue by shijingkun886** [aliyun/aliyun-cli#291]
* **Execution Command**: ALIBABACLOUD_ACCESS_KEY_ID=a ALIBABACLOUD_ACCESS_KEY_SECRET=b ALIBABACLOUD_REGION_ID=cn-hangzhou aliyun oss ls

* **Output**: 

it also read the credentials configured in default profile, and the environment variables are ignore. It only available when you create an invalid profile(empty accessid and secrets).

**Comment by night556** [comment]
This is not a problem, the configuration file is the first choice of cli, when it does not exist, it will read the environment variables.
If you want to temporarily change the credential information on the command line, please use the relevant flag to specify.
