### ISSUE TITLE
ContainerRegistry: easy way to support docker login

### ISSUE THREAD

**Issue by shijingkun886** [aliyun/aliyun-cli#292]
* **Type of Demand**: enhancing features

* **Detailed Description**: we can not get cr temp credential directly. when you run `aliyun cr GetAuthorizationToken` it return an JSON object, if you want to do docker login, you must parse the json and the the correct value.

* **Design**: run command like `aliyun cr GetAuthorizationToken` with a param can get the pure `authorizationToken` value. 

Or make it like aws, output a docker login command:

```
aws ecr get-login
```

output:
```
docker login –u AWS –p password –e none https://aws_account_id.dkr.ecr.us-east-1.amazonaws.com
```

**Comment by night556** [comment]
Sorry we don’t have this feature yet, but we will add this feature in the future, you can now consider using `jq` tool to filter the returned json.
