### ISSUE TITLE
cp download error

### ISSUE THREAD

**Issue by gcagle1** [aliyun/aliyun-cli#295]
* **Command Format**:
```ossutil cp cloud_url file_url  [-r] [-f] [-u] [--only-current-dir] [--output-dir=odir] [--disable-ignore-error] [--bigfile-threshold=size] [--checkpoint-dir=cdir] [--range=x-y] [--payer requester]```
* **Execution Command**:
```aliyun oss cp oss://guest-data-release/project-raw-data/data-release-20200629-2904 ~/Downloads -r ```

* **Output**:
```ERROR: expected element type <ListBucketResult> but have <html>, Bucket=guest-data-release, Object=```

Using mac64

**Comment by night556** [comment]
Use the ossutil tool to run the cp command to check whether the operation is normal. https://help.aliyun.com/document_detail/120075.html?spm=a2c4g.11174283.6.712.64647da2uhFwRd
