### ISSUE TITLE
pem 格式证书作为参数时，参数序列化失败

### ISSUE THREAD

**Issue by ailncode** [aliyun/aliyun-cli#298]
当我使用 aliyun cli 进行cdn自定义证书上传时 aliyun cli 无法正确识别参数
因为 证书中 存在 -- = 字符因而导致了 aliyun cli 将 参数内容识别为了参数名
aliyun cli 版本: 3.0.39
root@tssns-staging:~# aliyun version
3.0.39
* **执行命令**:
aliyun cdn SetDomainServerCertificate \
--CertName www.tssns.com \
--DomainName www.tssns.com \
--ServerCertificateStatus on \
--CertType upload \
--ServerCertificate '-----BEGIN CERTIFICATE-----dHNzbnM=-----END CERTIFICATE-----' \
--PrivateKey '-----BEGIN CERTIFICATE-----dHNzbnM=-----END CERTIFICATE-----'
* **输出**:
ERROR: parse failed flag duplicated -----BEGIN CERTIFICATE-----dHNzbnM

**Comment by night556** [comment]
证书文件内容格式不适合终端直接输入，可以在选项后面加上 `-FILE` 以从文件读取，比如 `--ServerCertificate-FILE <filepath>`

**Comment by ailncode** [comment]
感谢您的回复，晚上我试试，我已经自己写了一个工具调用sdk 上传了。。。。

**Comment by ailncode** [comment]
aliyun cdn SetDomainServerCertificate \
--ForceSet 1 \
--CertType upload \
--CertName www.tssns.com \
--DomainName www.tssns.com \
--ServerCertificateStatus on \
--PrivateKey-FILE /etc/letsencrypt/live/www.tssns.com/privkey.pem \
--ServerCertificate-FILE /etc/letsencrypt/live/www.tssns.com/fullchain.pem
#完全没问题，完美解决了我的问题，希望文档更完善一些。这里比阿里云工单高效了很多。
