### ISSUE TITLE
aliyuncli 找不到 SDK

### ISSUE THREAD

**Issue by handsomecheung** [aliyun/aliyun-cli#3]
Ubuntu 系统上使用 pip 安装 aliyuncli 和 aliyun-python-sdk-rds。
运行 aliyuncli rds 时提示：
usage: aliyuncli <command> <operation> [options and parameters]
<aliyuncli> the valid command as follows:

没有 valid command 可用。
代码中使用 from distutils.sysconfig import get_python_lib 来查找 python 的 lib 目录，但是 get_python_lib 获取到的目录为：/usr/lib/python2.7/dist-packages

而 pip 默认将包安装在 /usr/local/lib/python2.7/dist-packages 下面，所以 aliyuncli 找不到任何可用命令。

**Comment by handsomecheung** [comment]
看文档发现是 Known Issue 了。Closed

**Comment by xiangxixids** [comment]
感谢您的反馈, 目前只有Debian 类系统有这个问题, 尚未发现特别好的解决方案, 如果您有好的解决方案, 欢迎分享给我们!
