### ISSUE TITLE
aliyun cli could not run in alpine linux

### ISSUE THREAD

**Issue by easybest** [aliyun/aliyun-cli#301]
the latest version of aliyun cli could not be runnable in alpine linux.

**Comment by night556** [comment]
Due to different system environments, the provided binary files may not be suitable for all environments, you can try to compile manually.

**Comment by c521wy** [comment]
the binary needs /lib64/ld-linux-x86-64.so.2 to run, try add a link, see below

root@OpenWrt:~# ldd aliyun
	/lib64/ld-linux-x86-64.so.2 (0x7fb7ebaf0000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fb7ebaf0000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fb7ebaf0000)

![image](https://user-images.githubusercontent.com/4578684/104114225-dfa1d400-533c-11eb-9237-a9c0418d15f4.png)

**Comment by wenzuochao** [comment]
I will close the issue. If you have another question, you can reopen the issue or open a new issue. Thanks for your support.
