### ISSUE TITLE
Unable to include OOS Template Name

### ISSUE THREAD

**Issue by awstrainingwithus** [aliyun/aliyun-cli#302]
When I am trying to Create Life Cycle Hook for an auto Scaling group via CLI, I do not find an option to include the OOS Template Run command.

Kindly check and update.
![image](https://user-images.githubusercontent.com/65810411/89170363-2379fb80-d59d-11ea-8e66-2e6e69052686.png)
![image](https://user-images.githubusercontent.com/65810411/89170416-38ef2580-d59d-11ea-89e7-2729d1f2f44f.png)

when I refer the API documentation, Notification ARN is only meant for MNS. How do I update my template to run linux commands while scale-out

**Comment by night556** [comment]
Note that the displayed version is 3.0.42, please try upgrading to the latest version.
