### ISSUE TITLE
Building on armv7hl/armv7l fails from running out of memory

### ISSUE THREAD

**Issue by bdperkin** [aliyun/aliyun-cli#303]
The go compiler is running out of memory when trying to compile on armv7hl/armv7l.  This does not occur on any other architecture we build for (including aarch64).  This problem has been verified on multiple builders, but a minimal reproducer is described below:

System information:
Fedora release 33 (Rawhide)
Linux localhost.localdomain 5.8.0-1.fc33.armv7hl #1 SMP Mon Aug 3 17:04:56 UTC 2020 armv7l armv7l armv7l GNU/Linux
CPU: 2-core ARMv7 Processor rev 1 (v7l) Generic DT based system
Memory: 2.0Gi with 1.0Gi swap

Compiler information:
golang version go1.15rc1

Identical OS and compiler were used across all supported architectures (armv7hl, i686, x86_64, aarch64, ppc64le, s390x) to build Release version v3.0.55.

The error *appears* to be related to the size of resource/metas.go and that resource/reader.go loads the entire file into memory.  The output from my last session is as follows:

    ========================================
    [mockbuild@localhost aliyun-cli]$ go build -v -x -ldflags "-X 'github.com/aliyun/aliyun-cli/cli.Version=3.0.55'" -o out/aliyun main/main.go
    WORK=/tmp/go-build646246227
    github.com/aliyun/aliyun-cli/resource
    mkdir -p $WORK/b136/
    cat >$WORK/b136/importcfg << 'EOF' # internal
    # import config
    packagefile bytes=/usr/lib/golang/pkg/linux_arm/bytes.a
    packagefile compress/gzip=/usr/lib/golang/pkg/linux_arm/compress/gzip.a
    packagefile fmt=/usr/lib/golang/pkg/linux_arm/fmt.a
    packagefile io=/usr/lib/golang/pkg/linux_arm/io.a
    packagefile io/ioutil=/usr/lib/golang/pkg/linux_arm/io/ioutil.a
    packagefile os=/usr/lib/golang/pkg/linux_arm/os.a
    packagefile path/filepath=/usr/lib/golang/pkg/linux_arm/path/filepath.a
    packagefile strings=/usr/lib/golang/pkg/linux_arm/strings.a
    packagefile time=/usr/lib/golang/pkg/linux_arm/time.a
    EOF
    cd /home/mockbuild/git/aliyun-cli/resource
    /usr/lib/golang/pkg/tool/linux_arm/compile -o $WORK/b136/_pkg_.a -trimpath "$WORK/b136=>" -p github.com/aliyun/aliyun-cli/resource -lang=go1.12 -complete -buildid UZO09d5_Vh3sJuwzBCNN/UZO09d5_Vh3sJuwzBCNN -goversion go1.15rc1 -D "" -importcfg $WORK/b136/importcfg -pack -c=2 ./metas.go ./reader.go
    go build github.com/aliyun/aliyun-cli/resource: /usr/lib/golang/pkg/tool/linux_arm/compile: signal: killed
    ========================================

I verified that the OOM error is directly related to the size of metas.go by bisecting aliyun-openapi-meta down to b82138aed7872cca0030bd5affbede65f9effda5 that fails and 4d5be39cdffa25ff00ffb9263bc4d8f9890fb936 that works.  I don't think the issue has anything to do with this particular commit at all and more to do with the resources available on the building machine.  In my testing of different versions of metas.go I found that 21,445,265 bytes (140,802 lines) or less work and 21,628,043 bytes (143,310 lines) or more fail.  This was across seven tests with four failures and three successes.

We are unable to increase the resources on our builder machines, but more to the point, we don't believe it should take over 1.5Gi to compile the aliyun CLI.  I'm not familiar enough with the code to provide a suggestion on a fix.  But, my general thought is that there should be a way to re-architect this such that the metadata does not have to be entirely loaded into memory.  As the metadata continues to grow, this problem will continue to get worse and likely become a problem on another platform.

Please reach out if you need additional information (or more details on the reproducer).

Thanks!

**Comment by night556** [comment]
Golang compilation itself consumes a lot of memory, and we still cannot solve this problem on the current CLI.
You can try to increase the swap size to solve the problem of insufficient memory.
