### ISSUE TITLE
Bug report: DescribeCdnDomainConfigs --FunctionNames is not required

### ISSUE THREAD

**Issue by wi1dcard** [aliyun/aliyun-cli#307]
* **Command Format**:

```
aliyun cdn DescribeCdnDomainConfigs --DomainName ...
```

* **Execution Command**:

Not relevant.

* **Output**:

```
ERROR: required parameters not assigned:
  --FunctionNames

See https://help.aliyun.com/api/cdn/DescribeCdnDomainConfigs.html or use `aliyun cdn DescribeCdnDomainConfigs --help` to get more information
```

It seems the parameter `FunctionName` is not required: <https://www.alibabacloud.com/help/zh/doc-detail/90924.htm>. This can also be verified using Aliyun OpenAPI Explorer.

**Comment by night556** [comment]
The data obtained by the CLI is displayed as necessary, you can ask the product side.

**Comment by wi1dcard** [comment]
I'm sorry but what do you mean "as necessary"? How can I ask the customer support for this issue? Where are the "data" obtained from?

**Comment by night556** [comment]
The data is automatically generated. You can get the generated data at github.com/aliyun/aliyun-openapi-meta. As for the data is inaccurate, we will communicate this internally.

**Comment by wenzuochao** [comment]
The code is automatically generated according to the [meta](https://github.com/aliyun/aliyun-openapi-meta/blob/master/cdn/DescribeCdnDomainConfigs.json#L20).

**Comment by JacksonTian** [comment]
$ aliyun cdn DescribeCdnDomainConfigs --help
Alibaba Cloud Command Line Interface Version 3.0.91

Product: Cdn (Alibaba Cloud CDN)

Parameters:
  --DomainName    String  Required 
  --ConfigId      String  Optional 
  --FunctionNames String  Optional 
  --SecurityToken String  Optional 

It's ok now.
