### ISSUE TITLE
The latest version v3.0.58 is not available on Homebrew

### ISSUE THREAD

**Issue by wi1dcard** [aliyun/aliyun-cli#308]
* **Command Format**:

N/A

* **Execution Command**:

N/A

* **Output**:

N/A

The latest version on Homebrew and GitHub releases is still v3.0.56. And there seems no code change between [v3.0.56...master](https://github.com/aliyun/aliyun-cli/compare/v3.0.56...master).

**Comment by night556** [comment]
The code has not changed, but the referenced external data has changed, so a new release.

**Comment by wi1dcard** [comment]
Thanks! So when can we get the latest release on Homebrew?

**Comment by night556** [comment]
We will deal with homebrew here, and the latest can be downloaded from the official website temporarily.

**Comment by wenzuochao** [comment]
You can get the latest release on Homebrew now. Thanks for your support to our project.
