### ISSUE TITLE
--ram-role-name 参数 3.0.58版本不可用

### ISSUE THREAD

**Issue by geeklenny** [aliyun/aliyun-cli#309]
./aliyun cr GET /tokens --region cn-hangzhou --endpoint cr.cn-hangzhou.aliyuncs.com --ram-role-name docker-loader

ERROR: invalid access_key_id:

3.0.20版本正常

**Comment by night556** [comment]
默认凭证方式是ak，我看后面加了 --ram-role-name 选项，这个应当是RamRoleArn形式的，可以试试加上 --mode RamRoleArn

**Comment by night556** [comment]
另外可以使用 aliyun configure get 看看当前默认配置是什么
