### ISSUE TITLE
v3.0.63 和 v3.0.64 Linux 二进制执行错误

### ISSUE THREAD

**Issue by ist0ne** [aliyun/aliyun-cli#319]
```
# wget https://github.com/aliyun/aliyun-cli/releases/download/v3.0.62/aliyun-cli-linux-3.0.64-amd64.tgz
# tar xzvf aliyun-cli-linux-3.0.64-amd64.tgz
# ./aliyun -h
sh: ./aliyun: not found
```

**Comment by night556** [comment]
这貌似并不是执行错误，而是没找到该二进制文件。

**Comment by c521wy** [comment]
![image](https://user-images.githubusercontent.com/4578684/104114113-9309c900-533b-11eb-8412-5ca3456125e5.png)
看看这文件找的到不

**Comment by c521wy** [comment]
try add a link
![image](https://user-images.githubusercontent.com/4578684/104114257-34dde580-533d-11eb-8a62-03e843ab10a6.png)
