### ISSUE TITLE
Feature Request: Add option to AuthorizeSecurityGroup by Security Group Name

### ISSUE THREAD

**Issue by i420bdawg** [aliyun/aliyun-cli#32]
I would like to see the option to be able to add a rule to Security Groups both Ingress and Egress where only the names of the security groups are provided.   This will help in setting up automation scripts.

**Comment by jumping** [comment]
This tool has this function, you can run "aliyun ecs AuthorizeSecurityGroup xxxxx"

**Comment by i420bdawg** [comment]
No it requires security group id of the rule you are adding, not name

Eg if i want to allow port 443 to all instances in the testsg to goto testdestsg i cannot specify  both testsg and testdestsg by name in the command.

**Comment by night556** [comment]
> No it requires security group id of the rule you are adding, not name
> 
> Eg if i want to allow port 443 to all instances in the testsg to goto testdestsg i cannot specify both testsg and testdestsg by name in the command.

Hi，CLI Project  just calls the API provided by the product side，so if you want to be able to add a rule to Security Groups by name, We recommend that you Communicate with the product team.
If there is no follow-up reply, we will close this issue after February 22, 2019.
Thank you for your attention to AliCloud CLI Project！
