### ISSUE TITLE
建议给 aliyun oss 添加 sync 指令

### ISSUE THREAD

**Issue by Spinestars** [aliyun/aliyun-cli#321]
* **需求类型**:
增加 aliyun oss sync ，目前 aliyun oss 不支持同步。
-u 参数虽然可以支持升级上传，但是却无法将目的端存在而源端不存在的文件都删除
---
root@ip: /backup# aliyun oss sync
ERROR: 'sync' is not a vaild command

* **需求描述**:

建议加入 sync 指令，这是一个非常常见的需求。
就如同 ossutil 里文档描述的那样
https://help.aliyun.com/document_detail/193394.html?spm=a2c4g.11186623.6.889.1fc871009bgGtd

* **设计方案**:

**Comment by night556** [comment]
针对于oss的操作，这边建议您使用ossutil进行操作，cli暂时无法保证即时的功能同步。

**Comment by Spinestars** [comment]
> 针对于oss的操作，这边建议您使用ossutil进行操作，cli暂时无法保证即时的功能同步。

额，这真是一个令人沮丧的回应。
虽然我会选择用 ossutil 去实现需求，但是之所以选择 aliyun cli 就是因为它可以一统所有的产品，还是希望能尽快的支持。

**Comment by wenzuochao** [comment]
这个我们这边目前还没有支持计划，如果您没有其他问题的话，我这边先关闭这个 issue。感谢您对我们项目的支持。
