### ISSUE TITLE
Cannot create table store instance

### ISSUE THREAD

**Issue by nlamirault** [aliyun/aliyun-cli#322]
I can't create table store instance using the CLI.

* **Command Format**: `aliyun ots InsertInstance`

* **Execution Command**: `aliyun ots InsertInstance --InstanceName tfstates --profile myprofile --region eu-central-1 --Description "Instance for Terraform" --endpoint ots.eu-central-1.aliyuncs.com`

* **Output**:

```
ERROR: SDK.ServerError
ErrorCode: NotFound
Recommend: https://error-center.aliyun.com/status/search?Keyword=NotFound&source=PopGw
RequestId: C1B0704E-96E9-4947-9F0C-47A932F002B0
Message: Primary cluster does not exist
```

**Comment by night556** [comment]
Please try with the latest version.
```sh
aliyun ots InsertInstance help
Alibaba Cloud Command Line Interface Version 3.0.62

Product: Ots (Table Store)

Parameters:
  --InstanceName       String  Required 
  --AccessKeyId        String  Optional 
  --ClusterType        String  Optional 
  --Description        String  Optional 
  --Network            String  Optional 
  --TagInfo.n.TagKey   String  Required 
  --TagInfo.n.TagValue String  Required 
```

**Comment by nlamirault** [comment]
I'm using the 3.0.65 : 

```
❯ aliyun
Alibaba Cloud Command Line Interface Version 3.0.65
```

**Comment by wenzuochao** [comment]
You can submit a ticket [here](https://ia.aliyun.com/home?channel=ticket&mark=console-home).

**Comment by JacksonTian** [comment]
It's seems ok:

$ aliyun ots help
Alibaba Cloud Command Line Interface Version 3.0.91

Usage:
  aliyun Ots <ApiName> --parameter1 value1 --parameter2 value2 ...

Product: Ots (Table Store)
Version: 2016-06-20 

Available Api List: 
  BindInstance2Vpc
  DeleteInstance
  DeleteTags
  GetInstance
  InsertInstance
  InsertTags
  ListClusterType
  ListInstance
  ListTags
  ListVpcInfoByInstance
  ListVpcInfoByVpc
  OpenOtsService
  UnbindInstance2Vpc
  UpdateInstance

Run `aliyun ots <ApiName> --help` to get more information about this API
