### ISSUE TITLE
error on cli commands with latest release 3.0.67

### ISSUE THREAD

**Issue by agorti** [aliyun/aliyun-cli#324]
I'm getting an error with the latest build 3.0.67 while running aliyun command. working as expected for 3.0.66

* **Command Format**:
aliyun version

* **Execution Command**:
aliyun version
* **Output**: 
panic: read json from products.json failed &{[]}

goroutine 1 [running]:
github.com/aliyun/aliyun-cli/meta.LoadRepository(0x11cba60, 0x1d93c30, 0xc00000f9c0)
        /root/aliyun-cli/meta/repository.go:35 +0x616
github.com/aliyun/aliyun-cli/openapi.NewLibrary(...)
        /root/aliyun-cli/openapi/library.go:38
github.com/aliyun/aliyun-cli/openapi.NewCommando(0x11cc8e0, 0xc000010020, 0xfbbb96, 0x7, 0xfb983b, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        /root/aliyun-cli/openapi/commando.go:45 +0xa2
main.main()
        /root/aliyun-cli/main/main.go:77 +0x404

* **Expected Output**: 
3.0.67

**Comment by wenzuochao** [comment]
I‘m sorry for that. You can use 3.0.66 instead. I will fix it as soon as possible.

**Comment by wenzuochao** [comment]
You will use the 3.0.68 instead of 3.0.67.

**Comment by frenchvandal** [comment]
3.0.69 is working fine for me.

**Comment by JacksonTian** [comment]
Thanks @frenchvandal @agorti . I closed this issue, if any questions,  feel free to re-open or submit another issue.
