### ISSUE TITLE
Upgrade OSSUTIL to 1.7.1

### ISSUE THREAD

**Issue by frenchvandal** [aliyun/aliyun-cli#326]
嗨，大家好！

* **Type of Demand**:
update request

* **Detailed Description**:
`OSSUTIL` used in Aliyun CLI is currently 1.6.11.
```
2021/01/27 06:28:40 [info]ossutil version is v1.6.11
2021/01/27 06:28:40 [info]oss go sdk version is v2.0.8
2021/01/27 06:28:40 [info]go version is go1.14.8
```

* **Design**:
Are there any plans to keep `Aliyun CLI` up-to-date with `OSSUTIL` upstream? Latest version is 1.7.1.

**Comment by wenzuochao** [comment]
It's not necessary for us to update the latest dependencies. The cli has so many dependencies. If we always update cli when the dependencies updated,  this will be updated too frequently。

**Comment by frenchvandal** [comment]
Sure, I understand your concern.

My issue is just that Aliyun CLI not offer the `sync` command for oss component because this was implemented in OSSUTIL v1.7.0. Are you scheduling a one-shot update anytime soon?

**Comment by wenzuochao** [comment]
So far we have no upgrade plan. If you want to use sync command for OSS, we recommend you to use `ossutil` for operation. Cli cannot guarantee instant synchronization for the time being.

**Comment by frenchvandal** [comment]
Sure, of course.
趙文卓谢谢你抽出宝贵时间教我
