### ISSUE TITLE
Will Aliyun CLI be deprecated?

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#327]
With https://github.com/aliyun/alibabacloud-resourcify-cli now being developed what is the roadmap and strategy for our CLI tools? Will Aliyun CLI be deprecated? For example `aliyun cs DescribeCluster` does not work against Container Service anymore.

**Comment by aschleifer** [comment]
Executing said command against a cluster will return this:

```
ERROR: product 'cs' need restful call

Use `aliyun cs {GET|PUT|POST|DELETE} <path> ...`
```

**Comment by JacksonTian** [comment]
The answer is NO. we will support Aliyun CLI and ARC both.
