### ISSUE TITLE
Feature Request: Add option to pass Description for Security Group Rules via CLI

### ISSUE THREAD

**Issue by i420bdawg** [aliyun/aliyun-cli#33]
I would like to see the option to pass the description parameter through the CLI for ECS AuthorizeSecurityGroup and AuthorizeSecurityGroupEgress. the current SDK Supports this however, I am not sure how to edit the CLI to incorporate it.

**Comment by night556** [comment]
> I would like to see the option to pass the description parameter through the CLI for ECS AuthorizeSecurityGroup and AuthorizeSecurityGroupEgress. the current SDK Supports this however, I am not sure how to edit the CLI to incorporate it.

Hi, this issue has been around for a long time now, we don't know the follow-up situation. And if you have any questions, please contact us.
Thank you for your attention to AliCloud CLI Project.
