### ISSUE TITLE
No support for aliyun cs ListRepoSyncTask

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#331]
* **Type of Demand**:
Aliyun CLI does not support `aliyun cs ListRepoSyncTask` (see output below).
```
╰─ aliyun cr ListRepoSyncTask     
ERROR: product 'cr' need restful call
Use `aliyun cr {GET|PUT|POST|DELETE} <path> ...`
```
This API is documented at https://www.alibabacloud.com/help/doc-detail/145283.htm

Also, there is no documented way to use the restful interface such as `aliyun cr GET <path>` to get call ListRepoSyncTask.

**Comment by aschleifer** [comment]
@JacksonTian it would be nice if you mention in which version of the cli this has been fixed.

**Comment by JacksonTian** [comment]
The latest version(v3.0.137) has supported it.
