### ISSUE TITLE
arm架构的能不能发一下？python3的能不能更新一下？

### ISSUE THREAD

**Issue by csqmdx** [aliyun/aliyun-cli#335]
python用不了，arm的也没有。
其他网站提供的arm以及arm64不能用。配置都没法完成。

**Comment by JacksonTian** [comment]
Python 的 CLI 版本已经不再支持了。

**Comment by JacksonTian** [comment]
arm64 是 linux 的吧？

**Comment by manjoc** [comment]
自己编译吧

**Comment by JacksonTian** [comment]
3.0.91 版本开始，支持 ARM 版本下载了。地址请访问： https://github.com/aliyun/aliyun-cli#installation
