### ISSUE TITLE
Document Improvement: aliyuncli ecs CreateInstance documentation

### ISSUE THREAD

**Issue by xuyuji9000** [aliyun/aliyun-cli#34]
Documentation of creating instance should be more detailed for the sake of the usability of this sub-command.

No successful demo of what a right CreateInstances should be like make the process of test command fail and retry painful.

**Comment by night556** [comment]
> Documentation of creating instance should be more detailed for the sake of the usability of this sub-command.
> 
> No successful demo of what a right CreateInstances should be like make the process of test command fail and retry painful.

Hi, this issue has been around for a long time now, we suggest you uptate to the lastest version of CLI and try again. If you have any questions, please contact us.
Thank you for your attention to AliCloud CLI Project.
