### ISSUE TITLE
test case panic

### ISSUE THREAD

**Issue by geliwei** [aliyun/aliyun-cli#347]
* **Command Format**:
go-compilers-golang-compiler  x86_64  1-20.1.al7
go-srpm-macros                noarch  2-17.1.al7
golang                        x86_64  1.14.3-1.1.al7
json-c                        x86_64  0.11-4.1.al7

* **Execution Command**:
* + cd /builddir/build/BUILD
+ cd /builddir/build/BUILD/aliyun-cli-3.0.74/src/github.com/aliyun
+ export GOROOT=/usr/lib/golang/
+ GOROOT=/usr/lib/golang/
+ export GOPATH=/builddir/build/BUILD/aliyun-cli-3.0.74
+ GOPATH=/builddir/build/BUILD/aliyun-cli-3.0.74
+ export GOPROXY=https://mirrors.aliyun.com/goproxy,direct
+ GOPROXY=https://mirrors.aliyun.com/goproxy,direct
+ sed -i s#./oss/...## aliyun-cli/Makefile
+ sed -i 's/go test/go test -v/' aliyun-cli/Makefile
+ cd aliyun-cli
+ make -j32 test

* **Output**:
PASS
coverage: 95.8% of statements
ok  	github.com/aliyun/aliyun-cli/i18n	0.033s	coverage: 95.8% of statements
?   	github.com/aliyun/aliyun-cli/main	[no test files]
=== RUN   Test_main
--- FAIL: Test_main (0.00s)
panic: read json from products.json failed &{[]} [recovered]
	panic: read json from products.json failed &{[]}
goroutine 19 [running]:
testing.tRunner.func1.1(0xb5e380, 0xc00019b720)
	/usr/lib/golang/src/testing/testing.go:940 +0x421
testing.tRunner.func1(0xc0001df8c0)
	/usr/lib/golang/src/testing/testing.go:943 +0x600
panic(0xb5e380, 0xc00019b720)
	/usr/lib/golang/src/runtime/panic.go:975 +0x3e3
github.com/aliyun/aliyun-cli/meta.LoadRepository(0xce6d60, 0x111fae0, 0x1)
	/builddir/build/BUILD/aliyun-cli-3.0.74/src/github.com/aliyun/aliyun-cli/meta/repository.go:35 +0x89c
github.com/aliyun/aliyun-cli/openapi.NewLibrary(0xce6820, 0xc000212ab0, 0xbf020d, 0x2, 0x40)
	/builddir/build/BUILD/aliyun-cli-3.0.74/src/github.com/aliyun/aliyun-cli/openapi/library.go:38 +0x63
github.com/aliyun/aliyun-cli/openapi.NewCommando(0xce6820, 0xc000212ab0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/aliyun-cli-3.0.74/src/github.com/aliyun/aliyun-cli/openapi/commando.go:45 +0x11e
github.com/aliyun/aliyun-cli/openapi.Test_main(0xc0001df8c0)
	/builddir/build/BUILD/aliyun-cli-3.0.74/src/github.com/aliyun/aliyun-cli/openapi/commando_test.go:37 +0x2b5
testing.tRunner(0xc0001df8c0, 0xc2c380)
	/usr/lib/golang/src/testing/testing.go:991 +0x1ec
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1042 +0x661
FAIL	github.com/aliyun/aliyun-cli/openapi	0.021s
?   	github.com/aliyun/aliyun-cli/resource	[no test files]
FAIL
make: *** [test] Error 1

**Comment by JacksonTian** [comment]
拉下更新的代码

**Comment by JacksonTian** [comment]
这个报错是因为 meta 仓库是一个 git sub module，跑测试前，需要同步它先。
