### ISSUE TITLE
aliyun cli latest is not working in docker:404

### ISSUE THREAD

**Issue by adityahegde007** [aliyun/aliyun-cli#351]
Create docker image for cli
* **Command Format**: 
FROM alpine:latest
RUN apk add --no-cache jq
RUN wget https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
RUN tar -xvzf aliyun-cli-linux-latest-amd64.tgz
RUN rm aliyun-cli-linux-latest-amd64.tgz
RUN mv aliyun /usr/local/bin/

* **Execution Command**:
run docker and connect to it. Execute "aliyun" command
* **Output**:
#aliyun not found

Working until version v3.0.69 but not after that

docker run -it -d -–name aliyuncli aliyuncli
docker exec -it aliyuncli /bin/sh
#aliyun

**Comment by hayorov** [comment]
Hello @adityahegde007 ,

The output "X not found" is about missed dynamically linked library. (Probably the most confusing and ambiguous error message).

run `ldd aliyun` to get more diagnostics.

## The solution
For alpine add this into your Dockerfile
```
RUN apk add --no-cache libc6-compat musl
```

**Comment by JacksonTian** [comment]
@adityahegde007 Have your problem was resolved?
