### ISSUE TITLE
about docker related issue

### ISSUE THREAD

**Issue by opera443399** [aliyun/aliyun-cli#36]
1、因为阿里云的客服系统让我困惑，效率不高，我选择在github找找有没有地方提交问题反馈。
2、问题描述
我的 docker node 使用了[Docker Hub 镜像站点](https://cr.console.aliyun.com/#/accelerator)，然后发现一个问题：

````bash
~]$ sudo cat /etc/docker/daemon.json |grep registry
  "registry-mirrors": ["https://zvz7k9mh.mirror.aliyuncs.com"]

~]$ sudo docker pull opera443399/whoami
Using default tag: latest
latest: Pulling from opera443399/whoami
Digest: sha256:4119c322c2d9f007af8751394a63ed6809158bc39456e6aa60ab84e7a21429c5
Status: Image is up to date for opera443399/whoami:latest

~]$ sudo docker images |grep opera
opera443399/whoami         latest              160ed79ce86f        5 weeks ago         4.13MB
````

实际上，上述拉取到的是一个旧的版本 160ed79ce86f   

> 对比下面操作中另一个节点的状态（没有使用加速镜像）
````bash
~]$ sudo docker pull opera443399/whoami
Using default tag: latest
latest: Pulling from opera443399/whoami
Digest: sha256:a05120d9fe157868f7f1c8b842cc860fb58665d74cadaf8eb7d6091af626cccd
Status: Downloaded newer image for opera443399/whoami:latest

~]$ sudo docker images |grep opera
opera443399/whoami          0.9                  a7878d3e0fdf        20 hours ago        4.13MB
opera443399/whoami          latest               a7878d3e0fdf        20 hours ago        4.13MB
opera443399/whoami          0.8                  ae008c956c53        3 weeks ago         4.13MB
opera443399/whoami          0.7                  160ed79ce86f        5 weeks ago         4.13MB

````

小结：使用阿里云的容器服务中的 Docker Hub 镜像站点后，缓存的 latest 这个 tag 是旧版本，且过了好几天还没有刷新，这个问题怎么解决？

感谢您查看，希望能帮助反馈问题。

**Comment by zeyuye-airwallex** [comment]
以上终端显示，拉取的是
```
Digest: sha256:a05120d9fe157868f7f1c8b842cc860fb58665d74cadaf8eb7d6091af626cccd
```

这个和 160ed79ce86f 因该不是一样的吧， 要确保你的新版本push了

**Comment by opera443399** [comment]
@zeyuye-airwallex 
hi, 正是因为版本不一样才有问题呀，可能我之前描述的不够清楚。

> `Digest: sha256:a05120` -> 版本0.9 -> `a7878d3e0fdf`
> `Digest: sha256:4119c3` -> 版本0.7 -> `160ed79ce86f`

前文描述中，

第一段指令的含义是：通过阿里云镜像加速 pull `latest` 这个 tag  得到的版本是 0.7

第二段指令的含义是：作为对比，不通过镜像加速，直接 pull `latest` 这个 tag 得到的版本是 0.9（符合预期）

小结：阿里云加速镜像对 latest 这个 tag 而言，是不是缓存了旧版本？（当然，个人也不推荐在生产中用 latest，本文只是用来反馈可能存在的问题）

**Comment by night556** [comment]
> 1、因为阿里云的客服系统让我困惑，效率不高，我选择在github找找有没有地方提交问题反馈。
> 2、问题描述
> 我的 docker node 使用了[Docker Hub 镜像站点](https://cr.console.aliyun.com/#/accelerator)，然后发现一个问题：
> 
> ```shell
> ~]$ sudo cat /etc/docker/daemon.json |grep registry
>   "registry-mirrors": ["https://zvz7k9mh.mirror.aliyuncs.com"]
> 
> ~]$ sudo docker pull opera443399/whoami
> Using default tag: latest
> latest: Pulling from opera443399/whoami
> Digest: sha256:4119c322c2d9f007af8751394a63ed6809158bc39456e6aa60ab84e7a21429c5
> Status: Image is up to date for opera443399/whoami:latest
> 
> ~]$ sudo docker images |grep opera
> opera443399/whoami         latest              160ed79ce86f        5 weeks ago         4.13MB
> ```
> 
> 实际上，上述拉取到的是一个旧的版本 160ed79ce86f
> 
> > 对比下面操作中另一个节点的状态（没有使用加速镜像）
> 
> ```shell
> ~]$ sudo docker pull opera443399/whoami
> Using default tag: latest
> latest: Pulling from opera443399/whoami
> Digest: sha256:a05120d9fe157868f7f1c8b842cc860fb58665d74cadaf8eb7d6091af626cccd
> Status: Downloaded newer image for opera443399/whoami:latest
> 
> ~]$ sudo docker images |grep opera
> opera443399/whoami          0.9                  a7878d3e0fdf        20 hours ago        4.13MB
> opera443399/whoami          latest               a7878d3e0fdf        20 hours ago        4.13MB
> opera443399/whoami          0.8                  ae008c956c53        3 weeks ago         4.13MB
> opera443399/whoami          0.7                  160ed79ce86f        5 weeks ago         4.13MB
> ```
> 
> 小结：使用阿里云的容器服务中的 Docker Hub 镜像站点后，缓存的 latest 这个 tag 是旧版本，且过了好几天还没有刷新，这个问题怎么解决？
> 
> 感谢您查看，希望能帮助反馈问题。

Hi, here is the AliCloud CLI project, I see that your problem is not our project bussiness and it's been a long time since you asked this question, so considering these, we'll close the issue.
Thank you for your attention to AliCloud CLI Project！
