### ISSUE TITLE
3.0.74 - 3.0.80 编译成的镜像 运行全部错误 3.0.73以下是OK的

### ISSUE THREAD

**Issue by aikin-vip** [aliyun/aliyun-cli#364]
错误:
![image](https://user-images.githubusercontent.com/64122272/124214564-ffb09400-db24-11eb-81e3-654a6893ef2d.png)
正常：
![image](https://user-images.githubusercontent.com/64122272/124214638-1e168f80-db25-11eb-81cb-48c0f3f2d6d6.png)

Dockerfile: [https://gitlab.com/ruben-funai/aliyun-cli-docker/-/blob/master/arm64v8.Dockerfile](https://gitlab.com/ruben-funai/aliyun-cli-docker/-/blob/master/arm64v8.Dockerfile)

Dokcer镜像地址: [https://hub.docker.com/r/rubenfunai/aliyun-cli](https://hub.docker.com/r/rubenfunai/aliyun-cli)

**Comment by JacksonTian** [comment]
这是自己编译的吗

**Comment by JacksonTian** [comment]
You should run `git submodule update` before compile it.
