### ISSUE TITLE
Container Service: Regional endpoint is not selected

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#368]
Hi--, 

the regional endpoint of container service is not correctly selected based on the `--region` parameter.

For example, if you call

`$ aliyun cs DescribeClusters --region="eu-central-1`

the endpoint selected is `https://cs.aliyuncs.com/clusters` which is not correct. It should be `https://cs.eu-central-1.aliyuncs.com/clusters`

This needs to be fixed, because cs.aliyuncs.com resolves to an IP in Mainland China which sometimes results on connection resets when called from outside of Mainland China. Thanks.

**Comment by JacksonTian** [comment]
Please use like this: `aliyun cs DescribeClusters --endpoint=cs.eu-central-1.aliyuncs.com`

**Comment by arafato** [comment]
The workaround suggested works but it would be great if the `--endpoint` flag was not needed at all. The CLI should select the right endpoint automatically based on the `--region` flag. This is the convention that all other services also follow.

**Comment by JacksonTian** [comment]
We will use regional endpoint for avoid connection reset.

**Comment by JacksonTian** [comment]
The 3.0.82 fixed it.
