### ISSUE TITLE
aliyuncli configure 是否支持非交互式配置？

### ISSUE THREAD

**Issue by leo108** [aliyun/aliyun-cli#37]
我们需要在docker中通过脚本去调用aliyuncli，能否通过类似`aliyuncli configure --id=xxx --key=xxx`的方式来配置？

**Comment by ailan-gl** [comment]
可以通过`aliyun configure set --profile xxx --access-key-id xxx --access-key-secret xxx` 进行配置

**Comment by zeyuye-airwallex** [comment]
@leo108 可以关了这issue, @ailan-gl 的提供了答案
