### ISSUE TITLE
Two "InstanceId" related issues found in DescribeInstances

### ISSUE THREAD

**Issue by SCHEN2015** [aliyun/aliyun-cli#38]
Issue 1: Multiple instances replied after I specify an InstanceId.
```
[aaa@aaa-laptop2 20171106_Aliyun_Performance_Testing]$ aliyuncli ecs DescribeInstances --InstanceId i-rj93nu0s9j3wkq0g0nif | grep InstanceId
                "InstanceId": "i-rj99hcysthbzoefu00yv", 
                "InstanceId": "i-rj93tjc72c6bib9ki4yt", 
                "InstanceId": "i-rj94xswj2tx5rrpeyj0i", 
                "InstanceId": "i-rj93nu0s9j3wkq0g0nif", 
                "InstanceId": "i-rj97tbgo9lk6vccplksp", 
                "InstanceId": "i-rj909znunwuzcw4yhqzo", 
```

Issue 2: "--InstanceIds" exists in the help page, but can't be used.
```
[aaa@aaa-laptop2 20171106_Aliyun_Performance_Testing]$ aliyuncli ecs DescribeInstances help | grep InstanceIds
--InstanceIds                            	| --InstanceName

[aaa@aaa-laptop2 20171106_Aliyun_Performance_Testing]$ aliyuncli ecs DescribeInstances --InstanceIds i-rj93nu0s9j3wkq0g0nif
    "Message": "The specified parameter \"InstanceIds\" is not valid.", 
    ......
```

**Comment by SCHEN2015** [comment]
https://github.com/aliyun/aliyun-openapi-python-sdk/issues/44

**Comment by night556** [comment]
> Issue 1: Multiple instances replied after I specify an InstanceId.
> 
> ```
> [aaa@aaa-laptop2 20171106_Aliyun_Performance_Testing]$ aliyuncli ecs DescribeInstances --InstanceId i-rj93nu0s9j3wkq0g0nif | grep InstanceId
>                 "InstanceId": "i-rj99hcysthbzoefu00yv", 
>                 "InstanceId": "i-rj93tjc72c6bib9ki4yt", 
>                 "InstanceId": "i-rj94xswj2tx5rrpeyj0i", 
>                 "InstanceId": "i-rj93nu0s9j3wkq0g0nif", 
>                 "InstanceId": "i-rj97tbgo9lk6vccplksp", 
>                 "InstanceId": "i-rj909znunwuzcw4yhqzo", 
> ```
> Issue 2: "--InstanceIds" exists in the help page, but can't be used.
> 
> ```
> [aaa@aaa-laptop2 20171106_Aliyun_Performance_Testing]$ aliyuncli ecs DescribeInstances help | grep InstanceIds
> --InstanceIds                            	| --InstanceName
> 
> [aaa@aaa-laptop2 20171106_Aliyun_Performance_Testing]$ aliyuncli ecs DescribeInstances --InstanceIds i-rj93nu0s9j3wkq0g0nif
>     "Message": "The specified parameter \"InstanceIds\" is not valid.", 
>     ......
> ```

Hi, this issue has been around for a long time now, we suggest you uptate to the lastest version of CLI and try again. If you have any questions, please contact us. 
Thank you for your attention to AliCloud CLI Project.

**Comment by zot11** [comment]
I downloaded last version and still have this problem:
Message: The specified parameter "InstanceIds" is not valid.

**Comment by zot11** [comment]
Ok. I know answer. You should write \" to get result. My example is: aliyun ecs DescribeInstances --InstanceIds [\"i-***\",\"i-***\"] --profile default

**Comment by night556** [comment]
> Ok. I know answer. You should write " to get result. My example is: aliyun ecs DescribeInstances --InstanceIds ["i-***","i-***"] --profile default

I am very glad that your problem has been solved, and when you use a flag with value is json string, we recommend that you wrap this string in double quotes, and enclose the value inside with single quotes. Like this `"['i-***','i-***']"`.
Thank you for your attention to AliCloud CLI Project!
