### ISSUE TITLE
cs DescribeClusterAddonsUpgradeStatus doesn't work

### ISSUE THREAD

**Issue by aschleifer** [aliyun/aliyun-cli#380]
according to the [api documentation](https://www.alibabacloud.com/help/doc-detail/184635.htm?spm=a2c63.p38356.b99.1005.f0e57df86WoSq0) the call for to describ cluster addon upgrades requires one parameter, the `ClusterId` and has an optional parameter `componentIds` where you can give a list of components you want to filter the result for.

When I try to do this call with the CLI i get this error:

```
╰─ aliyun cs DescribeClusterAddonsUpgradeStatus --ClusterId c274546a0baea4b8291aeefa92a20186b
ERROR: SDK.ServerError
ErrorCode:
Recommend:
RequestId:
Message: {"code":"400","message":"Missing_params_componentIds","requestId":"895E8338-703D-344F-9720-A1E5BE165C32","status":400}
```
Stating that the `compnentIds` parameter is missing. However when I look at the help for this CLI call:

```
╰─ aliyun help cs DescribeClusterAddonsUpgradeStatus
Alibaba Cloud Command Line Interface Version 3.0.90

Product:     CS (Container Service)
Method:      GET
PathPattern: /clusters/[ClusterId]/components/upgradestatus

Parameters:
  --ClusterId String  Required
```

The parameter is not listed. Also when I then try to call it with componentIds I get an error aswell:
```
╰─ aliyun cs DescribeClusterAddonsUpgradeStatus --ClusterId c274546a0baea4b8291aeefa92a20186b --componentIds '["terway-eniip"]'
ERROR: '--componentIds' is not a valid parameter or flag. See `aliyun help cs DescribeClusterAddonsUpgradeStatus`.
```

How is this suppose to work?

**Comment by peze** [comment]
this is a restful api, so you should use it like this eg. 

>  aliyun cs GET  /clusters/[ClusterId]/components/upgradestatus?componentIds=["String"] 

if it's a post method api , you should use it like this:

> aliyun cs  POST /clusters/<cluster_id>/attach --header "Content-Type=application/json" --body "$(cat attach.json)"

**Comment by arafato** [comment]
@peze please re-open this ticket again. It is still not working with these commands.
@aschleifer please post the output for validation.

**Comment by aschleifer** [comment]
So the API documentation ( https://www.alibabacloud.com/help/doc-detail/184635.htm?spm=a2c63.p38356.b99.1005.f0e57df86WoSq0 ) says that `componentIds` is deprecated but even the openapi debug website says it is required.

Further more i tried this:
```
╰─ aliyun cs GET '/clusters/c274546a0baea4b8291aeefa92a20186b/components/upgradestatus?componentIds=["csi-plugin"]'
ERROR: SDK.ServerError
ErrorCode: InvalidUrl
Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidUrl&source=PopGw
RequestId: 050A0E66-E8B9-3FF3-A99F-CD6185BC1465
Message: Request url is invalid, Illegal character in query at index 117: http://provision.cs.aliyun-inc.com/clusters/c274546a0baea4b8291aeefa92a20186b/components/upgradestatus?componentIds=["csi-plugin"]
```

When I use https://next.api.alibabacloud.com/api/CS/2015-12-15/DescribeClusterAddonsUpgradeStatus and add the values (clusterid, componentId) it actually works, so the API itself seems to work if you provide the components. But this doesn't show me how the call is done or how i have to escape the components list in the CLI call.

For a future improvement task it would be nicce if that website would give call examples for the aliyun-cli also.

**Comment by peze** [comment]
Remove single quotes，just use it like this:

> aliyun cs GET /clusters/c274546a0baea4b8291aeefa92a20186b/components/upgradestatus?componentIds=["csi-plugin"]

**Comment by aschleifer** [comment]
```
╰─ aliyun cs GET /clusters/c274546a0baea4b8291aeefa92a20186b/components/upgradestatus?componentIds=["csi-plugin"]
ERROR: SDK.ServerError
ErrorCode:
Recommend:
RequestId:
Message: {"code":"400","message":"InvalidParamType","requestId":"AAF2A374-2CD8-34F4-ADE9-C19539E7D422","status":400}
```

I tried that before and got this even stranger error.

**Comment by peze** [comment]
ok....please use it in this way:

> aliyun cs GET /clusters/c274546a0baea4b8291aeefa92a20186b/components/upgradestatus --componentIds '["aaaa"]'

**Comment by aschleifer** [comment]
That actually works. But it should really be documented somewhere. Also the upstream API docu is still wrong as it says the componentIds are optional.

I would like to have them optional and if you don't pass them you get the result for all currently installed addons.

**Comment by peze** [comment]
ok,i will feedback to the document engineer and the api developer.
