### ISSUE TITLE
aliyun sts GetCallerIdentity timeout

### ISSUE THREAD

**Issue by oort7** [aliyun/aliyun-cli#384]
* **Command Format**: `aliyun sts GetCallerIdentity`

* **Execution Command**: `aliyun sts GetCallerIdentity --region [MASKED] --access-key-id [MASKED] --access-key-secret [MASKED]`

* **Output**:
```
ERROR: Post https://sts.aliyuncs.com/?AccessKeyId=[MASKED]&Action=GetCallerIdentity&Format=JSON&RegionId=[MASKED]&Signature=[MASKED]&SignatureMethod=HMAC-SHA1&SignatureNonce=[MASKED]&SignatureType=&SignatureVersion=1.0&Timestamp=2021-09-23T08%3A39%3A21Z&Version=2015-04-01: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Failure rate: >50%
We are getting this error very often. Sometimes this command succeeds after 10 or more retries.

Aliyun cli version: latest (3.0.90)

**Comment by JacksonTian** [comment]
Where are your call from? The sts.aliyuncs.com is hosted mainland.

**Comment by JacksonTian** [comment]
```sh
aliyun | grep timeout
  --read-timeout       use `--read-timeout <seconds>` to set I/O timeout(seconds)
  --connect-timeout    use `--connect-timeout <seconds>` to set connect timeout(seconds)
```

You can use above timeout flags.

**Comment by oort7** [comment]
We are calling sts from servers located in Europe. If command works, it returns within a few seconds.
Unfortunately if there is a problem, setting timeouts even to 300 seconds doesn't help and we are getting this error.

**Comment by JacksonTian** [comment]
you can use `--sts-region` flag to specify a regional endpoint. e.g. 

```sh
aliyun sts GetCallerIdentity --sts-region eu-west-1  xxxx
```


<br class="Apple-interchange-newline">
