### ISSUE TITLE
目前release打包是自动的还是手动上传

### ISSUE THREAD

**Issue by cuisongliu** [aliyun/aliyun-cli#389]
* **需求类型**:
我看release还是手动打包的，没有自动化？这个是还没集成么还是有这块的需求必须手动？

* **需求描述**:

* **设计方案**:

**Comment by JacksonTian** [comment]
发布流程是自动化了的。因为涉及到手动编写 changelog 的原因，目前是自动化发布到 pre-release 的状态，然后完善 changelog，再正式发布。
