### ISSUE TITLE
AliyunCLI处理 DataDisk.n.Category 等带n的参数无法正常匹配set方法

### ISSUE THREAD

**Issue by huigher** [aliyun/aliyun-cli#39]
AliyunCLI处理 类似DataDisk.n.Category 的带“n”参数时，是去掉点号然后再从SDK源码中匹配对应的set规则，但是<class 'ImportImageRequest.ImportImageRequest'>中关于DiskDeviceMapping.1.OSSBucket 的set方法命名为'set_DiskDeviceMappings'，无法完整匹配“DiskDeviceMapping1OSSBucket”名称，其他的Action可能也存在类似的问题，请评估是否可以修正这个bug，谢谢

**Comment by night556** [comment]
> AliyunCLI处理 类似DataDisk.n.Category 的带“n”参数时，是去掉点号然后再从SDK源码中匹配对应的set规则，但是<class 'ImportImageRequest.ImportImageRequest'>中关于DiskDeviceMapping.1.OSSBucket 的set方法命名为'set_DiskDeviceMappings'，无法完整匹配“DiskDeviceMapping1OSSBucket”名称，其他的Action可能也存在类似的问题，请评估是否可以修正这个bug，谢谢

你好，现在CLI版本已经更新到3.0.9，我们建议您更新至最新版本，再次尝试运行命令，如果仍有问题，请提交完整的命令与输出以及必要的描述给我们。最后考虑到该issue的时间已经很久了，如果没有后续情况，我们将在2019.2.11号之后关闭该issue。
感谢你对 AliCloud CLI 项目的关注！
