### ISSUE TITLE
是否支持通过环境变量配置cli？

### ISSUE THREAD

**Issue by abcfy2** [aliyun/aliyun-cli#398]
* **需求类型**: 优化用户体验

* **需求描述**: 是否考虑支持环境变量配置CLI？这样安全性会更好一些，不会将敏感信息暴露在命令行上。比如aws cli就支持这种模式： https://docs.aws.amazon.com/zh_cn/cli/latest/userguide/cli-configure-envvars.html

* **设计方案**: 考虑支持环境变量注入的方式实现cli非交互式配置

**Comment by JacksonTian** [comment]
支持的环境变量有：
- ALIBABACLOUD_ACCESS_KEY_ID
- ALIBABACLOUD_ACCESS_KEY_SECRET
- SECURITY_TOKEN

需要注意，仅在未配置 profile 的情况下，环境变量会生效。

**Comment by abcfy2** [comment]
哦，知道了，谢谢。

能否更新下文档呢？ https://help.aliyun.com/document_detail/121259.html

官方文档并未提及可以使用环境变量配置凭证。谢谢
