### ISSUE TITLE
文档中自动补全说明

### ISSUE THREAD

**Issue by dxtywt** [aliyun/aliyun-cli#40]
自动补全功能:

阿里云命令行工具具备了命令行自动提示和补全的功能. 这个功能安装后不会默认打开, 需要您手动开启:
对于bash:

`$ complete -C '/usr/local/bin/aliyun_completer' aliyuncli`
执行报错：
```
[root@node01 ~]# aliyuncli -bash: /usr/local/bin/aliyun_completer: No such file or directory
-bash: /usr/local/bin/aliyun_completer: No such file or directory
```
执行 `complete -r aliyuncli` 解决报错，并替换新路径即可
实际安装，aliyun_completer 路径为 `/usr/bin/aliyun_completer`

**Comment by xdays** [comment]
哥们这个aliyun_completer是从哪个包里得来的？貌似现在这个仓库已经是go的了

**Comment by night556** [comment]
> 自动补全功能:
> 
> 阿里云命令行工具具备了命令行自动提示和补全的功能. 这个功能安装后不会默认打开, 需要您手动开启:
> 对于bash:
> 
> `$ complete -C '/usr/local/bin/aliyun_completer' aliyuncli`
> 执行报错：
> 
> ```
> [root@node01 ~]# aliyuncli -bash: /usr/local/bin/aliyun_completer: No such file or directory
> -bash: /usr/local/bin/aliyun_completer: No such file or directory
> ```
> 执行 `complete -r aliyuncli` 解决报错，并替换新路径即可
> 实际安装，aliyun_completer 路径为 `/usr/bin/aliyun_completer`

你好，现在阿里云命令行工具已经更新到3.0.9版本，如果希望开启自动提示和补全，可以使用 "aliyun  auto-completion"命令。
