### ISSUE TITLE
Provide a sha256 hash of the Aliyun binary for verification checking.

### ISSUE THREAD

**Issue by kwoodson** [aliyun/aliyun-cli#401]
* **需求类型**:

Feature/Enhancement

* **需求描述**:

I apologize as I cannot understand the Chinese in this template. My chrome browser will not translate the comments in the form.

When I browse here https://github.com/aliyun/aliyun-cli/releases/tag/v3.0.102 and look at the Assets I see the different binaries that I can download. I do not see a hash file so that I can compare the downloaded results with the original file posted. This is a security feature to ensure that the binary has not been modified during the download.

![image](https://user-images.githubusercontent.com/1385770/147111441-15ac59d9-e24b-46be-8c8f-38e1d64362cc.png)

Would it be possible to provide a hash file next to the download so I can download both the hash and the binary, perform the hash of the binary, and then compare the hashes to ensure the content?

* **设计方案**:

Please add an additional Asset file to the download Asset list that provides a hash file that includes the hash (generally sha256 or sha512) of the file.  Something simple like this should suffice:
```
sha256sum ~/bin/aliyun | cut -d" " -f1 > aliyun.sha256.txt
```

Please consider and thanks!

**Comment by JacksonTian** [comment]
Thanks for you idea.

**Comment by JacksonTian** [comment]
Thanks to @kwoodson , we supported it now.  https://github.com/aliyun/aliyun-cli/releases/tag/v3.0.107
