### ISSUE TITLE
Latest release does not include binaries

### ISSUE THREAD

**Issue by tech189** [aliyun/aliyun-cli#414]
The latest release (v3.0.113) on GitHub releases does not have any binaries in the Assets section: https://github.com/aliyun/aliyun-cli/releases/tag/v3.0.113

At the moment the only way to download the latest release is with this link: https://aliyuncli.alicdn.com/aliyun-cli-windows-latest-amd64.zip

Please could you add the binaries back to the releases page?

**Comment by JacksonTian** [comment]
Sorry for the problem. Now you can use tag v3.0.114 to download it.
