### ISSUE TITLE
请求支持阿里云私有云环境

### ISSUE THREAD

**Issue by feehoo** [aliyun/aliyun-cli#444]
* **需求类型**:
请求支持阿里云私有云环境
* **需求描述**:
配置中没有支持私有云环境的选项配置，建议增加支持私有云环境的配置和代码
* **设计方案**:
建议增加支持私有云环境的配置和代码

**Comment by JacksonTian** [comment]
由于缺乏私有云环境的相关元数据信息，暂时无法支持。

您可以使用 CLI 的 Common Request 模式，自行拼接参数和 Endpoint 等，使用 --force 来调用私有云环境。
