### ISSUE TITLE
无法make

### ISSUE THREAD

**Issue by jumping** [aliyun/aliyun-cli#45]
无法编译
> 

make

go get gopkg.in/ini.v1
go get github.com/aliyun/alibaba-cloud-sdk-go/...
go get -u github.com/jteeuwen/go-bindata/...
go-bindata -o resource/metas.go -pkg resource -prefix ../aliyun-openapi-meta ../aliyun-openapi-meta/**/* ../aliyun-openapi-meta/products.yml
go build -o out/aliyun main/main.go
#command-line-arguments
main/main.go:41:32: undefined: resource.NewReader
make: *** [build] Error 2

**Comment by ailan-gl** [comment]
@jumping, 因为.gitignore的问题，resource/reader.go这个文件被遗漏了，
目前在最新的版本中已经加回来了，您可以再试一下
