### ISSUE TITLE
上传的时候多带个"/"是啥情况

### ISSUE THREAD

**Issue by lidashuang** [aliyun/aliyun-cli#5]
![]( http://7xlh32.com2.z0.glb.qiniucdn.com/15-9-22/88343396.jpg)
```
aliyuncli oss UploadObjectFromLocalDir ./src oss://ding-prod/112 --check_point upload.txt --replace true --check_md5 false --thread_num 5
```

对应的地址

```
http://ding-prod.oss-cn-hangzhou.aliyuncs.com/112//lfunc.c
```

这个工具

[阿里云全能命令行工具（支持全线云产品配置管理）]( http://market.aliyun.com/products/53690006/cmgj000314.html?spm=5176.2020520130.105.2.ejHJGm)

**Comment by lidashuang** [comment]
升级到 版本是 2.0.3  解决

**Comment by xiangxixids** [comment]
此问题是修改windows兼容性问题导致的，目前已经用别的手段做了兼容性处理。感谢发现的bug。此bug会记录并且关联到您的账户。后续如果有找bug活动，您的提的问题，会有机会获得奖励！
