### ISSUE TITLE
Aliyun cli doesn't work on alpine (musl libc)

### ISSUE THREAD

**Issue by anjieart** [aliyun/aliyun-cli#54]
Hi, I'm trying to put the cli tool inside alpine image. But it doesn't work as expected. Could someone take a look and give a fix? Thanks.

```
$ docker run -v `pwd`/aliyun:/usr/local/bin/aliyun alpine aliyun help
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa01071]

goroutine 1 [running]:
github.com/aliyun/aliyun-cli/oss/lib.DecideConfigFile(0x0, 0x0, 0xb231f2, 0x7)
	/Users/ailan/go/src/github.com/aliyun/aliyun-cli/oss/lib/config_helper.go:57 +0x51
```

**Comment by zeyuye-airwallex** [comment]
you have to build the `aliyun-cli` on alpine, then the `aliyun` works on alpinem try below Dockerfile

```Dockerfile
# build aliyun-cli (aliyun)
FROM golang:alpine as builder
ADD . src/github.com/aliyun/aliyun-cli/
WORKDIR /go/src/github.com/aliyun/aliyun-cli
RUN apk add --update make git;\
  make deps; \
  make testdeps; \
  make build;

# build aliyun image from alpine
FROM alpine
MAINTAINER 叶泽宇/Zeyu Ye <zeyu.ye@airwallex.com>
COPY --from=builder /go/src/github.com/aliyun/aliyun-cli/out/aliyun /usr/local/bin
CMD ["aliyun"]
```

## build/test
```bash
git clone https://github.com/aliyun/aliyun-cli.git
cd aliyun-cli
rand_tag=$(openssl rand -hex 16 )
docker build -t aliyun-${rand_tag} .
docker run -it --rm aliyun-${rand_tag}
```

**Comment by night556** [comment]
> Hi, I'm trying to put the cli tool inside alpine image. But it doesn't work as expected. Could someone take a look and give a fix? Thanks.
> 
> ```
> $ docker run -v `pwd`/aliyun:/usr/local/bin/aliyun alpine aliyun help
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa01071]
> 
> goroutine 1 [running]:
> github.com/aliyun/aliyun-cli/oss/lib.DecideConfigFile(0x0, 0x0, 0xb231f2, 0x7)
> 	/Users/ailan/go/src/github.com/aliyun/aliyun-cli/oss/lib/config_helper.go:57 +0x51
> ```

Hi, thanks for the answer by @zeyuye-airwallex , I hope his answer can help you. And if you have any questions, please contact with us.
Thank you for your attention to AliCloud CLI Project.

**Comment by GuanshengYang** [comment]
> you have to build the `aliyun-cli` on alpine, then the `aliyun` cli works on alpine try below Dockerfile
> 
> ## Dockerfile
> ```dockerfile
> # build aliyun-cli (aliyun)
> FROM golang:alpine as builder
> ADD . src/github.com/aliyun/aliyun-cli/
> WORKDIR /go/src/github.com/aliyun/aliyun-cli
> RUN apk add --update make git;\
>   make deps; \
>   make testdeps; \
>   make build;
> 
> # build aliyun image from alpine
> FROM alpine
> MAINTAINER 叶泽宇/Zeyu Ye <zeyu.ye@airwallex.com>
> COPY --from=builder /go/src/github.com/aliyun/aliyun-cli/out/aliyun /usr/local/bin
> CMD ["aliyun"]
> ```
> 
> ## Build/Test
> ```shell
> git clone https://github.com/aliyun/aliyun-cli.git
> cd aliyun-cli
> rand_tag=$(openssl rand -hex 16)
> docker build -t aliyun-${rand_tag} .
> docker run -it --rm aliyun-${rand_tag}
> ```

Hi, your Dockerfile help me a lot! I adjust a little bit .
## Dockerfile
```dockerfile
FROM golang:alpine3.10 as builder
WORKDIR /go/src/github.com/aliyun/
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
    apk add --update make git; \
    git clone https://github.com/aliyun/aliyun-cli.git; \
    git clone https://github.com/aliyun/aliyun-openapi-meta.git
WORKDIR /go/src/github.com/aliyun/aliyun-cli
ENV GOPROXY=https://goproxy.cn
RUN make deps; \
    make testdeps; \
    make build;

FROM alpine:3.10
COPY --from=builder /go/src/github.com/aliyun/aliyun-cli/out/aliyun /usr/local/bin
CMD ["aliyun"]
```
