### ISSUE TITLE
ARM binary release

### ISSUE THREAD

**Issue by anjieart** [aliyun/aliyun-cli#55]
Is it possible to leverage github `release` feature and put all the history releases and binaries there?

Meantime, besides popular `Linux`, `Darwin`, `Windows` (x86 and x64), is it possible to release additional binaries for `ARM` which is very useful to `Raspberry Pi` users?

I believe it's not a hard task since golang supports cross compiling pretty well.

**Comment by night556** [comment]
> Is it possible to leverage github `release` feature and put all the history releases and binaries there?
> 
> Meantime, besides popular `Linux`, `Darwin`, `Windows` (x86 and x64), is it possible to release additional binaries for `ARM` which is very useful to `Raspberry Pi` users?
> 
> I believe it's not a hard task since golang supports cross compiling pretty well.

Hi, thank you for your suggestion. We are temporarily supporting the mainstream system architecture, and the AliCloud CLI Project is open source, if you want build for other system or architecture,  you can download source code and build.
