### ISSUE TITLE
Receive "The Stack (###) already exists" Error when running "aliyun ros CreateStack"

### ISSUE THREAD

**Issue by QYongHao** [aliyun/aliyun-cli#557]
* **Command Format**: Ubuntu Terminal

* **Execution Command**: 
```
 aliyun ros CreateStack \
 --StackName ### \
 --TimeoutInMinutes ### \
 --TemplateURL oss://### \
 --Parameters.1.ParameterKey ###\
 --Parameters.1.ParameterValue ###  \
 --Parameters.2.ParameterKey ###\
 --Parameters.2.ParameterValue ###
```
* **Output**:
```
ERROR: SDK.ServerError
ErrorCode: StackExists
Recommend: https://next.api.aliyun.com/troubleshoot?q=StackExists&product=ROS
RequestId: 50FEFA9B-09A7-5721-8C8F-F51AFE885EBB
Message: The Stack (###) already exists.
```

Receive an error when running **aliyun ros CreateStack** saying that the stack already exists. The stack appears to be synthesizing correctly when I check the ROS console, so this is not a big deal. But still strange to get an error when nothing is going wrong with the deployment.

**Comment by JacksonTian** [comment]
Recommend: https://next.api.aliyun.com/troubleshoot?q=StackExists&product=ROS

You can visit the troubleshoot link to get reason/solution.
