### ISSUE TITLE
本地运行单元测试，会被删除本地大量文件

### ISSUE THREAD

**Issue by ayanamist** [aliyun/aliyun-cli#568]
https://github.com/aliyun/aliyun-cli/blob/550ccb6a9518e61f2bf188d682c2f4b398aa87a6/cli/completion_installer_test.go#L87-L99

执行测试如果执行到这个用例，就会把本地的 `~/.bashrc` 和 `~/.zshrc` 给删了！

https://github.com/aliyun/aliyun-cli/blob/550ccb6a9518e61f2bf188d682c2f4b398aa87a6/cli/completion_utils_test.go#L121

会删除 `~/.config` 整个目录！

**Comment by yetone** [comment]
太恐怖了 😱

**Comment by Xuanwo** [comment]
另附 ChatGPT 的回复：

![image](https://user-images.githubusercontent.com/5351546/205792083-221a885b-cb80-4990-9d03-dea6b626a346.png)

**Comment by yetone** [comment]
> 为什么**明知**会删除用户的**核心配置文件**，却只是认为『可能会对客户造成一定的不便』，还『希望客户能理解』？强烈质疑专业性。

那是 ChatGPT 的回复啊。。。

**Comment by lambdaq** [comment]
慕名而来。。。

**Comment by hellojukay** [comment]
啊，这。。。

**Comment by KKtheGhost** [comment]
这脚本也太不负责任了... 要么就直接仅支持容器化测试，要么把测试变量影响范围临时限制在 repo 目录下。
```
path := filepath.Join(u.HomeDir, ".bashrc") 
....
os.Remove(path) 
```
这种代码可以通过 Review 只能说 Reviewer 绝对没有拉到本地看过一眼吧

**Comment by Jeff-Tian** [comment]
安利一个 Bash 单元测试框架 Bach: https://bach.sh/index-cn.html 。用它， 在测试过程中 `rm -rf /` 都不必担心。

**Comment by hsyodyssey** [comment]
什么黑客组织

**Comment by Miigon** [comment]
突然想起来这个：
https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6f1dafc8beb84f2ac

很久以前的一个安装会把/usr删掉的项目

**Comment by Kilerd** [comment]
“我们是一家专业的公司”

**Comment by deplives** [comment]
我们是一家专业删用户数据的公司

**Comment by yisiliu** [comment]
这个 commit 四年了，第一次被发现，说明这个库是真的有人用呀🐶hhhhh

**Comment by CppXL** [comment]
好活

**Comment by AkaraChen** [comment]
这种玩意真敢往项目里塞啊

**Comment by ischaojie** [comment]
下一步直接 `rm -rf /*` 也不是不可能。。

**Comment by ycjcl868** [comment]
有点狠啊！不过从 KPI 视角：支持 aliyun cli 本地研发，已开源，获社区的一致好评（500+ stars）...

**Comment by ShuangRen** [comment]
慕名而来，真的敢啊

**Comment by ColorRabbit** [comment]
🐮

**Comment by ExerciseBook** [comment]
> 慕名而来。。。 贵厂的 CI 基础镜像究竟埋了多少坑，才会导致单元测试深仇大恨需要干掉 .bashrc 才能正常跑？

阿里云效的环境也是一坨。

**Comment by JacksonTian** [comment]
这部分测试代码是在添加 autocompletion 功能的时候编写的。编写这段代码的同学自身的环境中没有 .bashrc、. zshrc 文件，没有意识到这个问题。而这部分代码除了在编写这段代码的同学环境中运行外，主要执行环境是 GitHub Actions 等 CI 环境中，因此一直没能发现问题。

因为这部分是测试代码，并没有想到有人去亲自执行该代码。由于最终交付的是 binary 文件，这部分测试代码对最终用户并没有实际影响。当前相关 PR 已经合并解决该问题。

以上，这部分代码确实有考虑不周的地方，接受批评和建议。但请不要额外夸张，谢谢。
