### ISSUE TITLE
aliyun oss mode RamRoleArn ignores proxy-host setting

### ISSUE THREAD

**Issue by dirol13** [aliyun/aliyun-cli#598]
**- Command Format:**

`aliyun oss ls --mode RamRoleArn --proxy-host http://anyhost:8000`

**- Execution Command:**

it does not show anything

**- Output:**

it keeps running without end

I am running aliyun command in a corporate network with proxy servers. I use 
`aliyun oss ls --mode RamRoleArn --proxy-host http://anyhost:8000`

Version: 3.0.144, 3.0.132 both Windows and Linux versions
Environment variables set: http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY

Finally if I wait long enough I get this error:
ERROR: can't get credential refresh RoleArn sts token err: Get `https://sts.aliyuncs.com/*AccessKeyId=***&Action=AssumeRole&DurationSeconds=3600&Format=JSON&RoleArn=ROLE&RoleSessionName=SESSION_NAME&Signature=**&SignatureMethod=HMAC-SHA1&SignatureNonce=**&SignatureVersion=1.0&Timestamp=**&Version=**" dial tcp 47.88.128.94:443: connect: connection timed out.`
I captured the traffic via Wireshark and figured out that another modes like AK, StsToken do not ignore --proxy-host setting and work fine.

**Comment by TsinghuaDream** [comment]
Please use the latest version, this is fixed.
