### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by zxkane** [aliyun/aliyun-cli#6]
**cli**作为阿里云的一个工具，用户可能不是那么多，对用户的辅助多少也经常反馈不到整个产品上面。但既然阿里云决定将**cli**工具作为开源项目，是否可以更专业的对待一些。
1.  版本不一致。此repo的代码从Readme或label看，是`1.0`。然而官网下载来的是`2.0`。从commit history上看，代码都是一坨一坨提交的，呵呵。。。
2. 文档缺失。通过`aliyuncli oss`命令能查询到所有支持的`oss`操作命令。比如命令`UploadDisk`就无法在[在线文档](https://docs.aliyun.com/?spm=5176.383338.201.97.nlXsxq#/pub/aliyun-command-line-interface/oss/ossManual)中找到。既然是开源，是否应该把文档的更新作为代码的一部分，通过**CI**等automation的方式来自动发布。

**Comment by lyman** [comment]
一坨一坨这个事儿吧，有点麻烦。

我们这边通常都是用内部 repo 做开发，定期同步到 github。同步的时候可能要做代码剪裁，而且必须要把违反阿里集团信息安全规范的 commit log 清理掉。

于是就变成每次提交『一坨』了。除非可以直接用 github 的 repo 做开发（类似 aliyun-spark-sdk），否则可能没啥好办法。

**Comment by xiangxixids** [comment]
To zxkane, 您的反馈非常好，这一块我们目前做的不够好。不仅仅代码是一坨坨上传的，写的注释也不清楚。原因是目前人力真的有限。。。但是此问题，我们不会回避。从现在开始会严格维护开源的部分。同时文档的部分，会细化出来。针对特殊产品会给特殊的说明。

**Comment by zxkane** [comment]
**Git**本身非常擅长处理代码分支的情况，比如同时有开源和闭源版本。貌似`aliyun-cli`在github和阿里云内部的看来是不相关的两个repo，这样任何代码合并估计都是万分痛苦的。我相信你们同事非常不愿意提交内部改动到这里，工作量大而无趣，还特别容易出错。

同时，任何改动较大的`pull request`也非常难被接受。在这个`codebase`能工作的，要工作在你们的内部版估计还要不少改动。

不知道把`cli`开源形成一个社区的本意是什么？不论开源与否，有兴趣的hacker都可以改动python版的`cli`来实现自己的需求。按现状来说，这些改进很难能回到官方的版本。Just my two cents.

**Comment by wangyanstorm** [comment]
Really need courage to take such kind of codes as a open source project...

**Comment by windinn** [comment]
阿里开源的项目基本都是太监项目, 很少有后续更新, 更谈不上跟开源社区的互动了.

**Comment by Tinet-AaronAn** [comment]
OSS 建议增加sync同步能力。
还有找了好久也不知道怎么在本机上获取自己的instanceId?

**Comment by keontang** [comment]
> 找了好久也不知道怎么在本机上获取自己的instanceId?

@Tinet-AaronAn 非常同意你这个观点。我是通过 aliyun instance 默认到 hostname 转化到 instanceId，但是这个方法只能保证用户不修改 hostname，但是一般情况下，用户为了方便，都会修改 hostname 的。

真希望能从 /proc/XXXX 下面获取到 instanceId

**Comment by Tinet-AaronAn** [comment]
通过内网地址获取instanceId。
    aliyuncli ecs DescribeInstances --InstanceNetworkType vpc  --PrivateIpAddresses '["192.168.3.2"]' --filter Instances.Instance[0].InstanceId
    获取eip地址
    aliyuncli ecs DescribeInstances --InstanceNetworkType vpc  --PrivateIpAddresses '["192.168.3.2"]' --filter Instances.Instance[0].EipAddress.IpAddress

**Comment by keontang** [comment]
@Tinet-AaronAn 我跟你的场景不一样，我不用 `aliyuncli ` 获取，我是 golang 代码运行在 aliyun instance 上，想获取改 instanceID

**Comment by goodryb** [comment]
@keontang 请参考https://help.aliyun.com/knowledge_detail/49122.html
使用限制

只有 VPC 网络类型的实例才能获取到元数据。

获取方法

Linux：使用 curl http://100.100.100.200/latest/meta-data/ 可以访问到元数据的根目录，加入具体的元数据名称即可访问到具体的元数据，如：

curl http://100.100.100.200/latest/meta-data/instance-id 可以获取到实例 ID
curl http://100.100.100.200/latest/meta-data/image-id 可以获取到创建实例时所使用的镜像 ID
Windows：使用 Powershell 执行如下命令即可获取元数据信息：

  Invoke-RestMethod http://100.100.100.200/latest/meta-data/
在 URL 中增加具体的元数据名称即可查到具体的元数据，例如，添加 instance-id 可以获取实例 ID：

  Invoke-RestMethod http://100.100.100.200/latest/meta-data/instance-id

**Comment by keontang** [comment]
@goodryb 谢谢

**Comment by JacksonTian** [comment]
Thanks the suggestion all.

**Comment by JacksonTian** [comment]
Any question, let's create new another issue.
