### ISSUE TITLE
添加配置文件报错

### ISSUE THREAD

**Issue by goodryb** [aliyun/aliyun-cli#60]
aliyun configure
Configuring profile '' in '' authenticate mode...
Access Key Id [*************1ZG]:
Access Key Secret [***************************A7e]:
Default Region Id [cn-hangzhou]:
Default Output Format [json]: json (Only support json))
Default Language [zh|en] zh:
Saving profile[] ...Done.
panic: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"Ecs","RegionId":"cn-hangzhou","LocationProduct":"ecs","LocationEndpointType":"openAPI"}), please check the user guide

goroutine 1 [running]:
github.com/aliyun/aliyun-cli/config.DoHello(0xc4201e9848)
	/Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/hello.go:55 +0x69b
github.com/aliyun/aliyun-cli/config.doConfigure(0x0, 0x0, 0x0, 0x0, 0x1e29b60, 0x0)
	/Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/configure.go:105 +0x760
github.com/aliyun/aliyun-cli/config.NewConfigureCommand.func1(0xc4202b1b60, 0x1e29b60, 0x0, 0x0, 0x0, 0x0)
	/Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/configure.go:28 +0x87
github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc420118f00, 0xc4202b1b60, 0xc42000c2d0, 0x0, 0x0, 0x0, 0xc4201d4300)
	/Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:229 +0x6bc
github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc420119360, 0xc4202b1b60, 0xc42000c2d0, 0x1, 0x1, 0x0, 0xc4202b1b00)
	/Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:169 +0x9b9
github.com/aliyun/aliyun-cli/cli.(*Command).Execute(0xc420119360, 0xc42000c2d0, 0x1, 0x1)
	/Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:77 +0x1b4
main.main()
	/Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/main/main.go:67 +0x61c

**Comment by jxyowen** [comment]
检查AK信息是否有误
