### ISSUE TITLE
aliyun command usage error

### ISSUE THREAD

**Issue by xuyuji9000** [aliyun/aliyun-cli#65]
Getting this error for every `aliyun` command I run

<img width="712" alt="screen shot 2018-05-25 at 7 42 26 pm" src="https://user-images.githubusercontent.com/4877346/40542696-ca396b5c-6053-11e8-864a-442b29636ae0.png">

**ERROR: load current configuration failed unknown profile default, run configure to check**

**Comment by jxyowen** [comment]
run "aliyun configure" to config CLI

**Comment by xuyuji9000** [comment]
Tried command `aliyun configure`

Result:

<img width="1205" alt="screen shot 2018-06-20 at 10 40 10 am" src="https://user-images.githubusercontent.com/4877346/41634507-a2c1caba-7476-11e8-8a6c-a9de152b89cd.png">

**Comment by weiyongsheng** [comment]
看源码，发现删除自己用户home目录下的.aliyun/config.json文件就还原了
