### ISSUE TITLE
运行时崩溃，据说是获取不到user的原因，

### ISSUE THREAD

**Issue by wekay102200** [aliyun/aliyun-cli#66]
goroutine 1 [running]:
github.com/aliyun/aliyun-cli/oss/lib.DecideConfigFile(0x0, 0x0, 0xc3bb7f, 0x7)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/oss/lib/config_helper.go:57 +0x51
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xae7371]

goroutine 1 [running]:
github.com/aliyun/aliyun-cli/oss/lib.DecideConfigFile(0x0, 0x0, 0xc3bb7f, 0x7)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/oss/lib/config_helper.go:57 +0x51
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xae7371]

goroutine 1 [running]:
github.com/aliyun/aliyun-cli/oss/lib.DecideConfigFile(0x0, 0x0, 0xc3bb7f, 0x7)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/oss/lib/config_helper.go:57 +0x51
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xae7371]

goroutine 1 [running]:
github.com/aliyun/aliyun-cli/oss/lib.DecideConfigFile(0x0, 0x0, 0xc3bb7f, 0x7)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/oss/lib/config_helper.go:57 +0x51
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xae7371]

我觉得下载文件应该是和用户没关系的，不知道你们判断用户的依据是什么。

系统为ubuntu16.04，直接运行没问题。

**Comment by wekay102200** [comment]
在docker里面运行或者是在分布系统里面被调用会出现以上错误。

**Comment by jxyowen** [comment]
请使用3.0.3版 http://aliyun-cli.oss-cn-hangzhou.aliyuncs.com/aliyun-cli-linux-3.0.3-amd64.tgz
