### ISSUE TITLE
invalid memory address when run in the docker with linux binary version

### ISSUE THREAD

**Issue by JennyLi90** [aliyun/aliyun-cli#67]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xae7371]

goroutine 1 [running]:
github.com/aliyun/aliyun-cli/oss/lib.DecideConfigFile(0x0, 0x0, 0xc3bb7f, 0x7)
	/Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/oss/lib/config_helper.go:57 +0x51

**Comment by jxyowen** [comment]
请使用3.0.3版 http://aliyun-cli.oss-cn-hangzhou.aliyuncs.com/aliyun-cli-linux-3.0.3-amd64.tgz

**Comment by JennyLi90** [comment]
3.0.3 的版本没有问题了。谢谢
