### ISSUE TITLE
Container Registry commands do not work

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#68]
Hi --, 

when running `$ aliyun cr GET /namespace` I get the following error:
```
ERROR: SDK.ServerError
ErrorCode:
Recommend:
RequestId:
Message: {"message":"","code":"rpc_invalid_arg","requestId":"0474A51A-2965-464B-8391-1F4448F62BF7"}
```
Region is eu-central-1, credentials used have full access. Any ideas what might be the cause? Thanks!

**Comment by Hyzhou** [comment]
aliyun cr --endpoint cr.cn-hangzhou.aliyuncs.com GET /namespace

**Comment by Hyzhou** [comment]
Aliyun CLI cloud enum the default endpoint for the product. like

**Comment by arafato** [comment]
Thanks @Hyzhou that works! Could you please add this to `$aliyun cr help` ?
