### ISSUE TITLE
Service Activation possible?

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#69]
Hi everybody, 

is it possible to activate services via CLI? It only seems to be possible via the graphical console which involves manual steps. Thanks!

**Comment by night556** [comment]
> Hi everybody,
> 
> is it possible to activate services via CLI? It only seems to be possible via the graphical console which involves manual steps. Thanks!

Hi, the CLI project is for the convenience of product operation，and service activation is not supported at this time.
Thank you for your attention to AliCloud CLI Project!
