### ISSUE TITLE
oss只能使用杭州区？

### ISSUE THREAD

**Issue by zheli** [aliyun/aliyun-cli#7]
不管我怎么设，其他区就是不能用
```
root@133-130-89-83:~# aliyuncli oss CreateBucket oss://meixiaozhu-shared --location oss-cn-beijing
Error Headers:

[('content-length', '327'), ('server', 'AliyunOSS'), ('connection', 'keep-alive'), ('x-oss-request-id', '5634E30FC7A7A96714A64234'), ('date', 'Sat, 31 Oct 2015 15:49:35 GMT'), ('content-type', 'application/xml')]
Error Body:

<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>InvalidLocationConstraint</Code>
  <Message>The specified location-constraint is not valid</Message>
  <LocationConstraint>oss-cn-beijing</LocationConstraint>
  <RequestId>5634E30FC7A7A96714A64234</RequestId>
  <HostId>meixiaozhu-shared.oss.aliyuncs.com</HostId>
</Error>

Error Status:

400
CreateBucket Failed!
```
然后我不制定的话就可以
```
root@133-130-89-83:~# aliyuncli oss CreateBucket oss://meixiaozhu-shared
0.539(s) elapsed
```

是我选项用错了？

**Comment by xiangxixids** [comment]
你好, 不好意思 回复慢了. 您在使用--location的时候必须跟着对应的host才可以. 就您的例子中, oss选择beijing区域, 那么host要跟着使用beijing的host, 我猜您当前的配置中默认配置了hangzhou的region. 给您一个例子参考: 
杭州的例子:
aliyuncli oss  CreateBucket oss://ttttssccyy2 --location  oss-cn-hangzhou  --host oss-cn-hangzhou.aliyuncs.com
北京的例子:
aliyuncli oss  CreateBucket oss://ttttssccyy2 --location  oss-cn-beijing  --host oss-cn-beijing.aliyuncs.com 

另外, 您是否有在使用其他产品呢, 例如ecs/rds/cmd/bss 等, 如果遇到问题, 也请跟我们沟通.

**Comment by xiangxixids** [comment]
再给一个删除的命令参考:
aliyuncli oss   DeleteWholeBucket oss://ttttssccyy2 --host oss-cn-beijing.aliyuncs.com

**Comment by zheli** [comment]
能有回答我已经很满足了T_T

目前我们刚开始用ECS，OSS和RDS，等遇到问题一定再来问:)
