### ISSUE TITLE
mns service support

### ISSUE THREAD

**Issue by otarabai** [aliyun/aliyun-cli#71]
Hi,

Any plans to add support for Message Service ([mns](https://www.alibabacloud.com/product/message-service#resources)) ?

**Comment by night556** [comment]
> Hi,
> 
> Any plans to add support for Message Service ([mns](https://www.alibabacloud.com/product/message-service#resources)) ?

Hi, the products we support are increasing, if you want to know products we support, you can run `aliyun help` to print the products we support.
Thank you for your attention to AliCloud CLI Project!

**Comment by jonjohnston** [comment]
Why is this closed? Over 2 years and mns is still not supported.
