### ISSUE TITLE
如何访问容器镜像服务个人版API

### ISSUE THREAD

**Issue by yousong** [aliyun/aliyun-cli#714]
* **需求类型**: 

增加特性

* **需求描述**: 

容器镜像服务（cr）提供企业版和个人版实例服务，企业版API和个人版API是分开的，不能相互混用。当前`aliyun cr`子命令只支持访问企业版实例。新版本aliyun-cli如何访问个人版实例服务呢？

* **设计方案**:

无

**Comment by TsinghuaDream** [comment]
强制调用
aliyun mockproduct GET /regions --version 2016-06-07 --endpoint cr.cn-beijing.aliyuncs.com --force

**Comment by yousong** [comment]
> 强制调用 aliyun mockproduct GET /regions --version 2016-06-07 --endpoint cr.cn-beijing.aliyuncs.com --force

我这里没有mockproduct这个子命令，是需要开启什么隐藏通道吗？

```
➜  ~ aliyun --version | grep Version
Alibaba Cloud Command Line Interface Version 3.0.165
➜  ~ aliyun --help | grep mockproduct
➜  ~ aliyun --help | grep mock
➜  ~ aliyun mockproduct --help
Alibaba Cloud Command Line Interface Version 3.0.165
ERROR: 'mockproduct' is not a valid command or product. See `aliyun help`.
➜  ~ aliyun mockproduct GET
ERROR: 'mockproduct' is not a valid command or product. See `aliyun help`.
➜  ~
```

**Comment by TsinghuaDream** [comment]
不需要 这个命令就是隐藏通道 没有help提示的

**Comment by yousong** [comment]
> 不需要 这个命令就是隐藏通道 没有help提示的

多谢。没有文档，这个体验不是很好，比如POST传参之类

而且……
- 这个mockproduct在仓库的源码里面都没有找到
- 相同的命令使用从源码编译的二进制去执行会报错

难道release页面的二进制不是这里仓库编译出来的吗 ;(

**Comment by TsinghuaDream** [comment]
> > 不需要 这个命令就是隐藏通道 没有help提示的
> 
> 多谢。没有文档，这个体验不是很好，比如POST传参之类
> 
> 而且……
> 
> * 这个mockproduct在仓库的源码里面都没有找到
> * 相同的命令使用从源码编译的二进制去执行会报错
> 
> 难道release页面的二进制不是这里仓库编译出来的吗 ;(

你加了--force吗 应该不会报错的

**Comment by yousong** [comment]
> > > 不需要 这个命令就是隐藏通道 没有help提示的
> > 
> > 
> > 多谢。没有文档，这个体验不是很好，比如POST传参之类
> > 而且……
> > 
> > * 这个mockproduct在仓库的源码里面都没有找到
> > * 相同的命令使用从源码编译的二进制去执行会报错
> > 
> > 难道release页面的二进制不是这里仓库编译出来的吗 ;(
> 
> 你加了--force吗 应该不会报错的 这块主要原因是 个人版CR 元数据没接入CLI 所以需要使用类似公共调用方法强行调用

刚才再确认了下，是因为当时执行的环境没有做aliyun configure。实际是可以用的。

补充一些信息
- mockproduct只是一个占位符，只要不与已有的product code冲突，用别的串也是可以的
- 请求体可以通过`--body`，`--body-file`指定
- 部分文档，https://help.aliyun.com/document_detail/90398.html#section-uhy-4cc-kgb

代码入口

https://github.com/aliyun/aliyun-cli/blob/67ab4ebd377d95a01eaeeaf578601a06c5b84dbd/openapi/commando.go#L295-L303

**Comment by yousong** [comment]
估计使用GET/POST是可以达到效果的，先关闭issue。

@TsinghuaDream ，感谢提供帮助！
