### ISSUE TITLE
A clear statement should be provided when authentication fails

### ISSUE THREAD

**Issue by SCHEN2015** [aliyun/aliyun-cli#72]
The `aliyuncli ecs DescribeInstances` gives `SDK.InvalidRegionId` and `Can not find endpoint to access` when authentication fails. It would be much better and clear if `aliyuncli` provides a statement like "SDK.InvalidCredentials" or something like "Authentication failure".

Test code:

```
[cheshi@cheshi-desktop1 ~]$ aliyuncli configure
Aliyun Access Key ID [****************tdse]: 
Aliyun Access Key Secret [****************FXOw]: BadCredentialsHere
Default Region Id [us-west-1]:
Default output format [json]: 
[cheshi@cheshi-desktop1 ~]$ 
[cheshi@cheshi-desktop1 ~]$ aliyuncli ecs DescribeInstances
{
"Message": "Can not find endpoint to access.", 
"Code": "SDK.InvalidRegionId"
}
Detail of Client Exception:

SDK.InvalidRegionId Can not find endpoint to access.
```

**Comment by japzio** [comment]
this issue probably has been fixed?

**Comment by night556** [comment]
> The `aliyuncli ecs DescribeInstances` gives `SDK.InvalidRegionId` and `Can not find endpoint to access` when authentication fails. It would be much better and clear if `aliyuncli` provides a statement like "SDK.InvalidCredentials" or something like "Authentication failure".
> 
> Test code:
> 
> ```
> [cheshi@cheshi-desktop1 ~]$ aliyuncli configure
> Aliyun Access Key ID [****************tdse]: 
> Aliyun Access Key Secret [****************FXOw]: BadCredentialsHere
> Default Region Id [us-west-1]:
> Default output format [json]: 
> [cheshi@cheshi-desktop1 ~]$ 
> [cheshi@cheshi-desktop1 ~]$ aliyuncli ecs DescribeInstances
> {
> "Message": "Can not find endpoint to access.", 
> "Code": "SDK.InvalidRegionId"
> }
> Detail of Client Exception:
> 
> SDK.InvalidRegionId Can not find endpoint to access.
> ```

Hi, we have update in lastest version. So we recommend that you update to the latest version. If you have any other questions, please contact with us.
Thank you for your attention to AliCloud CLI Project!

**Comment by SCHEN2015** [comment]
> > The `aliyuncli ecs DescribeInstances` gives `SDK.InvalidRegionId` and `Can not find endpoint to access` when authentication fails. It would be much better and clear if `aliyuncli` provides a statement like "SDK.InvalidCredentials" or something like "Authentication failure".
> > Test code:
> > ```
> > [cheshi@cheshi-desktop1 ~]$ aliyuncli configure
> > Aliyun Access Key ID [****************tdse]: 
> > Aliyun Access Key Secret [****************FXOw]: BadCredentialsHere
> > Default Region Id [us-west-1]:
> > Default output format [json]: 
> > [cheshi@cheshi-desktop1 ~]$ 
> > [cheshi@cheshi-desktop1 ~]$ aliyuncli ecs DescribeInstances
> > {
> > "Message": "Can not find endpoint to access.", 
> > "Code": "SDK.InvalidRegionId"
> > }
> > Detail of Client Exception:
> > 
> > SDK.InvalidRegionId Can not find endpoint to access.
> > ```
> 
> Hi, we have update in lastest version. So we recommend that you update to the latest version. If you have any other questions, please contact with us.
> Thank you for your attention to AliCloud CLI Project!

Tried with release 3.0.10, it has been fixed. Thanks!

```
$ aliyun ecs DescribeInstances
ERROR: SDK.ServerError
ErrorCode: IncompleteSignature
```
