### ISSUE TITLE
当我使用 aliyun  configure get default 报 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lunnlew** [aliyun/aliyun-cli#73]
平台:
win10 
执行:
aliyun.exe  configure get default
报错:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xb0 pc=0x79ca93]

goroutine 1 [running]:
github.com/aliyun/aliyun-cli/cli.(*Flag).GetStringOrDefault(...)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/flag.go:136
github.com/aliyun/aliyun-cli/config.(*Profile).OverwriteWithFlags(0xc042082e88, 0xc042061780)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/profile.go:125 +0x1d3
github.com/aliyun/aliyun-cli/config.(*Configuration).GetCurrentProfile(0xc042083408, 0xc042061780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/configuration.go:59 +0x1b9
github.com/aliyun/aliyun-cli/config.doConfigureGet(0xc042061780, 0xc0423cb4f0, 0x1, 0x1)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/configure_get.go:43 +0x17e
github.com/aliyun/aliyun-cli/config.NewConfigureGetCommand.func1(0xc042061780, 0xc0423cb4f0, 0x1, 0x1, 0x1, 0xc0423cb4f0)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/configure_get.go:29 +0x50
github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc0423bcd20, 0xc042061780, 0xc0420600b0, 0x1, 0x1, 0x0, 0xc042061bc0)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:226 +0x697
github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc0423bcc80, 0xc042061780, 0xc0420600a0, 0x2, 0x2, 0x0, 0x12ddf08)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:166 +0x998
github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc04205cd20, 0xc042061780, 0xc042060090, 0x3, 0x3, 0xc0423bd998, 0xc0423fc480)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:166 +0x998
github.com/aliyun/aliyun-cli/cli.(*Command).Execute(0xc04205cd20, 0xc042061780, 0xc042060090, 0x3, 0x3)
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:74 +0x64
main.main()
        /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/main/main.go:71 +0x877`

**Comment by night556** [comment]
> 平台:
> win10
> 执行:
> aliyun.exe configure get default
> 报错:
> `panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0xb0 pc=0x79ca93]
> 
> goroutine 1 [running]:
> github.com/aliyun/aliyun-cli/cli.(*Flag).GetStringOrDefault(...)
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/flag.go:136
> github.com/aliyun/aliyun-cli/config.(*Profile).OverwriteWithFlags(0xc042082e88, 0xc042061780)
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/profile.go:125 +0x1d3
> github.com/aliyun/aliyun-cli/config.(*Configuration).GetCurrentProfile(0xc042083408, 0xc042061780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/configuration.go:59 +0x1b9
> github.com/aliyun/aliyun-cli/config.doConfigureGet(0xc042061780, 0xc0423cb4f0, 0x1, 0x1)
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/configure_get.go:43 +0x17e
> github.com/aliyun/aliyun-cli/config.NewConfigureGetCommand.func1(0xc042061780, 0xc0423cb4f0, 0x1, 0x1, 0x1, 0xc0423cb4f0)
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/config/configure_get.go:29 +0x50
> github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc0423bcd20, 0xc042061780, 0xc0420600b0, 0x1, 0x1, 0x0, 0xc042061bc0)
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:226 +0x697
> github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc0423bcc80, 0xc042061780, 0xc0420600a0, 0x2, 0x2, 0x0, 0x12ddf08)
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:166 +0x998
> github.com/aliyun/aliyun-cli/cli.(*Command).executeInner(0xc04205cd20, 0xc042061780, 0xc042060090, 0x3, 0x3, 0xc0423bd998, 0xc0423fc480)
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:166 +0x998
> github.com/aliyun/aliyun-cli/cli.(*Command).Execute(0xc04205cd20, 0xc042061780, 0xc042060090, 0x3, 0x3)
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/cli/command.go:74 +0x64
> main.main()
> /Users/jxyowen/Projects/go/src/github.com/aliyun/aliyun-cli/main/main.go:71 +0x877`

你好，现在CLI版本已经更新到3.0.9，我们建议您更新至最新版本，再次尝试运行命令，如果仍有问题，请根据 issue 模板提交完整的命令与输出以及必要的描述给我们。最后考虑到该issue的时间已经很久了，如果没有后续情况，我们将在2019.2.11号之后关闭该issue。
感谢你对 AliCloud CLI 项目的关注！
