### ISSUE TITLE
The specified parameter "KeyPairNames" is not valid

### ISSUE THREAD

**Issue by alexeyshishkin01** [aliyun/aliyun-cli#76]
root@Alexey-HP:~# aliyun ecs DeleteKeyPairs \
> --RegionId $RegionId \
> --KeyPairNames ppro-key
ERROR: SDK.ServerError
ErrorCode: InvalidKeyPairNames.ValueNotSupported
Recommend:
RequestId: 3369F771-84CC-49A6-9AD1-953BDC9049AC
Message: The specified parameter "KeyPairNames" is not valid.

**Comment by night556** [comment]
> root@Alexey-HP:~# aliyun ecs DeleteKeyPairs \
> 
> > --RegionId $RegionId 
> > --KeyPairNames ppro-key
> > ERROR: SDK.ServerError
> > ErrorCode: InvalidKeyPairNames.ValueNotSupported
> > Recommend:
> > RequestId: 3369F771-84CC-49A6-9AD1-953BDC9049AC
> > Message: The specified parameter "KeyPairNames" is not valid.

Hi, This issue is now four months away, and we don't know follow-up information, so if this problem still  has, please contact with us.
Thank you for your attention to AliCloud CLI Project!

**Comment by ewoodlief** [comment]
It will JSON parse an array of strings:

--KeyPairNames '["foo"]'

**Comment by night556** [comment]
> It will JSON parse an array of strings:
> 
> --KeyPairNames '["foo"]'



> root@Alexey-HP:~# aliyun ecs DeleteKeyPairs \
> 
> > --RegionId $RegionId 
> > --KeyPairNames ppro-key
> > ERROR: SDK.ServerError
> > ErrorCode: InvalidKeyPairNames.ValueNotSupported
> > Recommend:
> > RequestId: 3369F771-84CC-49A6-9AD1-953BDC9049AC
> > Message: The specified parameter "KeyPairNames" is not valid.

Thanks to @ewoodlief's answer, the form of the parameter value can refer to the document: https://help.aliyun.com/document_detail/51772.html?spm=5176.10695662.1996646101.searchclickresult.67b91a13eafXoN
