### ISSUE TITLE
Add oss to help description

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#77]
Hi --, 

I'm using version `3.0.4`

Can you please add `oss` to the help output (`$ aliyun --help`). It is currently not part of the output. Thanks!

**Comment by PaleCheung** [comment]
> Hi --,
> I'm using version 3.0.4
> Can you please add oss to the help output ($ aliyun --help). It is currently not part of the output. Thanks!

"aliyun oss" is just same as ossutil.
You can view ossutil's help doc if you want to use "aliyun oss".
I recommand you to use ossutil because there are some bugs in "aliyun oss".

**Comment by arafato** [comment]
Thanks for the answer! Any timeline when these bugs will be fixed?
