### ISSUE TITLE
Configure aliyun cli with env. variables

### ISSUE THREAD

**Issue by ala2208** [aliyun/aliyun-cli#79]
Hi,

I want to run cli commands once I exported env. varibles accessKeyID, accessSecretKey and region (without running "aliyun configure" command). 
What is the right env. variables names?
Does this feature supported?

Thank you!

**Comment by PaleCheung** [comment]
I think that it need an empty config file without your credential info.

**Comment by xiaozhu36** [comment]
Hi @ala2208 You can set env variables by `ACCESS_KEY_ID`、`ACCESS_KEY_SECRET`
and `REGION`.

**Comment by ala2208** [comment]
Thank You!
I will try.

**Comment by japzio** [comment]
> Hi @ala2208 You can set env variables by `ACCESS_KEY_ID`、`ACCESS_KEY_SECRET`
> and `REGION`. Please check it.

Hi @xiaozhu36 , 

Assuming `ACCESS_KEY_ID`、`ACCESS_KEY_SECRET` has been set, but REGION was unset, and i dont have `~/.aliyun/config.json`, it should no longer look for it if I pass --RegionId on the command line.
```
aliyun cr GetAuthorizationToken --RegionId ap-southeast-1
```
returns
```
user@node$ aliyun cr GetAuthorizationToken --RegionId ap-southeast-1
ERROR: region can't be empty

Configuration failed, use `aliyun configure` to configure it
```
