### ISSUE TITLE
json output

### ISSUE THREAD

**Issue by alexeyshishkin01** [aliyun/aliyun-cli#80]
hello, all!

is it possible to have other than json only output for 'aliyun' CLI (for example table)?

I need to get list of available resources in the specific region and specific zone and I run:

root@Alexey-HP:~# aliyun ecs DescribeAvailableResource \
> --RegionId $RegionId \
> --DestinationResource InstanceType \
> --ZoneId $ZoneId \
> --IoOptimized optimized

the output is almost unreadable

**Comment by alexeyshishkin01** [comment]
as an example of how it can be done using http://jmespath.org/:

aliyun ecs DescribeAvailableResource \
--RegionId $RegionId \
--DestinationResource InstanceType \
--ZoneId $ZoneId \
--IoOptimized optimized \
| jp.py AvailableZones.AvailableZone[0].AvailableResources.AvailableResource[0].SupportedResources.SupportedResource[0:999].Value \
| grep 'ecs' | awk -F '"' '{ print $2 }' | sort

**Comment by alexeyshishkin01** [comment]
this is because

aliyun ecs DescribeAvailableResource \
--RegionId $RegionId \
--DestinationResource InstanceType \
--ZoneId $ZoneId \
--IoOptimized optimized \
--output cols=Value

does not work as expected

**Comment by japzio** [comment]
probably could try **jq** . also requested pretty print cli output #119

**Comment by night556** [comment]
> this is because
> 
> aliyun ecs DescribeAvailableResource 
> --RegionId $RegionId 
> --DestinationResource InstanceType 
> --ZoneId $ZoneId 
> --IoOptimized optimized 
> --output cols=Value
> 
> does not work as expected

Hi, json pretty print is avaible now in version 3.0.8 and above.
Thank you for your attention to AliCloud CLI Project.
