### ISSUE TITLE
The specified parameter "SnapshotIds" is not valid

### ISSUE THREAD

**Issue by alexeyshishkin01** [aliyun/aliyun-cli#81]
I have an issue with the command:

root@Alexey-HP:~# aliyun ecs DescribeSnapshots \
> --RegionId $RegionId \
> --SnapshotIds $SnapshotId
ERROR: SDK.ServerError
ErrorCode: InvalidParameter
Recommend:
RequestId: 5D367BFE-2834-4D71-813D-72C110C236DA
Message: The specified parameter "SnapshotIds" is not valid.

If I run the same command without specifying '$SnapshotId' for '--SnapshotIds'
root@Alexey-HP:~# aliyun ecs DescribeSnapshots \
> --RegionId $RegionId \
> --SnapshotIds
it shows me information about my snapshots:

root@Alexey-HP:~# aliyun ecs DescribeSnapshots --RegionId $RegionId --SnapshotIds
{"PageNumber":1,"TotalCount":1,"PageSize":10,"RequestId":"EC6DD188-9F97-45DD-BC91-998A2061B0CC","Snapshots":{"Snapshot":[{"Description":"ppro-std1052-ubuntu1604-x64-snapshot","SnapshotName":"ppro-std1052-ubuntu1604-x64-snapshot","ProductCode":"","Encrypted":false,"SourceDiskSize":40,"Progress":"100%","Usage":"image","CreationTime":"2018-10-03T11:57:05Z","SourceStorageType":"disk","Tags":{"Tag":[]},"Status":"accomplished","SourceDiskType":"system","SourceDiskId":"d-gw88owuii37is8s6u0h5","SnapshotId":"s-gw890iev8ynwk9l6ry61"}]}}
root@Alexey-HP:~#

so I cannot display information about particular snapshot by providing SnapshotId (suppose I have 100 snapshots)

**Comment by night556** [comment]
> I have an issue with the command:
> 
> root@Alexey-HP:~# aliyun ecs DescribeSnapshots \
> 
> > --RegionId $RegionId 
> > --SnapshotIds $SnapshotId
> > ERROR: SDK.ServerError
> > ErrorCode: InvalidParameter
> > Recommend:
> > RequestId: 5D367BFE-2834-4D71-813D-72C110C236DA
> > Message: The specified parameter "SnapshotIds" is not valid.
> 
> If I run the same command without specifying '$SnapshotId' for '--SnapshotIds'
> root@Alexey-HP:~# aliyun ecs DescribeSnapshots \
> 
> > --RegionId $RegionId 
> > --SnapshotIds
> > it shows me information about my snapshots:
> 
> root@Alexey-HP:# aliyun ecs DescribeSnapshots --RegionId $RegionId --SnapshotIds
> {"PageNumber":1,"TotalCount":1,"PageSize":10,"RequestId":"EC6DD188-9F97-45DD-BC91-998A2061B0CC","Snapshots":{"Snapshot":[{"Description":"ppro-std1052-ubuntu1604-x64-snapshot","SnapshotName":"ppro-std1052-ubuntu1604-x64-snapshot","ProductCode":"","Encrypted":false,"SourceDiskSize":40,"Progress":"100%","Usage":"image","CreationTime":"2018-10-03T11:57:05Z","SourceStorageType":"disk","Tags":{"Tag":[]},"Status":"accomplished","SourceDiskType":"system","SourceDiskId":"d-gw88owuii37is8s6u0h5","SnapshotId":"s-gw890iev8ynwk9l6ry61"}]}}
> root@Alexey-HP:#
> 
> so I cannot display information about particular snapshot by providing SnapshotId (suppose I have 100 snapshots)

Hi, I just try this command and the result is sucessful. By the way, when you run this command, you need to be aware that the value of `--SnapshotIds` is similar to `['x-xxxxxxxxx','x-xxxxxxx']`. And if you have any other problems, please contact us.
Thank you for your attention to AliCloud CLI Project!
