### ISSUE TITLE
aliyun single-line output

### ISSUE THREAD

**Issue by alexeyshishkin01** [aliyun/aliyun-cli#82]
I have the following command output:
root@Alexey-HP:~# aliyun ecs DescribeDisks \
> --RegionId $RegionId \
> --DiskIds \
> --output cols=DiskId
DiskId
------
d-gw873hs7flndqzk86i63

I need this output to be as simple as 'd-gw873hs7flndqzk86i63', so that I'll be able to assign its result to variable, ex.:

DiskId=$(aliyun ecs DescribeDisks --RegionId $RegionId --DiskIds --output XXX-YYY-ZZZ)
echo $DiskId

How to do that?

**Comment by japzio** [comment]
you can use JQ json processor command line too to query json

**Comment by night556** [comment]
> I have the following command output:
> root@Alexey-HP:~# aliyun ecs DescribeDisks \
> 
> > --RegionId $RegionId 
> > --DiskIds 
> > --output cols=DiskId
> > DiskId
> 
> d-gw873hs7flndqzk86i63
> 
> I need this output to be as simple as 'd-gw873hs7flndqzk86i63', so that I'll be able to assign its result to variable, ex.:
> 
> DiskId=$(aliyun ecs DescribeDisks --RegionId $RegionId --DiskIds --output XXX-YYY-ZZZ)
> echo $DiskId
> 
> How to do that?

Hi, cli print the return of openapi, we support json and tabular forms. And if you want custom output format, you can operate on the basis of our output.
Thank you for your attention to AliCloud CLI Project!
