### ISSUE TITLE
数据同步问题

### ISSUE THREAD

**Issue by aleooooo** [aliyun/aliyun-cli#822]
cmd
aliyun vpc CreateVSwitch --region cn-qingdao --RegionId 'cn-qingdao' --CidrBlock '172.16.0.0/24' --ZoneId 'cn-qingdao-b' --VpcId 'vpc-xxxx' --VSwitchName 'VSW-cn-qingdao-b-1000'
在官网使用open api调用正常,并且生成了该CLI语句,但当我在本地使用3.0.181调用时,返回:
ERROR: SDK.ServerError
ErrorCode: InvalidVpcId.NotFound
Recommend: https://api.aliyun.com/troubleshoot?q=InvalidVpcId.NotFound&product=Vpc
RequestId: 750471EA-432C-...
Message: Specified VPC does not exist.
RespHeaders: map[Access-Control-Allow-Origin:[*] Access-Control-Expose-Headers:[*] Connection:[keep-alive] Content-Length:[250] Content-Type:[application/json;charset=utf-8] Date:[Sun, 10 Sep 2023 22:25:44 GMT] Keep-Alive:[timeout=25] X-Acs-Request-Id:[750471EA-432C-5338...] X-Acs-Trace-Id:[...]]
”

**Comment by aleooooo** [comment]
我很确定vpcid存在

**Comment by JacksonTian** [comment]
找客服或者在 API 门户上反馈一下，GitHub 上无法处理这种纯业务性问题的。

Issue 我先关闭。如果有问题可以随时 re-open。

Thanks for your feedback.
