### ISSUE TITLE
how to authorize security group when PortRange is "-1/-1"?

### ISSUE THREAD

**Issue by h1k0n** [aliyun/aliyun-cli#83]
#aliyun ecs AuthorizeSecurityGroup --RegionId cn-xxxx --SecurityGroupId sg-xxxx --IpProtocol icmp --PortRange -1/-1 --SourceCidrIp 0.0.0.0/0 --Description icmp
return:
ERROR: parse failed not support flag form -1/-1

**Comment by xh4n3** [comment]
Same issue. I specified Bandwidth to -1 when calling CreateLoadBalancerTCPListener, it reports ERROR: parse failed unknown flag -1.

**Comment by jxyowen** [comment]
Please try to use like this:
aliyun  ecs AuthorizeSecurityGroup --IpProtocol all --SecurityGroupId 1 --PortRange=-1/-1
