### ISSUE TITLE
Does aliyun-cli support upload SSL certificate to OSS bucket?

### ISSUE THREAD

**Issue by kelvinji2009** [aliyun/aliyun-cli#87]

**Comment by kelvinji2009** [comment]
Just like `aliyun slb UploadServerCertificate`

**Comment by night556** [comment]
> Just like `aliyun slb UploadServerCertificate`

Hi, this feature is already supported in lastest version. We recommand that you download the lastest version of cli and try again.
Thank you for your attention to AliCloud CLI Project!

**Comment by night556** [comment]
> Just like `aliyun slb UploadServerCertificate`

Hi, the new features related to oss products are not part of CLI project now. If you have some other questions, please contact us.
Thank you for your attention to AliCloud CLI Project!
