### ISSUE TITLE
Streaming data

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#88]
Hi --, 

is streaming data through pipes supported to avoid disk IO?
In AWS I can do
`aws s3 cp s3://rds-bucket/backup ‐ | aws s3 cp - s3://mybucket/backup`

Is this also supported by ossutil? I've tried but no success so far. Any plans to support it?

**Comment by night556** [comment]
> Hi --,
> 
> is streaming data through pipes supported to avoid disk IO?
> In AWS I can do
> `aws s3 cp s3://rds-bucket/backup ‐ | aws s3 cp - s3://mybucket/backup`
> 
> Is this also supported by ossutil? I've tried but no success so far. Any plans to support it?

Hi, pipeline command operator belongs to the linux shell command, as long as it meets the requirements of the pipe, it can be used. And CLI team will not change the output format for the time being. About ossutil, it is not the part of CLI project now, so we don't know the plan of ossutil.
