### ISSUE TITLE
Linux X86版本的工具

### ISSUE THREAD

**Issue by yaowenhui1982** [aliyun/aliyun-cli#880]
![image](https://github.com/aliyun/aliyun-cli/assets/5458544/1606c314-9fc1-49dd-aae0-c07e4cb8fd1f)

* **需求类型**:
平台支持

* **需求描述**:
现在应该大部分Linux还是X86平台上跑的，按理这个工具比ARM和AMD版本的更多才对.

* **设计方案**:
编译测试发布一个Linux X86版本的工具

**Comment by JacksonTian** [comment]
AMD 64 就是 64 位的，如果你说的是 x86 64 的话，也是直接用 AMD 64 就可以的。
