### ISSUE TITLE
安装的官网链接失效

### ISSUE THREAD

**Issue by yaowenhui1982** [aliyun/aliyun-cli#881]
* **命令格式**:
![image](https://github.com/aliyun/aliyun-cli/assets/5458544/0de05ff4-78ff-4b95-a60f-6f91d2761150)

* **执行命令**:

* **输出**:

**Comment by yaowenhui1982** [comment]
英文的可以，中文的不行；
![image](https://github.com/aliyun/aliyun-cli/assets/5458544/629f3dcc-e565-4bf9-a4bf-aa8fd226a285)

**Comment by JacksonTian** [comment]
感谢反馈，已经发 PR 进行修复了。
