### ISSUE TITLE
any problem with current release

### ISSUE THREAD

**Issue by patrickshan** [aliyun/aliyun-cli#9]
I tested with the command described in the doc after config. But it seems those commands don't work at all:
`
$ pip freeze | grep ali
`
aliyuncli==2.1.2
`
$ aliyuncli configure
`
Aliyun Access Key ID [***************_WxyZ]: 
Aliyun Access Key Secret [**_*************w4yX]: 
Default Region Id [cn-hangzhou]: 
Default output format [json]: 
`
$ aliyuncli Ecs DescribeInstances
`
usage: aliyuncli <command> <operation> [options and parameters]
<aliyuncli> the valid command as follows:
`
$ python --version
`
Python 2.7.9

**Comment by luoruici** [comment]
You should install the sdk of each products(ecs, rds...) separately. For example, if you want to use ecs:

```
sudo pip install aliyun-python-sdk-ecs
```

**Comment by WenchaoZeng** [comment]
still not work after sdk is installed.

**Comment by WenchaoZeng** [comment]
Here is the error:
```
xxx@xxx:~# sudo pip install aliyun-python-sdk-ecs
Requirement already satisfied (use --upgrade to upgrade): aliyun-python-sdk-ecs in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): aliyun-python-sdk-core>=2.0.2 in /usr/local/lib/python2.7/dist-packages (from aliyun-python-sdk-ecs)
Cleaning up...
xxx@xxx:~# aliyuncli Ecs DescribeInstances
usage: aliyuncli <command> <operation> [options and parameters]
<aliyuncli> the valid command as follows:
```

**Comment by StephenPCG** [comment]
The same issue occurs in my installation.

in ``aliyunOpenApiData.py`` line 65:

```python
sitepackages_path=get_python_lib()
```

``get_python_lib()`` returns `/usr/lib/python2.7/dist-packages`, while `pip` installs `aliyun-python-sdk-*` in `/usr/local/lib/python2.7/dist-packages`. So aliyuncli searches the wrong directory for sub command packages.

**Comment by keontang** [comment]
In ubuntu or debians:
```
cp -rf /usr/local/lib/python2.7/dist-packages/aliyun* /usr/lib/python2.7/dist-packages
```

fixed the problem.

**Comment by StephenPCG** [comment]
Consider using ``pip.get_installed_distributions()`` to find all installed packages, instead of listing dir of a single site packages path. [pkgutil.iter_modules()](https://docs.python.org/3/library/pkgutil.html#pkgutil.iter_modules) is also a better choice.

**Comment by zerthimon** [comment]
Having the same issue:

Workaround:
```
ln -s /usr/local/lib/python2.7/dist-packages/aliyunsdkecs /usr/lib/python2.7/dist-packages/aliyunsdkecs
```

**Comment by ebsarr** [comment]
This happens on Debian systems because these systems install third party libraries under `/usr/local/lib/python2.7/dist-packages` . However, `aliyuncli` uses `distutils.sysconfig.get_python_lib()` to discover installed aliyun SDKs, and since this function always returns `/usr/lib/python2.7/dist-packages`, `aliyuncli` cannot find the SDK. The work-around is to force `pip` command to install the aliyun SDKs in `/usr/lib/python2.7/dist-packages`.

Example
```
$ dist_packages=$( python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())" )
$ sudo pip install --install-option="--install-purelib=${dist_packages}" aliyuncli
$ sudo pip install --install-option="--install-purelib=${dist_packages}" aliyun-python-sdk-ecs
```

**Comment by tangyouze** [comment]
If the pull request can be merged, I can fix this bug and generate a pull request
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.getsitepackages()
['/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
>>> 
aliyun@alihk9:~$ 
```

http://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory

**Comment by lvscar** [comment]
The bug has been fixed in the current version of aliyuncli, THX.
