### ISSUE TITLE
aliyun cli not working in Alibaba Cloud Linux  3.2104 LTS 64 bit

### ISSUE THREAD

**Issue by Lunartist** [aliyun/aliyun-cli#904]
* **Command Format**:
 aliyun slb DescribeAvailableResource --region ap-southeast-1 --RegionId 'ap-southeast-1'
 (basically all format)
 
* **Execution Command**:
 export DEBUG=sdk
 aliyun slb DescribeAvailableResource --region ap-southeast-1 --RegionId 'ap-southeast-1'
 (basically all commands fail)

* **Output**:
> GET /?AccessKeyId=[mask]&Action=DescribeEndpoints&Format=JSON&Id=ap-southeast-1&RegionId=ap-southeast-1&ServiceCode=slb&Signature=[mask]&SignatureMethod=HMAC-SHA1&SignatureNonce=[mask]&SignatureType=&SignatureVersion=1.0&Timestamp=2023-12-22T08%3A34%3A03Z&Type=openAPI&Version=2015-06-12 HTTP/1.1
> Host: location-readonly.aliyuncs.com
> x-sdk-client: golang/1.0.0
> x-sdk-invoke-type: common
> Accept-Encoding: identity
> User-Agent: AlibabaCloud (linux; amd64) Golang/1.20.11 Core/0.0.1 Aliyun-CLI/3.0.189
> x-acs-version: 2015-06-12
> x-acs-action: DescribeEndpoints
> x-sdk-core-version: 0.0.1
> Content-Type: application/x-www-form-urlencoded
>
 Retry Times: 0.
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: *
< X-Acs-Trace-Id: 21261bae72a7e3b593933daf2081a9a8
< Content-Length: 243
< Connection: keep-alive
< Keep-Alive: timeout=25
< Etag: 2uYNtZQOicMqms2j0NMN+ZQ3
< Date: Fri, 22 Dec 2023 08:34:03 GMT
< Content-Type: application/json;charset=utf-8
< X-Acs-Request-Id: 8E327048-669E-3F9A-A2DD-3D76B52BC7E5
<
{"Endpoints":{"Endpoint":[{"Type":"openAPI","Protocols":{"Protocols":["HTTP","HTTPS"]},"Endpoint":"slb.aliyuncs.com","Id":"ap-southeast-1","SerivceCode":"slb","Namespace":""}]},"RequestId":"8E327048-669E-3F9A-A2DD-3D76B52BC7E5","Success":true}
resolve endpoint with {"Domain":"","Product":"Slb","RegionId":"ap-southeast-1","LocationProduct":"slb","LocationEndpointType":"openAPI"}

        slb.aliyuncs.com by resolver(location resolver)

> POST /?AccessKeyId=[mask]&Action=DescribeAvailableResource&Format=JSON&RegionId=ap-southeast-1&Signature=[mask]&SignatureMethod=HMAC-SHA1&SignatureNonce=[mask]&SignatureType=&SignatureVersion=1.0&Timestamp=2023-12-22T08%3A34%3A03Z&Version=2014-05-15 HTTP/1.1
> Host: slb.aliyuncs.com
> Content-Type: application/x-www-form-urlencoded
> x-sdk-client: golang/1.0.0
> x-sdk-invoke-type: common
> User-Agent: AlibabaCloud (linux; amd64) Golang/1.20.11 Core/0.0.1 Aliyun-CLI/3.0.189
> Accept-Encoding: identity
> x-acs-version: 2014-05-15
> x-acs-action: DescribeAvailableResource
> x-sdk-core-version: 0.0.1
>
 Retry Times: 0.
<
 Error: Post "http://slb.aliyuncs.com/?AccessKeyId=[mask]&Action=DescribeAvailableResource&Format=JSON&RegionId=ap-southeast-1&Signature=[mask]&SignatureMethod=HMAC-SHA1&SignatureNonce=[mask]&SignatureType=&SignatureVersion=1.0&Timestamp=2023-12-22T08%3A34%3A03Z&Version=2014-05-15": EOF.
ERROR: Post "http://slb.aliyuncs.com/?AccessKeyId=[mask]&Action=DescribeAvailableResource&Format=JSON&RegionId=ap-southeast-1&Signature=[mask]&SignatureMethod=HMAC-SHA1&SignatureNonce=[mask]&SignatureType=&SignatureVersion=1.0&Timestamp=2023-12-22T08%3A34%3A03Z&Version=2014-05-15": EOF

aliyun version 3.0.189

[bpimanager@louis temp]$ cat /etc/os-release
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

[bpimanager@louis temp]$ bash -version
GNU bash, version 4.4.20(1)-release (x86_64-koji-linux-gnu)

**Comment by JacksonTian** [comment]
This is a network issue. Not OS related.

**Comment by Lunartist** [comment]
![2023-12-26 13_35_23-bastion-uat](https://github.com/aliyun/aliyun-cli/assets/60244788/c8ecc22c-3988-4024-8a53-84ce79e83e52)
Ping is OK. Doesn't it mean the network is connected?

**Comment by Lunartist** [comment]
Firewall was not the problem. Alibaba CLI's endpoint is fixed to Chinese endpoint and is blocked when used for international resources.
This solved My problem
`aliyun slb DescribeAvailableResource --region ap-southeast-1 --RegionId 'ap-southeast-1' --endpoint slb-vpc.ap-southeast-1.aliyuncs.com`

**Comment by Lunartist** [comment]
Can we change default endpoint?
