### ISSUE TITLE
Add support for MQC

### ISSUE THREAD

**Issue by Chaoba** [aliyun/aliyun-cli#91]
Searched from [api center](https://developer.aliyun.com/api) that there is no api for [MQC](http://mqc.aliyun.com/?spm=a2c0i.7764369.1999348069.1.4737a377W5rDHc).
Could you please add this api into aliyun-cli? So we can integrate app compatibility test into our CI.

**Comment by JacksonTian** [comment]
Hi @Chaoba The MQC has not OpenAPI, so the cli tool can not support it.
