### ISSUE TITLE
NAS CreateFileSystem does not work (EOF Error)

### ISSUE THREAD

**Issue by arafato** [aliyun/aliyun-cli#92]
Hi--
```
$ aliyun nas CreateFileSystem --RegionId=eu-central-1 --ZoneId=eu-central-1a --FileSystemType=Performance --ProtocolType=NFS
```
does not work. Also with other regions such as `cn-bejing`.
The error is (removed access key):
```
ERROR: Post http://nas.eu-central-1.aliyuncs.com/?AccessKeyId=<my_access_key>&Action=CreateFileSystem&FileSystemType=Performance&Format=JSON&ProtocolType=NFS&RegionId=eu-central-1&Signature=uUaN5iHwDVvLId7YCeqxs4zyeq8%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=9090f8254d2041619809d08dc7ae3cb6&SignatureType=&SignatureVersion=1.0&Timestamp=2018-12-05T07%3A33%3A06Z&Version=2016-02-29&ZoneId=eu-central-1a: EOF
```

Can you please fix this? Thanks!

**Comment by night556** [comment]
> Hi--
> 
> ```
> $ aliyun nas CreateFileSystem --RegionId=eu-central-1 --ZoneId=eu-central-1a --FileSystemType=Performance --ProtocolType=NFS
> ```
> does not work. Also with other regions such as `cn-bejing`.
> The error is (removed access key):
> 
> ```
> ERROR: Post http://nas.eu-central-1.aliyuncs.com/?AccessKeyId=<my_access_key>&Action=CreateFileSystem&FileSystemType=Performance&Format=JSON&ProtocolType=NFS&RegionId=eu-central-1&Signature=uUaN5iHwDVvLId7YCeqxs4zyeq8%3D&SignatureMethod=HMAC-SHA1&SignatureNonce=9090f8254d2041619809d08dc7ae3cb6&SignatureType=&SignatureVersion=1.0&Timestamp=2018-12-05T07%3A33%3A06Z&Version=2016-02-29&ZoneId=eu-central-1a: EOF
> ```
> Can you please fix this? Thanks!

Hi, the cli tool has been update to version 3.0.10, We recommend that you upgrade and try again. If you have problems still, please contact with us.
Thank you for your attention to AliCloud CLI Project!
