### ISSUE TITLE
help里要求用Permissions.N.xxx参数 但是help里没有列出来 也用不了

### ISSUE THREAD

**Issue by mondomuyo** [aliyun/aliyun-cli#924]
* **命令格式**:
aliyun help ecs AuthorizeSecurityGroupEgress
* **执行命令**:
aliyun help ecs AuthorizeSecurityGroupEgress
* **输出**:
Alibaba Cloud Command Line Interface Version 3.0.196

Product: Ecs (Elastic Compute Service)

Parameters:
  --RegionId String  Required

  The region ID of the source security group. You can call the [DescribeRegions](~~25609~~) operation to query the most recent region list.

  --SecurityGroupId String  Required

  The security group ID.

  --ClientToken String  Optional

  The client token that is used to ensure the idempotence of the request. You can use the client to generate the token, but you must make sure that the token is unique among different requests. The **token** can contain only ASCII characters and cannot exceed 64 characters in length. For more information, see [Ensure idempotence](~~25693~~).

  --Description String  Optional

  This parameter is deprecated. Use `Permissions.N.Description` to specify the description of security group rule N.

  --DestCidrIp String  Optional

  This parameter is deprecated. Use `Permissions.N.DestCidrIp` to specify the destination IPv4 CIDR block.

  --DestGroupId String  Optional

  This parameter is deprecated. Use `Permissions.N.DestGroupId` to specify the ID of the destination security group.

  --DestGroupOwnerAccount String  Optional

  This parameter is deprecated. Use `Permissions.N.DestGroupOwnerAccount` to specify the Alibaba Cloud account that manages the destination security group.

  --DestGroupOwnerId Long    Optional

  This parameter is deprecated. Use `Permissions.N.DestGroupOwnerId` to specify the ID of the Alibaba Cloud account that manages the destination security group.

  --DestPrefixListId String  Optional

  This parameter is deprecated. Use `Permissions.N.DestPrefixListId` to specify the ID of the destination prefix list.

  --IpProtocol String  Optional

  This parameter is deprecated. Use `Permissions.N.IpProtocol` to specify the transport layer protocol.

  --Ipv6DestCidrIp String  Optional

  This parameter is deprecated. Use `Permissions.N.Ipv6DestCidrIp` to specify the destination IPv6 CIDR block.

  --Ipv6SourceCidrIp String  Optional

  This parameter is deprecated. Use `Permissions.N.Ipv6SourceCidrIp` to specify the source IPv6 CIDR block.

  --NicType String  Optional

  This parameter is deprecated. Use `Permissions.N.NicType` to specify the NIC type.

  --Permissions Array   Optional

  The security group rules. Valid values of N: 1 to 100.

  --Policy String  Optional

  This parameter is deprecated. Use `Permissions.N.Policy` to specify whether to allow outbound access.

  --PortRange String  Optional

  This parameter is deprecated. Use `Permissions.N.PortRange` to specify the range of destination ports.

  --Priority String  Optional

  This parameter is deprecated. Use `Permissions.N.Priority` to specify the rule priority.

  --SourceCidrIp String  Optional

  This parameter is deprecated. Use `Permissions.N.SourceCidrIp` to specify the source IPv4 CIDR block.

  --SourcePortRange String  Optional

  This parameter is deprecated. Use `Permissions.N.SourcePortRange` to specify the range of source ports.

<img width="1563" alt="image" src="https://github.com/aliyun/aliyun-cli/assets/50761361/2cb2f4ef-c199-40c8-a6bd-f18b3235e947">

**Comment by JacksonTian** [comment]
https://api.aliyun.com/api/Ecs/2014-05-26/AuthorizeSecurityGroupEgress?tab=CLI&params={%22RegionId%22:%22cn-beijing%22,%22Permissions%22:[{%22Policy%22:%221%22,%22Priority%22:%222%22,%22IpProtocol%22:%223%22}]} 可以先按API 门户的指导来使用。目前 Help 信息对于复杂结构支持还不够完善。

**Comment by mondomuyo** [comment]
明白了 我加个--force试试 谢谢
