### ISSUE TITLE
How can create container service k8s cluster with aliyuncli ?

### ISSUE THREAD

**Issue by minhtran-agilityio** [aliyun/aliyun-cli#94]
**Background information**:
I follow this link https://pypi.org/project/aliyuncli/ to setup `aliyuncli`:
- installed `pip install aliyuncli`
- installed `pip install aliyun-python-sdk-cs`
- executed configuration with `aliyuncli configure`

I want to create container service k8s cluster from command line like `aliyuncli cs CreateCluster`
You can see this screenshot ---> https://www.evernote.com/l/AdfFjVzMd0hMRZjdKKh8ie3tzt1sBrhsXzsB/image.png

**Questions**:
- What's params will be passed after that `aliyuncli cs CreateCluster ??? ???`

**Note**:
- I want to use `aliyuncli` not `aliyun`

**Comment by night556** [comment]
The Python version of the CLI has stopped maintenance，you can got the new release version of CLI which reconfiguration by Golang , and there is a website (https://help.aliyun.com/document_detail/71197.html?spm=a2c4g.11174283.6.732.45d57a22245InW) , which will help you with your question.
Thank you for your attention to AliCloud CLI Project！
